// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BoardCastInfo.proto

#ifndef PROTOBUF_BoardCastInfo_2eproto__INCLUDED
#define PROTOBUF_BoardCastInfo_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_BoardCastInfo_2eproto();
void protobuf_AssignDesc_BoardCastInfo_2eproto();
void protobuf_ShutdownFile_BoardCastInfo_2eproto();

class OPBoardCastInfo;
class OPBoardCastInfoRet;
class OPBoardCastInfoRet_BoardCast;

// ===================================================================

class OPBoardCastInfo : public ::google::protobuf::Message {
 public:
  OPBoardCastInfo();
  virtual ~OPBoardCastInfo();

  OPBoardCastInfo(const OPBoardCastInfo& from);

  inline OPBoardCastInfo& operator=(const OPBoardCastInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const OPBoardCastInfo& default_instance();

  void Swap(OPBoardCastInfo* other);

  // implements Message ----------------------------------------------

  OPBoardCastInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const OPBoardCastInfo& from);
  void MergeFrom(const OPBoardCastInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 version = 1;
  inline bool has_version() const;
  inline void clear_version();
  static const int kVersionFieldNumber = 1;
  inline ::google::protobuf::int32 version() const;
  inline void set_version(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:OPBoardCastInfo)
 private:
  inline void set_has_version();
  inline void clear_has_version();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 version_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_BoardCastInfo_2eproto();
  friend void protobuf_AssignDesc_BoardCastInfo_2eproto();
  friend void protobuf_ShutdownFile_BoardCastInfo_2eproto();

  void InitAsDefaultInstance();
  static OPBoardCastInfo* default_instance_;
};
// -------------------------------------------------------------------

class OPBoardCastInfoRet_BoardCast : public ::google::protobuf::Message {
 public:
  OPBoardCastInfoRet_BoardCast();
  virtual ~OPBoardCastInfoRet_BoardCast();

  OPBoardCastInfoRet_BoardCast(const OPBoardCastInfoRet_BoardCast& from);

  inline OPBoardCastInfoRet_BoardCast& operator=(const OPBoardCastInfoRet_BoardCast& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const OPBoardCastInfoRet_BoardCast& default_instance();

  void Swap(OPBoardCastInfoRet_BoardCast* other);

  // implements Message ----------------------------------------------

  OPBoardCastInfoRet_BoardCast* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const OPBoardCastInfoRet_BoardCast& from);
  void MergeFrom(const OPBoardCastInfoRet_BoardCast& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 type = 1;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 1;
  inline ::google::protobuf::int32 type() const;
  inline void set_type(::google::protobuf::int32 value);

  // required string name = 2;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 2;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // repeated int32 params = 3;
  inline int params_size() const;
  inline void clear_params();
  static const int kParamsFieldNumber = 3;
  inline ::google::protobuf::int32 params(int index) const;
  inline void set_params(int index, ::google::protobuf::int32 value);
  inline void add_params(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      params() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_params();

  // @@protoc_insertion_point(class_scope:OPBoardCastInfoRet.BoardCast)
 private:
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_name();
  inline void clear_has_name();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* name_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > params_;
  ::google::protobuf::int32 type_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_BoardCastInfo_2eproto();
  friend void protobuf_AssignDesc_BoardCastInfo_2eproto();
  friend void protobuf_ShutdownFile_BoardCastInfo_2eproto();

  void InitAsDefaultInstance();
  static OPBoardCastInfoRet_BoardCast* default_instance_;
};
// -------------------------------------------------------------------

class OPBoardCastInfoRet : public ::google::protobuf::Message {
 public:
  OPBoardCastInfoRet();
  virtual ~OPBoardCastInfoRet();

  OPBoardCastInfoRet(const OPBoardCastInfoRet& from);

  inline OPBoardCastInfoRet& operator=(const OPBoardCastInfoRet& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const OPBoardCastInfoRet& default_instance();

  void Swap(OPBoardCastInfoRet* other);

  // implements Message ----------------------------------------------

  OPBoardCastInfoRet* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const OPBoardCastInfoRet& from);
  void MergeFrom(const OPBoardCastInfoRet& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef OPBoardCastInfoRet_BoardCast BoardCast;

  // accessors -------------------------------------------------------

  // required int32 servertime = 1;
  inline bool has_servertime() const;
  inline void clear_servertime();
  static const int kServertimeFieldNumber = 1;
  inline ::google::protobuf::int32 servertime() const;
  inline void set_servertime(::google::protobuf::int32 value);

  // repeated .OPBoardCastInfoRet.BoardCast boardCastInfo = 2;
  inline int boardcastinfo_size() const;
  inline void clear_boardcastinfo();
  static const int kBoardCastInfoFieldNumber = 2;
  inline const ::OPBoardCastInfoRet_BoardCast& boardcastinfo(int index) const;
  inline ::OPBoardCastInfoRet_BoardCast* mutable_boardcastinfo(int index);
  inline ::OPBoardCastInfoRet_BoardCast* add_boardcastinfo();
  inline const ::google::protobuf::RepeatedPtrField< ::OPBoardCastInfoRet_BoardCast >&
      boardcastinfo() const;
  inline ::google::protobuf::RepeatedPtrField< ::OPBoardCastInfoRet_BoardCast >*
      mutable_boardcastinfo();

  // @@protoc_insertion_point(class_scope:OPBoardCastInfoRet)
 private:
  inline void set_has_servertime();
  inline void clear_has_servertime();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::OPBoardCastInfoRet_BoardCast > boardcastinfo_;
  ::google::protobuf::int32 servertime_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_BoardCastInfo_2eproto();
  friend void protobuf_AssignDesc_BoardCastInfo_2eproto();
  friend void protobuf_ShutdownFile_BoardCastInfo_2eproto();

  void InitAsDefaultInstance();
  static OPBoardCastInfoRet* default_instance_;
};
// ===================================================================


// ===================================================================

// OPBoardCastInfo

// required int32 version = 1;
inline bool OPBoardCastInfo::has_version() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void OPBoardCastInfo::set_has_version() {
  _has_bits_[0] |= 0x00000001u;
}
inline void OPBoardCastInfo::clear_has_version() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void OPBoardCastInfo::clear_version() {
  version_ = 0;
  clear_has_version();
}
inline ::google::protobuf::int32 OPBoardCastInfo::version() const {
  return version_;
}
inline void OPBoardCastInfo::set_version(::google::protobuf::int32 value) {
  set_has_version();
  version_ = value;
}

// -------------------------------------------------------------------

// OPBoardCastInfoRet_BoardCast

// required int32 type = 1;
inline bool OPBoardCastInfoRet_BoardCast::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void OPBoardCastInfoRet_BoardCast::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void OPBoardCastInfoRet_BoardCast::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void OPBoardCastInfoRet_BoardCast::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::google::protobuf::int32 OPBoardCastInfoRet_BoardCast::type() const {
  return type_;
}
inline void OPBoardCastInfoRet_BoardCast::set_type(::google::protobuf::int32 value) {
  set_has_type();
  type_ = value;
}

// required string name = 2;
inline bool OPBoardCastInfoRet_BoardCast::has_name() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void OPBoardCastInfoRet_BoardCast::set_has_name() {
  _has_bits_[0] |= 0x00000002u;
}
inline void OPBoardCastInfoRet_BoardCast::clear_has_name() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void OPBoardCastInfoRet_BoardCast::clear_name() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& OPBoardCastInfoRet_BoardCast::name() const {
  return *name_;
}
inline void OPBoardCastInfoRet_BoardCast::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void OPBoardCastInfoRet_BoardCast::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void OPBoardCastInfoRet_BoardCast::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* OPBoardCastInfoRet_BoardCast::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  return name_;
}
inline ::std::string* OPBoardCastInfoRet_BoardCast::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void OPBoardCastInfoRet_BoardCast::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// repeated int32 params = 3;
inline int OPBoardCastInfoRet_BoardCast::params_size() const {
  return params_.size();
}
inline void OPBoardCastInfoRet_BoardCast::clear_params() {
  params_.Clear();
}
inline ::google::protobuf::int32 OPBoardCastInfoRet_BoardCast::params(int index) const {
  return params_.Get(index);
}
inline void OPBoardCastInfoRet_BoardCast::set_params(int index, ::google::protobuf::int32 value) {
  params_.Set(index, value);
}
inline void OPBoardCastInfoRet_BoardCast::add_params(::google::protobuf::int32 value) {
  params_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
OPBoardCastInfoRet_BoardCast::params() const {
  return params_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
OPBoardCastInfoRet_BoardCast::mutable_params() {
  return &params_;
}

// -------------------------------------------------------------------

// OPBoardCastInfoRet

// required int32 servertime = 1;
inline bool OPBoardCastInfoRet::has_servertime() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void OPBoardCastInfoRet::set_has_servertime() {
  _has_bits_[0] |= 0x00000001u;
}
inline void OPBoardCastInfoRet::clear_has_servertime() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void OPBoardCastInfoRet::clear_servertime() {
  servertime_ = 0;
  clear_has_servertime();
}
inline ::google::protobuf::int32 OPBoardCastInfoRet::servertime() const {
  return servertime_;
}
inline void OPBoardCastInfoRet::set_servertime(::google::protobuf::int32 value) {
  set_has_servertime();
  servertime_ = value;
}

// repeated .OPBoardCastInfoRet.BoardCast boardCastInfo = 2;
inline int OPBoardCastInfoRet::boardcastinfo_size() const {
  return boardcastinfo_.size();
}
inline void OPBoardCastInfoRet::clear_boardcastinfo() {
  boardcastinfo_.Clear();
}
inline const ::OPBoardCastInfoRet_BoardCast& OPBoardCastInfoRet::boardcastinfo(int index) const {
  return boardcastinfo_.Get(index);
}
inline ::OPBoardCastInfoRet_BoardCast* OPBoardCastInfoRet::mutable_boardcastinfo(int index) {
  return boardcastinfo_.Mutable(index);
}
inline ::OPBoardCastInfoRet_BoardCast* OPBoardCastInfoRet::add_boardcastinfo() {
  return boardcastinfo_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::OPBoardCastInfoRet_BoardCast >&
OPBoardCastInfoRet::boardcastinfo() const {
  return boardcastinfo_;
}
inline ::google::protobuf::RepeatedPtrField< ::OPBoardCastInfoRet_BoardCast >*
OPBoardCastInfoRet::mutable_boardcastinfo() {
  return &boardcastinfo_;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_BoardCastInfo_2eproto__INCLUDED
