// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RecordReadMsgTime.proto

#ifndef PROTOBUF_RecordReadMsgTime_2eproto__INCLUDED
#define PROTOBUF_RecordReadMsgTime_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_RecordReadMsgTime_2eproto();
void protobuf_AssignDesc_RecordReadMsgTime_2eproto();
void protobuf_ShutdownFile_RecordReadMsgTime_2eproto();

class OPRecordReadMsgTime;
class OPRecordReadMsgTimeRet;

// ===================================================================

class OPRecordReadMsgTime : public ::google::protobuf::Message {
 public:
  OPRecordReadMsgTime();
  virtual ~OPRecordReadMsgTime();

  OPRecordReadMsgTime(const OPRecordReadMsgTime& from);

  inline OPRecordReadMsgTime& operator=(const OPRecordReadMsgTime& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const OPRecordReadMsgTime& default_instance();

  void Swap(OPRecordReadMsgTime* other);

  // implements Message ----------------------------------------------

  OPRecordReadMsgTime* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const OPRecordReadMsgTime& from);
  void MergeFrom(const OPRecordReadMsgTime& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 version = 1 [default = 1];
  inline bool has_version() const;
  inline void clear_version();
  static const int kVersionFieldNumber = 1;
  inline ::google::protobuf::int32 version() const;
  inline void set_version(::google::protobuf::int32 value);

  // optional int32 id = 2;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 2;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:OPRecordReadMsgTime)
 private:
  inline void set_has_version();
  inline void clear_has_version();
  inline void set_has_id();
  inline void clear_has_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 version_;
  ::google::protobuf::int32 id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_RecordReadMsgTime_2eproto();
  friend void protobuf_AssignDesc_RecordReadMsgTime_2eproto();
  friend void protobuf_ShutdownFile_RecordReadMsgTime_2eproto();

  void InitAsDefaultInstance();
  static OPRecordReadMsgTime* default_instance_;
};
// -------------------------------------------------------------------

class OPRecordReadMsgTimeRet : public ::google::protobuf::Message {
 public:
  OPRecordReadMsgTimeRet();
  virtual ~OPRecordReadMsgTimeRet();

  OPRecordReadMsgTimeRet(const OPRecordReadMsgTimeRet& from);

  inline OPRecordReadMsgTimeRet& operator=(const OPRecordReadMsgTimeRet& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const OPRecordReadMsgTimeRet& default_instance();

  void Swap(OPRecordReadMsgTimeRet* other);

  // implements Message ----------------------------------------------

  OPRecordReadMsgTimeRet* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const OPRecordReadMsgTimeRet& from);
  void MergeFrom(const OPRecordReadMsgTimeRet& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 servertime = 1;
  inline bool has_servertime() const;
  inline void clear_servertime();
  static const int kServertimeFieldNumber = 1;
  inline ::google::protobuf::int32 servertime() const;
  inline void set_servertime(::google::protobuf::int32 value);

  // repeated int32 stats = 2;
  inline int stats_size() const;
  inline void clear_stats();
  static const int kStatsFieldNumber = 2;
  inline ::google::protobuf::int32 stats(int index) const;
  inline void set_stats(int index, ::google::protobuf::int32 value);
  inline void add_stats(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      stats() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_stats();

  // @@protoc_insertion_point(class_scope:OPRecordReadMsgTimeRet)
 private:
  inline void set_has_servertime();
  inline void clear_has_servertime();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > stats_;
  ::google::protobuf::int32 servertime_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_RecordReadMsgTime_2eproto();
  friend void protobuf_AssignDesc_RecordReadMsgTime_2eproto();
  friend void protobuf_ShutdownFile_RecordReadMsgTime_2eproto();

  void InitAsDefaultInstance();
  static OPRecordReadMsgTimeRet* default_instance_;
};
// ===================================================================


// ===================================================================

// OPRecordReadMsgTime

// required int32 version = 1 [default = 1];
inline bool OPRecordReadMsgTime::has_version() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void OPRecordReadMsgTime::set_has_version() {
  _has_bits_[0] |= 0x00000001u;
}
inline void OPRecordReadMsgTime::clear_has_version() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void OPRecordReadMsgTime::clear_version() {
  version_ = 1;
  clear_has_version();
}
inline ::google::protobuf::int32 OPRecordReadMsgTime::version() const {
  return version_;
}
inline void OPRecordReadMsgTime::set_version(::google::protobuf::int32 value) {
  set_has_version();
  version_ = value;
}

// optional int32 id = 2;
inline bool OPRecordReadMsgTime::has_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void OPRecordReadMsgTime::set_has_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void OPRecordReadMsgTime::clear_has_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void OPRecordReadMsgTime::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 OPRecordReadMsgTime::id() const {
  return id_;
}
inline void OPRecordReadMsgTime::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
}

// -------------------------------------------------------------------

// OPRecordReadMsgTimeRet

// required int32 servertime = 1;
inline bool OPRecordReadMsgTimeRet::has_servertime() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void OPRecordReadMsgTimeRet::set_has_servertime() {
  _has_bits_[0] |= 0x00000001u;
}
inline void OPRecordReadMsgTimeRet::clear_has_servertime() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void OPRecordReadMsgTimeRet::clear_servertime() {
  servertime_ = 0;
  clear_has_servertime();
}
inline ::google::protobuf::int32 OPRecordReadMsgTimeRet::servertime() const {
  return servertime_;
}
inline void OPRecordReadMsgTimeRet::set_servertime(::google::protobuf::int32 value) {
  set_has_servertime();
  servertime_ = value;
}

// repeated int32 stats = 2;
inline int OPRecordReadMsgTimeRet::stats_size() const {
  return stats_.size();
}
inline void OPRecordReadMsgTimeRet::clear_stats() {
  stats_.Clear();
}
inline ::google::protobuf::int32 OPRecordReadMsgTimeRet::stats(int index) const {
  return stats_.Get(index);
}
inline void OPRecordReadMsgTimeRet::set_stats(int index, ::google::protobuf::int32 value) {
  stats_.Set(index, value);
}
inline void OPRecordReadMsgTimeRet::add_stats(::google::protobuf::int32 value) {
  stats_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
OPRecordReadMsgTimeRet::stats() const {
  return stats_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
OPRecordReadMsgTimeRet::mutable_stats() {
  return &stats_;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_RecordReadMsgTime_2eproto__INCLUDED
