
#include "stdafx.h"

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SnatchSkillBook.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "SnatchSkillBook.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* OPSnatchSkillBook_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  OPSnatchSkillBook_reflection_ = NULL;
const ::google::protobuf::Descriptor* OPSnatchSkillBookRet_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  OPSnatchSkillBookRet_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_SnatchSkillBook_2eproto() {
  protobuf_AddDesc_SnatchSkillBook_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "SnatchSkillBook.proto");
  GOOGLE_CHECK(file != NULL);
  OPSnatchSkillBook_descriptor_ = file->message_type(0);
  static const int OPSnatchSkillBook_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OPSnatchSkillBook, version_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OPSnatchSkillBook, playerid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OPSnatchSkillBook, bookid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OPSnatchSkillBook, isnpc_),
  };
  OPSnatchSkillBook_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      OPSnatchSkillBook_descriptor_,
      OPSnatchSkillBook::default_instance_,
      OPSnatchSkillBook_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OPSnatchSkillBook, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OPSnatchSkillBook, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(OPSnatchSkillBook));
  OPSnatchSkillBookRet_descriptor_ = file->message_type(1);
  static const int OPSnatchSkillBookRet_offsets_[5] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OPSnatchSkillBookRet, servertime_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OPSnatchSkillBookRet, status_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OPSnatchSkillBookRet, ret_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OPSnatchSkillBookRet, battle_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OPSnatchSkillBookRet, vitality_),
  };
  OPSnatchSkillBookRet_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      OPSnatchSkillBookRet_descriptor_,
      OPSnatchSkillBookRet::default_instance_,
      OPSnatchSkillBookRet_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OPSnatchSkillBookRet, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OPSnatchSkillBookRet, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(OPSnatchSkillBookRet));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_SnatchSkillBook_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    OPSnatchSkillBook_descriptor_, &OPSnatchSkillBook::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    OPSnatchSkillBookRet_descriptor_, &OPSnatchSkillBookRet::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_SnatchSkillBook_2eproto() {
  delete OPSnatchSkillBook::default_instance_;
  delete OPSnatchSkillBook_reflection_;
  delete OPSnatchSkillBookRet::default_instance_;
  delete OPSnatchSkillBookRet_reflection_;
}

void protobuf_AddDesc_SnatchSkillBook_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::protobuf_AddDesc_UserBattle_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\025SnatchSkillBook.proto\032\020UserBattle.prot"
    "o\"X\n\021OPSnatchSkillBook\022\022\n\007version\030\001 \002(\005:"
    "\0011\022\020\n\010playerId\030\002 \002(\005\022\016\n\006bookId\030\003 \002(\005\022\r\n\005"
    "isNpc\030\004 \002(\005\"{\n\024OPSnatchSkillBookRet\022\022\n\ns"
    "ervertime\030\001 \002(\005\022\016\n\006status\030\002 \002(\005\022\013\n\003ret\030\003"
    " \002(\005\022 \n\006battle\030\004 \001(\0132\020.OPUserBattleRet\022\020"
    "\n\010vitality\030\005 \002(\005B\035\n\033com.oldmountain.dzm."
    "message", 287);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "SnatchSkillBook.proto", &protobuf_RegisterTypes);
  OPSnatchSkillBook::default_instance_ = new OPSnatchSkillBook();
  OPSnatchSkillBookRet::default_instance_ = new OPSnatchSkillBookRet();
  OPSnatchSkillBook::default_instance_->InitAsDefaultInstance();
  OPSnatchSkillBookRet::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_SnatchSkillBook_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_SnatchSkillBook_2eproto {
  StaticDescriptorInitializer_SnatchSkillBook_2eproto() {
    protobuf_AddDesc_SnatchSkillBook_2eproto();
  }
} static_descriptor_initializer_SnatchSkillBook_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int OPSnatchSkillBook::kVersionFieldNumber;
const int OPSnatchSkillBook::kPlayerIdFieldNumber;
const int OPSnatchSkillBook::kBookIdFieldNumber;
const int OPSnatchSkillBook::kIsNpcFieldNumber;
#endif  // !_MSC_VER

OPSnatchSkillBook::OPSnatchSkillBook()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void OPSnatchSkillBook::InitAsDefaultInstance() {
}

OPSnatchSkillBook::OPSnatchSkillBook(const OPSnatchSkillBook& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void OPSnatchSkillBook::SharedCtor() {
  _cached_size_ = 0;
  version_ = 1;
  playerid_ = 0;
  bookid_ = 0;
  isnpc_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

OPSnatchSkillBook::~OPSnatchSkillBook() {
  SharedDtor();
}

void OPSnatchSkillBook::SharedDtor() {
  if (this != default_instance_) {
  }
}

void OPSnatchSkillBook::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* OPSnatchSkillBook::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return OPSnatchSkillBook_descriptor_;
}

const OPSnatchSkillBook& OPSnatchSkillBook::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_SnatchSkillBook_2eproto();
  return *default_instance_;
}

OPSnatchSkillBook* OPSnatchSkillBook::default_instance_ = NULL;

OPSnatchSkillBook* OPSnatchSkillBook::New() const {
  return new OPSnatchSkillBook;
}

void OPSnatchSkillBook::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    version_ = 1;
    playerid_ = 0;
    bookid_ = 0;
    isnpc_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool OPSnatchSkillBook::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 version = 1 [default = 1];
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &version_)));
          set_has_version();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_playerId;
        break;
      }

      // required int32 playerId = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_playerId:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &playerid_)));
          set_has_playerid();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_bookId;
        break;
      }

      // required int32 bookId = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_bookId:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &bookid_)));
          set_has_bookid();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(32)) goto parse_isNpc;
        break;
      }

      // required int32 isNpc = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_isNpc:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &isnpc_)));
          set_has_isnpc();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void OPSnatchSkillBook::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required int32 version = 1 [default = 1];
  if (has_version()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->version(), output);
  }

  // required int32 playerId = 2;
  if (has_playerid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->playerid(), output);
  }

  // required int32 bookId = 3;
  if (has_bookid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->bookid(), output);
  }

  // required int32 isNpc = 4;
  if (has_isnpc()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->isnpc(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* OPSnatchSkillBook::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required int32 version = 1 [default = 1];
  if (has_version()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->version(), target);
  }

  // required int32 playerId = 2;
  if (has_playerid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->playerid(), target);
  }

  // required int32 bookId = 3;
  if (has_bookid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->bookid(), target);
  }

  // required int32 isNpc = 4;
  if (has_isnpc()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->isnpc(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int OPSnatchSkillBook::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 version = 1 [default = 1];
    if (has_version()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->version());
    }

    // required int32 playerId = 2;
    if (has_playerid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->playerid());
    }

    // required int32 bookId = 3;
    if (has_bookid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->bookid());
    }

    // required int32 isNpc = 4;
    if (has_isnpc()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->isnpc());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void OPSnatchSkillBook::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const OPSnatchSkillBook* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const OPSnatchSkillBook*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void OPSnatchSkillBook::MergeFrom(const OPSnatchSkillBook& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_version()) {
      set_version(from.version());
    }
    if (from.has_playerid()) {
      set_playerid(from.playerid());
    }
    if (from.has_bookid()) {
      set_bookid(from.bookid());
    }
    if (from.has_isnpc()) {
      set_isnpc(from.isnpc());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void OPSnatchSkillBook::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void OPSnatchSkillBook::CopyFrom(const OPSnatchSkillBook& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool OPSnatchSkillBook::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000000f) != 0x0000000f) return false;

  return true;
}

void OPSnatchSkillBook::Swap(OPSnatchSkillBook* other) {
  if (other != this) {
    std::swap(version_, other->version_);
    std::swap(playerid_, other->playerid_);
    std::swap(bookid_, other->bookid_);
    std::swap(isnpc_, other->isnpc_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata OPSnatchSkillBook::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = OPSnatchSkillBook_descriptor_;
  metadata.reflection = OPSnatchSkillBook_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int OPSnatchSkillBookRet::kServertimeFieldNumber;
const int OPSnatchSkillBookRet::kStatusFieldNumber;
const int OPSnatchSkillBookRet::kRetFieldNumber;
const int OPSnatchSkillBookRet::kBattleFieldNumber;
const int OPSnatchSkillBookRet::kVitalityFieldNumber;
#endif  // !_MSC_VER

OPSnatchSkillBookRet::OPSnatchSkillBookRet()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void OPSnatchSkillBookRet::InitAsDefaultInstance() {
  battle_ = const_cast< ::OPUserBattleRet*>(&::OPUserBattleRet::default_instance());
}

OPSnatchSkillBookRet::OPSnatchSkillBookRet(const OPSnatchSkillBookRet& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void OPSnatchSkillBookRet::SharedCtor() {
  _cached_size_ = 0;
  servertime_ = 0;
  status_ = 0;
  ret_ = 0;
  battle_ = NULL;
  vitality_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

OPSnatchSkillBookRet::~OPSnatchSkillBookRet() {
  SharedDtor();
}

void OPSnatchSkillBookRet::SharedDtor() {
  if (this != default_instance_) {
    delete battle_;
  }
}

void OPSnatchSkillBookRet::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* OPSnatchSkillBookRet::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return OPSnatchSkillBookRet_descriptor_;
}

const OPSnatchSkillBookRet& OPSnatchSkillBookRet::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_SnatchSkillBook_2eproto();
  return *default_instance_;
}

OPSnatchSkillBookRet* OPSnatchSkillBookRet::default_instance_ = NULL;

OPSnatchSkillBookRet* OPSnatchSkillBookRet::New() const {
  return new OPSnatchSkillBookRet;
}

void OPSnatchSkillBookRet::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    servertime_ = 0;
    status_ = 0;
    ret_ = 0;
    if (has_battle()) {
      if (battle_ != NULL) battle_->::OPUserBattleRet::Clear();
    }
    vitality_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool OPSnatchSkillBookRet::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 servertime = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &servertime_)));
          set_has_servertime();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_status;
        break;
      }

      // required int32 status = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_status:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &status_)));
          set_has_status();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_ret;
        break;
      }

      // required int32 ret = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_ret:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &ret_)));
          set_has_ret();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(34)) goto parse_battle;
        break;
      }

      // optional .OPUserBattleRet battle = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_battle:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_battle()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(40)) goto parse_vitality;
        break;
      }

      // required int32 vitality = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_vitality:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &vitality_)));
          set_has_vitality();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void OPSnatchSkillBookRet::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required int32 servertime = 1;
  if (has_servertime()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->servertime(), output);
  }

  // required int32 status = 2;
  if (has_status()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->status(), output);
  }

  // required int32 ret = 3;
  if (has_ret()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->ret(), output);
  }

  // optional .OPUserBattleRet battle = 4;
  if (has_battle()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, this->battle(), output);
  }

  // required int32 vitality = 5;
  if (has_vitality()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->vitality(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* OPSnatchSkillBookRet::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required int32 servertime = 1;
  if (has_servertime()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->servertime(), target);
  }

  // required int32 status = 2;
  if (has_status()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->status(), target);
  }

  // required int32 ret = 3;
  if (has_ret()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->ret(), target);
  }

  // optional .OPUserBattleRet battle = 4;
  if (has_battle()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        4, this->battle(), target);
  }

  // required int32 vitality = 5;
  if (has_vitality()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->vitality(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int OPSnatchSkillBookRet::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 servertime = 1;
    if (has_servertime()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->servertime());
    }

    // required int32 status = 2;
    if (has_status()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->status());
    }

    // required int32 ret = 3;
    if (has_ret()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->ret());
    }

    // optional .OPUserBattleRet battle = 4;
    if (has_battle()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->battle());
    }

    // required int32 vitality = 5;
    if (has_vitality()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->vitality());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void OPSnatchSkillBookRet::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const OPSnatchSkillBookRet* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const OPSnatchSkillBookRet*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void OPSnatchSkillBookRet::MergeFrom(const OPSnatchSkillBookRet& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_servertime()) {
      set_servertime(from.servertime());
    }
    if (from.has_status()) {
      set_status(from.status());
    }
    if (from.has_ret()) {
      set_ret(from.ret());
    }
    if (from.has_battle()) {
      mutable_battle()->::OPUserBattleRet::MergeFrom(from.battle());
    }
    if (from.has_vitality()) {
      set_vitality(from.vitality());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void OPSnatchSkillBookRet::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void OPSnatchSkillBookRet::CopyFrom(const OPSnatchSkillBookRet& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool OPSnatchSkillBookRet::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000017) != 0x00000017) return false;

  if (has_battle()) {
    if (!this->battle().IsInitialized()) return false;
  }
  return true;
}

void OPSnatchSkillBookRet::Swap(OPSnatchSkillBookRet* other) {
  if (other != this) {
    std::swap(servertime_, other->servertime_);
    std::swap(status_, other->status_);
    std::swap(ret_, other->ret_);
    std::swap(battle_, other->battle_);
    std::swap(vitality_, other->vitality_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata OPSnatchSkillBookRet::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = OPSnatchSkillBookRet_descriptor_;
  metadata.reflection = OPSnatchSkillBookRet_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
