// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UpgradeDisciple.proto

#ifndef PROTOBUF_UpgradeDisciple_2eproto__INCLUDED
#define PROTOBUF_UpgradeDisciple_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_UpgradeDisciple_2eproto();
void protobuf_AssignDesc_UpgradeDisciple_2eproto();
void protobuf_ShutdownFile_UpgradeDisciple_2eproto();

class OPUpgradeDisciple;
class OPUpgradeDiscipleRet;

// ===================================================================

class OPUpgradeDisciple : public ::google::protobuf::Message {
 public:
  OPUpgradeDisciple();
  virtual ~OPUpgradeDisciple();

  OPUpgradeDisciple(const OPUpgradeDisciple& from);

  inline OPUpgradeDisciple& operator=(const OPUpgradeDisciple& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const OPUpgradeDisciple& default_instance();

  void Swap(OPUpgradeDisciple* other);

  // implements Message ----------------------------------------------

  OPUpgradeDisciple* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const OPUpgradeDisciple& from);
  void MergeFrom(const OPUpgradeDisciple& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:OPUpgradeDisciple)
 private:
  inline void set_has_id();
  inline void clear_has_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_UpgradeDisciple_2eproto();
  friend void protobuf_AssignDesc_UpgradeDisciple_2eproto();
  friend void protobuf_ShutdownFile_UpgradeDisciple_2eproto();

  void InitAsDefaultInstance();
  static OPUpgradeDisciple* default_instance_;
};
// -------------------------------------------------------------------

class OPUpgradeDiscipleRet : public ::google::protobuf::Message {
 public:
  OPUpgradeDiscipleRet();
  virtual ~OPUpgradeDiscipleRet();

  OPUpgradeDiscipleRet(const OPUpgradeDiscipleRet& from);

  inline OPUpgradeDiscipleRet& operator=(const OPUpgradeDiscipleRet& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const OPUpgradeDiscipleRet& default_instance();

  void Swap(OPUpgradeDiscipleRet* other);

  // implements Message ----------------------------------------------

  OPUpgradeDiscipleRet* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const OPUpgradeDiscipleRet& from);
  void MergeFrom(const OPUpgradeDiscipleRet& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);

  // required int32 servertime = 2;
  inline bool has_servertime() const;
  inline void clear_servertime();
  static const int kServertimeFieldNumber = 2;
  inline ::google::protobuf::int32 servertime() const;
  inline void set_servertime(::google::protobuf::int32 value);

  // required int32 upgradelevel = 3;
  inline bool has_upgradelevel() const;
  inline void clear_upgradelevel();
  static const int kUpgradelevelFieldNumber = 3;
  inline ::google::protobuf::int32 upgradelevel() const;
  inline void set_upgradelevel(::google::protobuf::int32 value);

  // required int32 potentiality = 4;
  inline bool has_potentiality() const;
  inline void clear_potentiality();
  static const int kPotentialityFieldNumber = 4;
  inline ::google::protobuf::int32 potentiality() const;
  inline void set_potentiality(::google::protobuf::int32 value);

  // required int32 soulcount = 5;
  inline bool has_soulcount() const;
  inline void clear_soulcount();
  static const int kSoulcountFieldNumber = 5;
  inline ::google::protobuf::int32 soulcount() const;
  inline void set_soulcount(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:OPUpgradeDiscipleRet)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_servertime();
  inline void clear_has_servertime();
  inline void set_has_upgradelevel();
  inline void clear_has_upgradelevel();
  inline void set_has_potentiality();
  inline void clear_has_potentiality();
  inline void set_has_soulcount();
  inline void clear_has_soulcount();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 id_;
  ::google::protobuf::int32 servertime_;
  ::google::protobuf::int32 upgradelevel_;
  ::google::protobuf::int32 potentiality_;
  ::google::protobuf::int32 soulcount_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];

  friend void  protobuf_AddDesc_UpgradeDisciple_2eproto();
  friend void protobuf_AssignDesc_UpgradeDisciple_2eproto();
  friend void protobuf_ShutdownFile_UpgradeDisciple_2eproto();

  void InitAsDefaultInstance();
  static OPUpgradeDiscipleRet* default_instance_;
};
// ===================================================================


// ===================================================================

// OPUpgradeDisciple

// required int32 id = 1;
inline bool OPUpgradeDisciple::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void OPUpgradeDisciple::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void OPUpgradeDisciple::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void OPUpgradeDisciple::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 OPUpgradeDisciple::id() const {
  return id_;
}
inline void OPUpgradeDisciple::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
}

// -------------------------------------------------------------------

// OPUpgradeDiscipleRet

// required int32 id = 1;
inline bool OPUpgradeDiscipleRet::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void OPUpgradeDiscipleRet::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void OPUpgradeDiscipleRet::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void OPUpgradeDiscipleRet::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 OPUpgradeDiscipleRet::id() const {
  return id_;
}
inline void OPUpgradeDiscipleRet::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
}

// required int32 servertime = 2;
inline bool OPUpgradeDiscipleRet::has_servertime() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void OPUpgradeDiscipleRet::set_has_servertime() {
  _has_bits_[0] |= 0x00000002u;
}
inline void OPUpgradeDiscipleRet::clear_has_servertime() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void OPUpgradeDiscipleRet::clear_servertime() {
  servertime_ = 0;
  clear_has_servertime();
}
inline ::google::protobuf::int32 OPUpgradeDiscipleRet::servertime() const {
  return servertime_;
}
inline void OPUpgradeDiscipleRet::set_servertime(::google::protobuf::int32 value) {
  set_has_servertime();
  servertime_ = value;
}

// required int32 upgradelevel = 3;
inline bool OPUpgradeDiscipleRet::has_upgradelevel() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void OPUpgradeDiscipleRet::set_has_upgradelevel() {
  _has_bits_[0] |= 0x00000004u;
}
inline void OPUpgradeDiscipleRet::clear_has_upgradelevel() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void OPUpgradeDiscipleRet::clear_upgradelevel() {
  upgradelevel_ = 0;
  clear_has_upgradelevel();
}
inline ::google::protobuf::int32 OPUpgradeDiscipleRet::upgradelevel() const {
  return upgradelevel_;
}
inline void OPUpgradeDiscipleRet::set_upgradelevel(::google::protobuf::int32 value) {
  set_has_upgradelevel();
  upgradelevel_ = value;
}

// required int32 potentiality = 4;
inline bool OPUpgradeDiscipleRet::has_potentiality() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void OPUpgradeDiscipleRet::set_has_potentiality() {
  _has_bits_[0] |= 0x00000008u;
}
inline void OPUpgradeDiscipleRet::clear_has_potentiality() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void OPUpgradeDiscipleRet::clear_potentiality() {
  potentiality_ = 0;
  clear_has_potentiality();
}
inline ::google::protobuf::int32 OPUpgradeDiscipleRet::potentiality() const {
  return potentiality_;
}
inline void OPUpgradeDiscipleRet::set_potentiality(::google::protobuf::int32 value) {
  set_has_potentiality();
  potentiality_ = value;
}

// required int32 soulcount = 5;
inline bool OPUpgradeDiscipleRet::has_soulcount() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void OPUpgradeDiscipleRet::set_has_soulcount() {
  _has_bits_[0] |= 0x00000010u;
}
inline void OPUpgradeDiscipleRet::clear_has_soulcount() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void OPUpgradeDiscipleRet::clear_soulcount() {
  soulcount_ = 0;
  clear_has_soulcount();
}
inline ::google::protobuf::int32 OPUpgradeDiscipleRet::soulcount() const {
  return soulcount_;
}
inline void OPUpgradeDiscipleRet::set_soulcount(::google::protobuf::int32 value) {
  set_has_soulcount();
  soulcount_ = value;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_UpgradeDisciple_2eproto__INCLUDED
