// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserCareerInfo.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "UserCareerInfo.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* OPUserCareerInfo_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  OPUserCareerInfo_reflection_ = NULL;
const ::google::protobuf::Descriptor* OPUserCareerInfoRet_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  OPUserCareerInfoRet_reflection_ = NULL;
const ::google::protobuf::Descriptor* OPUserCareerInfoRet_Status_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  OPUserCareerInfoRet_Status_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_UserCareerInfo_2eproto() {
  protobuf_AddDesc_UserCareerInfo_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "UserCareerInfo.proto");
  GOOGLE_CHECK(file != NULL);
  OPUserCareerInfo_descriptor_ = file->message_type(0);
  static const int OPUserCareerInfo_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OPUserCareerInfo, version_),
  };
  OPUserCareerInfo_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      OPUserCareerInfo_descriptor_,
      OPUserCareerInfo::default_instance_,
      OPUserCareerInfo_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OPUserCareerInfo, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OPUserCareerInfo, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(OPUserCareerInfo));
  OPUserCareerInfoRet_descriptor_ = file->message_type(1);
  static const int OPUserCareerInfoRet_offsets_[8] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OPUserCareerInfoRet, playerid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OPUserCareerInfoRet, currentchapter_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OPUserCareerInfoRet, currentpoint_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OPUserCareerInfoRet, checktime_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OPUserCareerInfoRet, chapteraddpower_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OPUserCareerInfoRet, pointevaluate_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OPUserCareerInfoRet, pointcount_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OPUserCareerInfoRet, backwardstime_),
  };
  OPUserCareerInfoRet_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      OPUserCareerInfoRet_descriptor_,
      OPUserCareerInfoRet::default_instance_,
      OPUserCareerInfoRet_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OPUserCareerInfoRet, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OPUserCareerInfoRet, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(OPUserCareerInfoRet));
  OPUserCareerInfoRet_Status_descriptor_ = OPUserCareerInfoRet_descriptor_->nested_type(0);
  static const int OPUserCareerInfoRet_Status_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OPUserCareerInfoRet_Status, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OPUserCareerInfoRet_Status, value_),
  };
  OPUserCareerInfoRet_Status_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      OPUserCareerInfoRet_Status_descriptor_,
      OPUserCareerInfoRet_Status::default_instance_,
      OPUserCareerInfoRet_Status_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OPUserCareerInfoRet_Status, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OPUserCareerInfoRet_Status, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(OPUserCareerInfoRet_Status));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_UserCareerInfo_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    OPUserCareerInfo_descriptor_, &OPUserCareerInfo::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    OPUserCareerInfoRet_descriptor_, &OPUserCareerInfoRet::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    OPUserCareerInfoRet_Status_descriptor_, &OPUserCareerInfoRet_Status::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_UserCareerInfo_2eproto() {
  delete OPUserCareerInfo::default_instance_;
  delete OPUserCareerInfo_reflection_;
  delete OPUserCareerInfoRet::default_instance_;
  delete OPUserCareerInfoRet_reflection_;
  delete OPUserCareerInfoRet_Status::default_instance_;
  delete OPUserCareerInfoRet_Status_reflection_;
}

void protobuf_AddDesc_UserCareerInfo_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\024UserCareerInfo.proto\"&\n\020OPUserCareerIn"
    "fo\022\022\n\007version\030\001 \002(\005:\0011\"\277\002\n\023OPUserCareerI"
    "nfoRet\022\020\n\010playerid\030\001 \002(\005\022\026\n\016currentchapt"
    "er\030\002 \002(\005\022\024\n\014currentpoint\030\003 \002(\005\022\021\n\tcheckt"
    "ime\030\004 \002(\005\0224\n\017chapteraddpower\030\005 \003(\0132\033.OPU"
    "serCareerInfoRet.Status\0222\n\rpointevaluate"
    "\030\006 \003(\0132\033.OPUserCareerInfoRet.Status\022/\n\np"
    "ointcount\030\007 \003(\0132\033.OPUserCareerInfoRet.St"
    "atus\022\025\n\rbackwardsTime\030\010 \001(\005\032#\n\006Status\022\n\n"
    "\002id\030\001 \002(\005\022\r\n\005value\030\002 \002(\005B\035\n\033com.oldmount"
    "ain.dzm.message", 415);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "UserCareerInfo.proto", &protobuf_RegisterTypes);
  OPUserCareerInfo::default_instance_ = new OPUserCareerInfo();
  OPUserCareerInfoRet::default_instance_ = new OPUserCareerInfoRet();
  OPUserCareerInfoRet_Status::default_instance_ = new OPUserCareerInfoRet_Status();
  OPUserCareerInfo::default_instance_->InitAsDefaultInstance();
  OPUserCareerInfoRet::default_instance_->InitAsDefaultInstance();
  OPUserCareerInfoRet_Status::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_UserCareerInfo_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_UserCareerInfo_2eproto {
  StaticDescriptorInitializer_UserCareerInfo_2eproto() {
    protobuf_AddDesc_UserCareerInfo_2eproto();
  }
} static_descriptor_initializer_UserCareerInfo_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int OPUserCareerInfo::kVersionFieldNumber;
#endif  // !_MSC_VER

OPUserCareerInfo::OPUserCareerInfo()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void OPUserCareerInfo::InitAsDefaultInstance() {
}

OPUserCareerInfo::OPUserCareerInfo(const OPUserCareerInfo& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void OPUserCareerInfo::SharedCtor() {
  _cached_size_ = 0;
  version_ = 1;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

OPUserCareerInfo::~OPUserCareerInfo() {
  SharedDtor();
}

void OPUserCareerInfo::SharedDtor() {
  if (this != default_instance_) {
  }
}

void OPUserCareerInfo::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* OPUserCareerInfo::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return OPUserCareerInfo_descriptor_;
}

const OPUserCareerInfo& OPUserCareerInfo::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_UserCareerInfo_2eproto();
  return *default_instance_;
}

OPUserCareerInfo* OPUserCareerInfo::default_instance_ = NULL;

OPUserCareerInfo* OPUserCareerInfo::New() const {
  return new OPUserCareerInfo;
}

void OPUserCareerInfo::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    version_ = 1;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool OPUserCareerInfo::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 version = 1 [default = 1];
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &version_)));
          set_has_version();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void OPUserCareerInfo::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required int32 version = 1 [default = 1];
  if (has_version()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->version(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* OPUserCareerInfo::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required int32 version = 1 [default = 1];
  if (has_version()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->version(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int OPUserCareerInfo::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 version = 1 [default = 1];
    if (has_version()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->version());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void OPUserCareerInfo::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const OPUserCareerInfo* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const OPUserCareerInfo*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void OPUserCareerInfo::MergeFrom(const OPUserCareerInfo& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_version()) {
      set_version(from.version());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void OPUserCareerInfo::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void OPUserCareerInfo::CopyFrom(const OPUserCareerInfo& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool OPUserCareerInfo::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void OPUserCareerInfo::Swap(OPUserCareerInfo* other) {
  if (other != this) {
    std::swap(version_, other->version_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata OPUserCareerInfo::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = OPUserCareerInfo_descriptor_;
  metadata.reflection = OPUserCareerInfo_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int OPUserCareerInfoRet_Status::kIdFieldNumber;
const int OPUserCareerInfoRet_Status::kValueFieldNumber;
#endif  // !_MSC_VER

OPUserCareerInfoRet_Status::OPUserCareerInfoRet_Status()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void OPUserCareerInfoRet_Status::InitAsDefaultInstance() {
}

OPUserCareerInfoRet_Status::OPUserCareerInfoRet_Status(const OPUserCareerInfoRet_Status& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void OPUserCareerInfoRet_Status::SharedCtor() {
  _cached_size_ = 0;
  id_ = 0;
  value_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

OPUserCareerInfoRet_Status::~OPUserCareerInfoRet_Status() {
  SharedDtor();
}

void OPUserCareerInfoRet_Status::SharedDtor() {
  if (this != default_instance_) {
  }
}

void OPUserCareerInfoRet_Status::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* OPUserCareerInfoRet_Status::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return OPUserCareerInfoRet_Status_descriptor_;
}

const OPUserCareerInfoRet_Status& OPUserCareerInfoRet_Status::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_UserCareerInfo_2eproto();
  return *default_instance_;
}

OPUserCareerInfoRet_Status* OPUserCareerInfoRet_Status::default_instance_ = NULL;

OPUserCareerInfoRet_Status* OPUserCareerInfoRet_Status::New() const {
  return new OPUserCareerInfoRet_Status;
}

void OPUserCareerInfoRet_Status::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    id_ = 0;
    value_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool OPUserCareerInfoRet_Status::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 id = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &id_)));
          set_has_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_value;
        break;
      }

      // required int32 value = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_value:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &value_)));
          set_has_value();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void OPUserCareerInfoRet_Status::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required int32 id = 1;
  if (has_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->id(), output);
  }

  // required int32 value = 2;
  if (has_value()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->value(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* OPUserCareerInfoRet_Status::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required int32 id = 1;
  if (has_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->id(), target);
  }

  // required int32 value = 2;
  if (has_value()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->value(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int OPUserCareerInfoRet_Status::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 id = 1;
    if (has_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->id());
    }

    // required int32 value = 2;
    if (has_value()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->value());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void OPUserCareerInfoRet_Status::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const OPUserCareerInfoRet_Status* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const OPUserCareerInfoRet_Status*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void OPUserCareerInfoRet_Status::MergeFrom(const OPUserCareerInfoRet_Status& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_id()) {
      set_id(from.id());
    }
    if (from.has_value()) {
      set_value(from.value());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void OPUserCareerInfoRet_Status::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void OPUserCareerInfoRet_Status::CopyFrom(const OPUserCareerInfoRet_Status& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool OPUserCareerInfoRet_Status::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void OPUserCareerInfoRet_Status::Swap(OPUserCareerInfoRet_Status* other) {
  if (other != this) {
    std::swap(id_, other->id_);
    std::swap(value_, other->value_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata OPUserCareerInfoRet_Status::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = OPUserCareerInfoRet_Status_descriptor_;
  metadata.reflection = OPUserCareerInfoRet_Status_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int OPUserCareerInfoRet::kPlayeridFieldNumber;
const int OPUserCareerInfoRet::kCurrentchapterFieldNumber;
const int OPUserCareerInfoRet::kCurrentpointFieldNumber;
const int OPUserCareerInfoRet::kChecktimeFieldNumber;
const int OPUserCareerInfoRet::kChapteraddpowerFieldNumber;
const int OPUserCareerInfoRet::kPointevaluateFieldNumber;
const int OPUserCareerInfoRet::kPointcountFieldNumber;
const int OPUserCareerInfoRet::kBackwardsTimeFieldNumber;
#endif  // !_MSC_VER

OPUserCareerInfoRet::OPUserCareerInfoRet()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void OPUserCareerInfoRet::InitAsDefaultInstance() {
}

OPUserCareerInfoRet::OPUserCareerInfoRet(const OPUserCareerInfoRet& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void OPUserCareerInfoRet::SharedCtor() {
  _cached_size_ = 0;
  playerid_ = 0;
  currentchapter_ = 0;
  currentpoint_ = 0;
  checktime_ = 0;
  backwardstime_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

OPUserCareerInfoRet::~OPUserCareerInfoRet() {
  SharedDtor();
}

void OPUserCareerInfoRet::SharedDtor() {
  if (this != default_instance_) {
  }
}

void OPUserCareerInfoRet::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* OPUserCareerInfoRet::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return OPUserCareerInfoRet_descriptor_;
}

const OPUserCareerInfoRet& OPUserCareerInfoRet::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_UserCareerInfo_2eproto();
  return *default_instance_;
}

OPUserCareerInfoRet* OPUserCareerInfoRet::default_instance_ = NULL;

OPUserCareerInfoRet* OPUserCareerInfoRet::New() const {
  return new OPUserCareerInfoRet;
}

void OPUserCareerInfoRet::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    playerid_ = 0;
    currentchapter_ = 0;
    currentpoint_ = 0;
    checktime_ = 0;
    backwardstime_ = 0;
  }
  chapteraddpower_.Clear();
  pointevaluate_.Clear();
  pointcount_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool OPUserCareerInfoRet::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 playerid = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &playerid_)));
          set_has_playerid();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_currentchapter;
        break;
      }

      // required int32 currentchapter = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_currentchapter:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &currentchapter_)));
          set_has_currentchapter();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_currentpoint;
        break;
      }

      // required int32 currentpoint = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_currentpoint:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &currentpoint_)));
          set_has_currentpoint();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(32)) goto parse_checktime;
        break;
      }

      // required int32 checktime = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_checktime:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &checktime_)));
          set_has_checktime();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(42)) goto parse_chapteraddpower;
        break;
      }

      // repeated .OPUserCareerInfoRet.Status chapteraddpower = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_chapteraddpower:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_chapteraddpower()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(42)) goto parse_chapteraddpower;
        if (input->ExpectTag(50)) goto parse_pointevaluate;
        break;
      }

      // repeated .OPUserCareerInfoRet.Status pointevaluate = 6;
      case 6: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_pointevaluate:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_pointevaluate()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(50)) goto parse_pointevaluate;
        if (input->ExpectTag(58)) goto parse_pointcount;
        break;
      }

      // repeated .OPUserCareerInfoRet.Status pointcount = 7;
      case 7: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_pointcount:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_pointcount()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(58)) goto parse_pointcount;
        if (input->ExpectTag(64)) goto parse_backwardsTime;
        break;
      }

      // optional int32 backwardsTime = 8;
      case 8: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_backwardsTime:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &backwardstime_)));
          set_has_backwardstime();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void OPUserCareerInfoRet::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required int32 playerid = 1;
  if (has_playerid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->playerid(), output);
  }

  // required int32 currentchapter = 2;
  if (has_currentchapter()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->currentchapter(), output);
  }

  // required int32 currentpoint = 3;
  if (has_currentpoint()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->currentpoint(), output);
  }

  // required int32 checktime = 4;
  if (has_checktime()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->checktime(), output);
  }

  // repeated .OPUserCareerInfoRet.Status chapteraddpower = 5;
  for (int i = 0; i < this->chapteraddpower_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      5, this->chapteraddpower(i), output);
  }

  // repeated .OPUserCareerInfoRet.Status pointevaluate = 6;
  for (int i = 0; i < this->pointevaluate_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      6, this->pointevaluate(i), output);
  }

  // repeated .OPUserCareerInfoRet.Status pointcount = 7;
  for (int i = 0; i < this->pointcount_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      7, this->pointcount(i), output);
  }

  // optional int32 backwardsTime = 8;
  if (has_backwardstime()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(8, this->backwardstime(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* OPUserCareerInfoRet::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required int32 playerid = 1;
  if (has_playerid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->playerid(), target);
  }

  // required int32 currentchapter = 2;
  if (has_currentchapter()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->currentchapter(), target);
  }

  // required int32 currentpoint = 3;
  if (has_currentpoint()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->currentpoint(), target);
  }

  // required int32 checktime = 4;
  if (has_checktime()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->checktime(), target);
  }

  // repeated .OPUserCareerInfoRet.Status chapteraddpower = 5;
  for (int i = 0; i < this->chapteraddpower_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        5, this->chapteraddpower(i), target);
  }

  // repeated .OPUserCareerInfoRet.Status pointevaluate = 6;
  for (int i = 0; i < this->pointevaluate_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        6, this->pointevaluate(i), target);
  }

  // repeated .OPUserCareerInfoRet.Status pointcount = 7;
  for (int i = 0; i < this->pointcount_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        7, this->pointcount(i), target);
  }

  // optional int32 backwardsTime = 8;
  if (has_backwardstime()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(8, this->backwardstime(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int OPUserCareerInfoRet::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 playerid = 1;
    if (has_playerid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->playerid());
    }

    // required int32 currentchapter = 2;
    if (has_currentchapter()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->currentchapter());
    }

    // required int32 currentpoint = 3;
    if (has_currentpoint()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->currentpoint());
    }

    // required int32 checktime = 4;
    if (has_checktime()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->checktime());
    }

    // optional int32 backwardsTime = 8;
    if (has_backwardstime()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->backwardstime());
    }

  }
  // repeated .OPUserCareerInfoRet.Status chapteraddpower = 5;
  total_size += 1 * this->chapteraddpower_size();
  for (int i = 0; i < this->chapteraddpower_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->chapteraddpower(i));
  }

  // repeated .OPUserCareerInfoRet.Status pointevaluate = 6;
  total_size += 1 * this->pointevaluate_size();
  for (int i = 0; i < this->pointevaluate_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->pointevaluate(i));
  }

  // repeated .OPUserCareerInfoRet.Status pointcount = 7;
  total_size += 1 * this->pointcount_size();
  for (int i = 0; i < this->pointcount_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->pointcount(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void OPUserCareerInfoRet::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const OPUserCareerInfoRet* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const OPUserCareerInfoRet*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void OPUserCareerInfoRet::MergeFrom(const OPUserCareerInfoRet& from) {
  GOOGLE_CHECK_NE(&from, this);
  chapteraddpower_.MergeFrom(from.chapteraddpower_);
  pointevaluate_.MergeFrom(from.pointevaluate_);
  pointcount_.MergeFrom(from.pointcount_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_playerid()) {
      set_playerid(from.playerid());
    }
    if (from.has_currentchapter()) {
      set_currentchapter(from.currentchapter());
    }
    if (from.has_currentpoint()) {
      set_currentpoint(from.currentpoint());
    }
    if (from.has_checktime()) {
      set_checktime(from.checktime());
    }
    if (from.has_backwardstime()) {
      set_backwardstime(from.backwardstime());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void OPUserCareerInfoRet::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void OPUserCareerInfoRet::CopyFrom(const OPUserCareerInfoRet& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool OPUserCareerInfoRet::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000000f) != 0x0000000f) return false;

  for (int i = 0; i < chapteraddpower_size(); i++) {
    if (!this->chapteraddpower(i).IsInitialized()) return false;
  }
  for (int i = 0; i < pointevaluate_size(); i++) {
    if (!this->pointevaluate(i).IsInitialized()) return false;
  }
  for (int i = 0; i < pointcount_size(); i++) {
    if (!this->pointcount(i).IsInitialized()) return false;
  }
  return true;
}

void OPUserCareerInfoRet::Swap(OPUserCareerInfoRet* other) {
  if (other != this) {
    std::swap(playerid_, other->playerid_);
    std::swap(currentchapter_, other->currentchapter_);
    std::swap(currentpoint_, other->currentpoint_);
    std::swap(checktime_, other->checktime_);
    chapteraddpower_.Swap(&other->chapteraddpower_);
    pointevaluate_.Swap(&other->pointevaluate_);
    pointcount_.Swap(&other->pointcount_);
    std::swap(backwardstime_, other->backwardstime_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata OPUserCareerInfoRet::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = OPUserCareerInfoRet_descriptor_;
  metadata.reflection = OPUserCareerInfoRet_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
