// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserArenaInfo.proto

#ifndef PROTOBUF_UserArenaInfo_2eproto__INCLUDED
#define PROTOBUF_UserArenaInfo_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_UserArenaInfo_2eproto();
void protobuf_AssignDesc_UserArenaInfo_2eproto();
void protobuf_ShutdownFile_UserArenaInfo_2eproto();

class OPUserArenaInfo;
class OPUserArenaInfoRet;

// ===================================================================

class OPUserArenaInfo : public ::google::protobuf::Message {
 public:
  OPUserArenaInfo();
  virtual ~OPUserArenaInfo();

  OPUserArenaInfo(const OPUserArenaInfo& from);

  inline OPUserArenaInfo& operator=(const OPUserArenaInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const OPUserArenaInfo& default_instance();

  void Swap(OPUserArenaInfo* other);

  // implements Message ----------------------------------------------

  OPUserArenaInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const OPUserArenaInfo& from);
  void MergeFrom(const OPUserArenaInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 version = 1 [default = 1];
  inline bool has_version() const;
  inline void clear_version();
  static const int kVersionFieldNumber = 1;
  inline ::google::protobuf::int32 version() const;
  inline void set_version(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:OPUserArenaInfo)
 private:
  inline void set_has_version();
  inline void clear_has_version();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 version_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_UserArenaInfo_2eproto();
  friend void protobuf_AssignDesc_UserArenaInfo_2eproto();
  friend void protobuf_ShutdownFile_UserArenaInfo_2eproto();

  void InitAsDefaultInstance();
  static OPUserArenaInfo* default_instance_;
};
// -------------------------------------------------------------------

class OPUserArenaInfoRet : public ::google::protobuf::Message {
 public:
  OPUserArenaInfoRet();
  virtual ~OPUserArenaInfoRet();

  OPUserArenaInfoRet(const OPUserArenaInfoRet& from);

  inline OPUserArenaInfoRet& operator=(const OPUserArenaInfoRet& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const OPUserArenaInfoRet& default_instance();

  void Swap(OPUserArenaInfoRet* other);

  // implements Message ----------------------------------------------

  OPUserArenaInfoRet* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const OPUserArenaInfoRet& from);
  void MergeFrom(const OPUserArenaInfoRet& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 arenaRank = 1;
  inline bool has_arenarank() const;
  inline void clear_arenarank();
  static const int kArenaRankFieldNumber = 1;
  inline ::google::protobuf::int32 arenarank() const;
  inline void set_arenarank(::google::protobuf::int32 value);

  // required int32 arenaScore = 2;
  inline bool has_arenascore() const;
  inline void clear_arenascore();
  static const int kArenaScoreFieldNumber = 2;
  inline ::google::protobuf::int32 arenascore() const;
  inline void set_arenascore(::google::protobuf::int32 value);

  // required int32 arenaNum = 3;
  inline bool has_arenanum() const;
  inline void clear_arenanum();
  static const int kArenaNumFieldNumber = 3;
  inline ::google::protobuf::int32 arenanum() const;
  inline void set_arenanum(::google::protobuf::int32 value);

  // required int32 rewardScore = 4;
  inline bool has_rewardscore() const;
  inline void clear_rewardscore();
  static const int kRewardScoreFieldNumber = 4;
  inline ::google::protobuf::int32 rewardscore() const;
  inline void set_rewardscore(::google::protobuf::int32 value);

  // required int32 rewardRefreshTime = 5;
  inline bool has_rewardrefreshtime() const;
  inline void clear_rewardrefreshtime();
  static const int kRewardRefreshTimeFieldNumber = 5;
  inline ::google::protobuf::int32 rewardrefreshtime() const;
  inline void set_rewardrefreshtime(::google::protobuf::int32 value);

  // repeated int32 rewardIDs = 6;
  inline int rewardids_size() const;
  inline void clear_rewardids();
  static const int kRewardIDsFieldNumber = 6;
  inline ::google::protobuf::int32 rewardids(int index) const;
  inline void set_rewardids(int index, ::google::protobuf::int32 value);
  inline void add_rewardids(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      rewardids() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_rewardids();

  // required int32 servertime = 7;
  inline bool has_servertime() const;
  inline void clear_servertime();
  static const int kServertimeFieldNumber = 7;
  inline ::google::protobuf::int32 servertime() const;
  inline void set_servertime(::google::protobuf::int32 value);

  // repeated int32 gotRewardIDs = 8;
  inline int gotrewardids_size() const;
  inline void clear_gotrewardids();
  static const int kGotRewardIDsFieldNumber = 8;
  inline ::google::protobuf::int32 gotrewardids(int index) const;
  inline void set_gotrewardids(int index, ::google::protobuf::int32 value);
  inline void add_gotrewardids(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      gotrewardids() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_gotrewardids();

  // @@protoc_insertion_point(class_scope:OPUserArenaInfoRet)
 private:
  inline void set_has_arenarank();
  inline void clear_has_arenarank();
  inline void set_has_arenascore();
  inline void clear_has_arenascore();
  inline void set_has_arenanum();
  inline void clear_has_arenanum();
  inline void set_has_rewardscore();
  inline void clear_has_rewardscore();
  inline void set_has_rewardrefreshtime();
  inline void clear_has_rewardrefreshtime();
  inline void set_has_servertime();
  inline void clear_has_servertime();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 arenarank_;
  ::google::protobuf::int32 arenascore_;
  ::google::protobuf::int32 arenanum_;
  ::google::protobuf::int32 rewardscore_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > rewardids_;
  ::google::protobuf::int32 rewardrefreshtime_;
  ::google::protobuf::int32 servertime_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > gotrewardids_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(8 + 31) / 32];

  friend void  protobuf_AddDesc_UserArenaInfo_2eproto();
  friend void protobuf_AssignDesc_UserArenaInfo_2eproto();
  friend void protobuf_ShutdownFile_UserArenaInfo_2eproto();

  void InitAsDefaultInstance();
  static OPUserArenaInfoRet* default_instance_;
};
// ===================================================================


// ===================================================================

// OPUserArenaInfo

// required int32 version = 1 [default = 1];
inline bool OPUserArenaInfo::has_version() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void OPUserArenaInfo::set_has_version() {
  _has_bits_[0] |= 0x00000001u;
}
inline void OPUserArenaInfo::clear_has_version() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void OPUserArenaInfo::clear_version() {
  version_ = 1;
  clear_has_version();
}
inline ::google::protobuf::int32 OPUserArenaInfo::version() const {
  return version_;
}
inline void OPUserArenaInfo::set_version(::google::protobuf::int32 value) {
  set_has_version();
  version_ = value;
}

// -------------------------------------------------------------------

// OPUserArenaInfoRet

// required int32 arenaRank = 1;
inline bool OPUserArenaInfoRet::has_arenarank() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void OPUserArenaInfoRet::set_has_arenarank() {
  _has_bits_[0] |= 0x00000001u;
}
inline void OPUserArenaInfoRet::clear_has_arenarank() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void OPUserArenaInfoRet::clear_arenarank() {
  arenarank_ = 0;
  clear_has_arenarank();
}
inline ::google::protobuf::int32 OPUserArenaInfoRet::arenarank() const {
  return arenarank_;
}
inline void OPUserArenaInfoRet::set_arenarank(::google::protobuf::int32 value) {
  set_has_arenarank();
  arenarank_ = value;
}

// required int32 arenaScore = 2;
inline bool OPUserArenaInfoRet::has_arenascore() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void OPUserArenaInfoRet::set_has_arenascore() {
  _has_bits_[0] |= 0x00000002u;
}
inline void OPUserArenaInfoRet::clear_has_arenascore() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void OPUserArenaInfoRet::clear_arenascore() {
  arenascore_ = 0;
  clear_has_arenascore();
}
inline ::google::protobuf::int32 OPUserArenaInfoRet::arenascore() const {
  return arenascore_;
}
inline void OPUserArenaInfoRet::set_arenascore(::google::protobuf::int32 value) {
  set_has_arenascore();
  arenascore_ = value;
}

// required int32 arenaNum = 3;
inline bool OPUserArenaInfoRet::has_arenanum() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void OPUserArenaInfoRet::set_has_arenanum() {
  _has_bits_[0] |= 0x00000004u;
}
inline void OPUserArenaInfoRet::clear_has_arenanum() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void OPUserArenaInfoRet::clear_arenanum() {
  arenanum_ = 0;
  clear_has_arenanum();
}
inline ::google::protobuf::int32 OPUserArenaInfoRet::arenanum() const {
  return arenanum_;
}
inline void OPUserArenaInfoRet::set_arenanum(::google::protobuf::int32 value) {
  set_has_arenanum();
  arenanum_ = value;
}

// required int32 rewardScore = 4;
inline bool OPUserArenaInfoRet::has_rewardscore() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void OPUserArenaInfoRet::set_has_rewardscore() {
  _has_bits_[0] |= 0x00000008u;
}
inline void OPUserArenaInfoRet::clear_has_rewardscore() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void OPUserArenaInfoRet::clear_rewardscore() {
  rewardscore_ = 0;
  clear_has_rewardscore();
}
inline ::google::protobuf::int32 OPUserArenaInfoRet::rewardscore() const {
  return rewardscore_;
}
inline void OPUserArenaInfoRet::set_rewardscore(::google::protobuf::int32 value) {
  set_has_rewardscore();
  rewardscore_ = value;
}

// required int32 rewardRefreshTime = 5;
inline bool OPUserArenaInfoRet::has_rewardrefreshtime() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void OPUserArenaInfoRet::set_has_rewardrefreshtime() {
  _has_bits_[0] |= 0x00000010u;
}
inline void OPUserArenaInfoRet::clear_has_rewardrefreshtime() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void OPUserArenaInfoRet::clear_rewardrefreshtime() {
  rewardrefreshtime_ = 0;
  clear_has_rewardrefreshtime();
}
inline ::google::protobuf::int32 OPUserArenaInfoRet::rewardrefreshtime() const {
  return rewardrefreshtime_;
}
inline void OPUserArenaInfoRet::set_rewardrefreshtime(::google::protobuf::int32 value) {
  set_has_rewardrefreshtime();
  rewardrefreshtime_ = value;
}

// repeated int32 rewardIDs = 6;
inline int OPUserArenaInfoRet::rewardids_size() const {
  return rewardids_.size();
}
inline void OPUserArenaInfoRet::clear_rewardids() {
  rewardids_.Clear();
}
inline ::google::protobuf::int32 OPUserArenaInfoRet::rewardids(int index) const {
  return rewardids_.Get(index);
}
inline void OPUserArenaInfoRet::set_rewardids(int index, ::google::protobuf::int32 value) {
  rewardids_.Set(index, value);
}
inline void OPUserArenaInfoRet::add_rewardids(::google::protobuf::int32 value) {
  rewardids_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
OPUserArenaInfoRet::rewardids() const {
  return rewardids_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
OPUserArenaInfoRet::mutable_rewardids() {
  return &rewardids_;
}

// required int32 servertime = 7;
inline bool OPUserArenaInfoRet::has_servertime() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void OPUserArenaInfoRet::set_has_servertime() {
  _has_bits_[0] |= 0x00000040u;
}
inline void OPUserArenaInfoRet::clear_has_servertime() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void OPUserArenaInfoRet::clear_servertime() {
  servertime_ = 0;
  clear_has_servertime();
}
inline ::google::protobuf::int32 OPUserArenaInfoRet::servertime() const {
  return servertime_;
}
inline void OPUserArenaInfoRet::set_servertime(::google::protobuf::int32 value) {
  set_has_servertime();
  servertime_ = value;
}

// repeated int32 gotRewardIDs = 8;
inline int OPUserArenaInfoRet::gotrewardids_size() const {
  return gotrewardids_.size();
}
inline void OPUserArenaInfoRet::clear_gotrewardids() {
  gotrewardids_.Clear();
}
inline ::google::protobuf::int32 OPUserArenaInfoRet::gotrewardids(int index) const {
  return gotrewardids_.Get(index);
}
inline void OPUserArenaInfoRet::set_gotrewardids(int index, ::google::protobuf::int32 value) {
  gotrewardids_.Set(index, value);
}
inline void OPUserArenaInfoRet::add_gotrewardids(::google::protobuf::int32 value) {
  gotrewardids_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
OPUserArenaInfoRet::gotrewardids() const {
  return gotrewardids_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
OPUserArenaInfoRet::mutable_gotrewardids() {
  return &gotrewardids_;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_UserArenaInfo_2eproto__INCLUDED
