// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserDiscipleInfo.proto

#ifndef PROTOBUF_UserDiscipleInfo_2eproto__INCLUDED
#define PROTOBUF_UserDiscipleInfo_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_UserDiscipleInfo_2eproto();
void protobuf_AssignDesc_UserDiscipleInfo_2eproto();
void protobuf_ShutdownFile_UserDiscipleInfo_2eproto();

class OPUserDiscipleInfo;
class OPUserDiscipleInfoRet;
class OPUserDiscipleInfoRet_DiscipleInfo;

// ===================================================================

class OPUserDiscipleInfo : public ::google::protobuf::Message {
 public:
  OPUserDiscipleInfo();
  virtual ~OPUserDiscipleInfo();

  OPUserDiscipleInfo(const OPUserDiscipleInfo& from);

  inline OPUserDiscipleInfo& operator=(const OPUserDiscipleInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const OPUserDiscipleInfo& default_instance();

  void Swap(OPUserDiscipleInfo* other);

  // implements Message ----------------------------------------------

  OPUserDiscipleInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const OPUserDiscipleInfo& from);
  void MergeFrom(const OPUserDiscipleInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 version = 1 [default = 1];
  inline bool has_version() const;
  inline void clear_version();
  static const int kVersionFieldNumber = 1;
  inline ::google::protobuf::int32 version() const;
  inline void set_version(::google::protobuf::int32 value);

  // optional int32 id = 2;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 2;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:OPUserDiscipleInfo)
 private:
  inline void set_has_version();
  inline void clear_has_version();
  inline void set_has_id();
  inline void clear_has_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 version_;
  ::google::protobuf::int32 id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_UserDiscipleInfo_2eproto();
  friend void protobuf_AssignDesc_UserDiscipleInfo_2eproto();
  friend void protobuf_ShutdownFile_UserDiscipleInfo_2eproto();

  void InitAsDefaultInstance();
  static OPUserDiscipleInfo* default_instance_;
};
// -------------------------------------------------------------------

class OPUserDiscipleInfoRet_DiscipleInfo : public ::google::protobuf::Message {
 public:
  OPUserDiscipleInfoRet_DiscipleInfo();
  virtual ~OPUserDiscipleInfoRet_DiscipleInfo();

  OPUserDiscipleInfoRet_DiscipleInfo(const OPUserDiscipleInfoRet_DiscipleInfo& from);

  inline OPUserDiscipleInfoRet_DiscipleInfo& operator=(const OPUserDiscipleInfoRet_DiscipleInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const OPUserDiscipleInfoRet_DiscipleInfo& default_instance();

  void Swap(OPUserDiscipleInfoRet_DiscipleInfo* other);

  // implements Message ----------------------------------------------

  OPUserDiscipleInfoRet_DiscipleInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const OPUserDiscipleInfoRet_DiscipleInfo& from);
  void MergeFrom(const OPUserDiscipleInfoRet_DiscipleInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);

  // required int32 itemid = 2;
  inline bool has_itemid() const;
  inline void clear_itemid();
  static const int kItemidFieldNumber = 2;
  inline ::google::protobuf::int32 itemid() const;
  inline void set_itemid(::google::protobuf::int32 value);

  // required int32 level = 3;
  inline bool has_level() const;
  inline void clear_level();
  static const int kLevelFieldNumber = 3;
  inline ::google::protobuf::int32 level() const;
  inline void set_level(::google::protobuf::int32 value);

  // required int32 exp = 4;
  inline bool has_exp() const;
  inline void clear_exp();
  static const int kExpFieldNumber = 4;
  inline ::google::protobuf::int32 exp() const;
  inline void set_exp(::google::protobuf::int32 value);

  // required int32 health = 5;
  inline bool has_health() const;
  inline void clear_health();
  static const int kHealthFieldNumber = 5;
  inline ::google::protobuf::int32 health() const;
  inline void set_health(::google::protobuf::int32 value);

  // required int32 attack = 6;
  inline bool has_attack() const;
  inline void clear_attack();
  static const int kAttackFieldNumber = 6;
  inline ::google::protobuf::int32 attack() const;
  inline void set_attack(::google::protobuf::int32 value);

  // required int32 defence = 7;
  inline bool has_defence() const;
  inline void clear_defence();
  static const int kDefenceFieldNumber = 7;
  inline ::google::protobuf::int32 defence() const;
  inline void set_defence(::google::protobuf::int32 value);

  // required int32 rp = 8;
  inline bool has_rp() const;
  inline void clear_rp();
  static const int kRpFieldNumber = 8;
  inline ::google::protobuf::int32 rp() const;
  inline void set_rp(::google::protobuf::int32 value);

  // required int32 upgradelevel = 9;
  inline bool has_upgradelevel() const;
  inline void clear_upgradelevel();
  static const int kUpgradelevelFieldNumber = 9;
  inline ::google::protobuf::int32 upgradelevel() const;
  inline void set_upgradelevel(::google::protobuf::int32 value);

  // required int32 potentiality = 10;
  inline bool has_potentiality() const;
  inline void clear_potentiality();
  static const int kPotentialityFieldNumber = 10;
  inline ::google::protobuf::int32 potentiality() const;
  inline void set_potentiality(::google::protobuf::int32 value);

  // required int32 skill1 = 11;
  inline bool has_skill1() const;
  inline void clear_skill1();
  static const int kSkill1FieldNumber = 11;
  inline ::google::protobuf::int32 skill1() const;
  inline void set_skill1(::google::protobuf::int32 value);

  // required int32 battleid = 12;
  inline bool has_battleid() const;
  inline void clear_battleid();
  static const int kBattleidFieldNumber = 12;
  inline ::google::protobuf::int32 battleid() const;
  inline void set_battleid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:OPUserDiscipleInfoRet.DiscipleInfo)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_itemid();
  inline void clear_has_itemid();
  inline void set_has_level();
  inline void clear_has_level();
  inline void set_has_exp();
  inline void clear_has_exp();
  inline void set_has_health();
  inline void clear_has_health();
  inline void set_has_attack();
  inline void clear_has_attack();
  inline void set_has_defence();
  inline void clear_has_defence();
  inline void set_has_rp();
  inline void clear_has_rp();
  inline void set_has_upgradelevel();
  inline void clear_has_upgradelevel();
  inline void set_has_potentiality();
  inline void clear_has_potentiality();
  inline void set_has_skill1();
  inline void clear_has_skill1();
  inline void set_has_battleid();
  inline void clear_has_battleid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 id_;
  ::google::protobuf::int32 itemid_;
  ::google::protobuf::int32 level_;
  ::google::protobuf::int32 exp_;
  ::google::protobuf::int32 health_;
  ::google::protobuf::int32 attack_;
  ::google::protobuf::int32 defence_;
  ::google::protobuf::int32 rp_;
  ::google::protobuf::int32 upgradelevel_;
  ::google::protobuf::int32 potentiality_;
  ::google::protobuf::int32 skill1_;
  ::google::protobuf::int32 battleid_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(12 + 31) / 32];

  friend void  protobuf_AddDesc_UserDiscipleInfo_2eproto();
  friend void protobuf_AssignDesc_UserDiscipleInfo_2eproto();
  friend void protobuf_ShutdownFile_UserDiscipleInfo_2eproto();

  void InitAsDefaultInstance();
  static OPUserDiscipleInfoRet_DiscipleInfo* default_instance_;
};
// -------------------------------------------------------------------

class OPUserDiscipleInfoRet : public ::google::protobuf::Message {
 public:
  OPUserDiscipleInfoRet();
  virtual ~OPUserDiscipleInfoRet();

  OPUserDiscipleInfoRet(const OPUserDiscipleInfoRet& from);

  inline OPUserDiscipleInfoRet& operator=(const OPUserDiscipleInfoRet& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const OPUserDiscipleInfoRet& default_instance();

  void Swap(OPUserDiscipleInfoRet* other);

  // implements Message ----------------------------------------------

  OPUserDiscipleInfoRet* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const OPUserDiscipleInfoRet& from);
  void MergeFrom(const OPUserDiscipleInfoRet& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef OPUserDiscipleInfoRet_DiscipleInfo DiscipleInfo;

  // accessors -------------------------------------------------------

  // required int32 servertime = 1;
  inline bool has_servertime() const;
  inline void clear_servertime();
  static const int kServertimeFieldNumber = 1;
  inline ::google::protobuf::int32 servertime() const;
  inline void set_servertime(::google::protobuf::int32 value);

  // repeated .OPUserDiscipleInfoRet.DiscipleInfo disciple = 2;
  inline int disciple_size() const;
  inline void clear_disciple();
  static const int kDiscipleFieldNumber = 2;
  inline const ::OPUserDiscipleInfoRet_DiscipleInfo& disciple(int index) const;
  inline ::OPUserDiscipleInfoRet_DiscipleInfo* mutable_disciple(int index);
  inline ::OPUserDiscipleInfoRet_DiscipleInfo* add_disciple();
  inline const ::google::protobuf::RepeatedPtrField< ::OPUserDiscipleInfoRet_DiscipleInfo >&
      disciple() const;
  inline ::google::protobuf::RepeatedPtrField< ::OPUserDiscipleInfoRet_DiscipleInfo >*
      mutable_disciple();

  // @@protoc_insertion_point(class_scope:OPUserDiscipleInfoRet)
 private:
  inline void set_has_servertime();
  inline void clear_has_servertime();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::OPUserDiscipleInfoRet_DiscipleInfo > disciple_;
  ::google::protobuf::int32 servertime_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_UserDiscipleInfo_2eproto();
  friend void protobuf_AssignDesc_UserDiscipleInfo_2eproto();
  friend void protobuf_ShutdownFile_UserDiscipleInfo_2eproto();

  void InitAsDefaultInstance();
  static OPUserDiscipleInfoRet* default_instance_;
};
// ===================================================================


// ===================================================================

// OPUserDiscipleInfo

// required int32 version = 1 [default = 1];
inline bool OPUserDiscipleInfo::has_version() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void OPUserDiscipleInfo::set_has_version() {
  _has_bits_[0] |= 0x00000001u;
}
inline void OPUserDiscipleInfo::clear_has_version() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void OPUserDiscipleInfo::clear_version() {
  version_ = 1;
  clear_has_version();
}
inline ::google::protobuf::int32 OPUserDiscipleInfo::version() const {
  return version_;
}
inline void OPUserDiscipleInfo::set_version(::google::protobuf::int32 value) {
  set_has_version();
  version_ = value;
}

// optional int32 id = 2;
inline bool OPUserDiscipleInfo::has_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void OPUserDiscipleInfo::set_has_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void OPUserDiscipleInfo::clear_has_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void OPUserDiscipleInfo::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 OPUserDiscipleInfo::id() const {
  return id_;
}
inline void OPUserDiscipleInfo::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
}

// -------------------------------------------------------------------

// OPUserDiscipleInfoRet_DiscipleInfo

// required int32 id = 1;
inline bool OPUserDiscipleInfoRet_DiscipleInfo::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void OPUserDiscipleInfoRet_DiscipleInfo::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void OPUserDiscipleInfoRet_DiscipleInfo::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void OPUserDiscipleInfoRet_DiscipleInfo::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 OPUserDiscipleInfoRet_DiscipleInfo::id() const {
  return id_;
}
inline void OPUserDiscipleInfoRet_DiscipleInfo::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
}

// required int32 itemid = 2;
inline bool OPUserDiscipleInfoRet_DiscipleInfo::has_itemid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void OPUserDiscipleInfoRet_DiscipleInfo::set_has_itemid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void OPUserDiscipleInfoRet_DiscipleInfo::clear_has_itemid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void OPUserDiscipleInfoRet_DiscipleInfo::clear_itemid() {
  itemid_ = 0;
  clear_has_itemid();
}
inline ::google::protobuf::int32 OPUserDiscipleInfoRet_DiscipleInfo::itemid() const {
  return itemid_;
}
inline void OPUserDiscipleInfoRet_DiscipleInfo::set_itemid(::google::protobuf::int32 value) {
  set_has_itemid();
  itemid_ = value;
}

// required int32 level = 3;
inline bool OPUserDiscipleInfoRet_DiscipleInfo::has_level() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void OPUserDiscipleInfoRet_DiscipleInfo::set_has_level() {
  _has_bits_[0] |= 0x00000004u;
}
inline void OPUserDiscipleInfoRet_DiscipleInfo::clear_has_level() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void OPUserDiscipleInfoRet_DiscipleInfo::clear_level() {
  level_ = 0;
  clear_has_level();
}
inline ::google::protobuf::int32 OPUserDiscipleInfoRet_DiscipleInfo::level() const {
  return level_;
}
inline void OPUserDiscipleInfoRet_DiscipleInfo::set_level(::google::protobuf::int32 value) {
  set_has_level();
  level_ = value;
}

// required int32 exp = 4;
inline bool OPUserDiscipleInfoRet_DiscipleInfo::has_exp() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void OPUserDiscipleInfoRet_DiscipleInfo::set_has_exp() {
  _has_bits_[0] |= 0x00000008u;
}
inline void OPUserDiscipleInfoRet_DiscipleInfo::clear_has_exp() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void OPUserDiscipleInfoRet_DiscipleInfo::clear_exp() {
  exp_ = 0;
  clear_has_exp();
}
inline ::google::protobuf::int32 OPUserDiscipleInfoRet_DiscipleInfo::exp() const {
  return exp_;
}
inline void OPUserDiscipleInfoRet_DiscipleInfo::set_exp(::google::protobuf::int32 value) {
  set_has_exp();
  exp_ = value;
}

// required int32 health = 5;
inline bool OPUserDiscipleInfoRet_DiscipleInfo::has_health() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void OPUserDiscipleInfoRet_DiscipleInfo::set_has_health() {
  _has_bits_[0] |= 0x00000010u;
}
inline void OPUserDiscipleInfoRet_DiscipleInfo::clear_has_health() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void OPUserDiscipleInfoRet_DiscipleInfo::clear_health() {
  health_ = 0;
  clear_has_health();
}
inline ::google::protobuf::int32 OPUserDiscipleInfoRet_DiscipleInfo::health() const {
  return health_;
}
inline void OPUserDiscipleInfoRet_DiscipleInfo::set_health(::google::protobuf::int32 value) {
  set_has_health();
  health_ = value;
}

// required int32 attack = 6;
inline bool OPUserDiscipleInfoRet_DiscipleInfo::has_attack() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void OPUserDiscipleInfoRet_DiscipleInfo::set_has_attack() {
  _has_bits_[0] |= 0x00000020u;
}
inline void OPUserDiscipleInfoRet_DiscipleInfo::clear_has_attack() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void OPUserDiscipleInfoRet_DiscipleInfo::clear_attack() {
  attack_ = 0;
  clear_has_attack();
}
inline ::google::protobuf::int32 OPUserDiscipleInfoRet_DiscipleInfo::attack() const {
  return attack_;
}
inline void OPUserDiscipleInfoRet_DiscipleInfo::set_attack(::google::protobuf::int32 value) {
  set_has_attack();
  attack_ = value;
}

// required int32 defence = 7;
inline bool OPUserDiscipleInfoRet_DiscipleInfo::has_defence() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void OPUserDiscipleInfoRet_DiscipleInfo::set_has_defence() {
  _has_bits_[0] |= 0x00000040u;
}
inline void OPUserDiscipleInfoRet_DiscipleInfo::clear_has_defence() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void OPUserDiscipleInfoRet_DiscipleInfo::clear_defence() {
  defence_ = 0;
  clear_has_defence();
}
inline ::google::protobuf::int32 OPUserDiscipleInfoRet_DiscipleInfo::defence() const {
  return defence_;
}
inline void OPUserDiscipleInfoRet_DiscipleInfo::set_defence(::google::protobuf::int32 value) {
  set_has_defence();
  defence_ = value;
}

// required int32 rp = 8;
inline bool OPUserDiscipleInfoRet_DiscipleInfo::has_rp() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void OPUserDiscipleInfoRet_DiscipleInfo::set_has_rp() {
  _has_bits_[0] |= 0x00000080u;
}
inline void OPUserDiscipleInfoRet_DiscipleInfo::clear_has_rp() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void OPUserDiscipleInfoRet_DiscipleInfo::clear_rp() {
  rp_ = 0;
  clear_has_rp();
}
inline ::google::protobuf::int32 OPUserDiscipleInfoRet_DiscipleInfo::rp() const {
  return rp_;
}
inline void OPUserDiscipleInfoRet_DiscipleInfo::set_rp(::google::protobuf::int32 value) {
  set_has_rp();
  rp_ = value;
}

// required int32 upgradelevel = 9;
inline bool OPUserDiscipleInfoRet_DiscipleInfo::has_upgradelevel() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void OPUserDiscipleInfoRet_DiscipleInfo::set_has_upgradelevel() {
  _has_bits_[0] |= 0x00000100u;
}
inline void OPUserDiscipleInfoRet_DiscipleInfo::clear_has_upgradelevel() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void OPUserDiscipleInfoRet_DiscipleInfo::clear_upgradelevel() {
  upgradelevel_ = 0;
  clear_has_upgradelevel();
}
inline ::google::protobuf::int32 OPUserDiscipleInfoRet_DiscipleInfo::upgradelevel() const {
  return upgradelevel_;
}
inline void OPUserDiscipleInfoRet_DiscipleInfo::set_upgradelevel(::google::protobuf::int32 value) {
  set_has_upgradelevel();
  upgradelevel_ = value;
}

// required int32 potentiality = 10;
inline bool OPUserDiscipleInfoRet_DiscipleInfo::has_potentiality() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void OPUserDiscipleInfoRet_DiscipleInfo::set_has_potentiality() {
  _has_bits_[0] |= 0x00000200u;
}
inline void OPUserDiscipleInfoRet_DiscipleInfo::clear_has_potentiality() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void OPUserDiscipleInfoRet_DiscipleInfo::clear_potentiality() {
  potentiality_ = 0;
  clear_has_potentiality();
}
inline ::google::protobuf::int32 OPUserDiscipleInfoRet_DiscipleInfo::potentiality() const {
  return potentiality_;
}
inline void OPUserDiscipleInfoRet_DiscipleInfo::set_potentiality(::google::protobuf::int32 value) {
  set_has_potentiality();
  potentiality_ = value;
}

// required int32 skill1 = 11;
inline bool OPUserDiscipleInfoRet_DiscipleInfo::has_skill1() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void OPUserDiscipleInfoRet_DiscipleInfo::set_has_skill1() {
  _has_bits_[0] |= 0x00000400u;
}
inline void OPUserDiscipleInfoRet_DiscipleInfo::clear_has_skill1() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void OPUserDiscipleInfoRet_DiscipleInfo::clear_skill1() {
  skill1_ = 0;
  clear_has_skill1();
}
inline ::google::protobuf::int32 OPUserDiscipleInfoRet_DiscipleInfo::skill1() const {
  return skill1_;
}
inline void OPUserDiscipleInfoRet_DiscipleInfo::set_skill1(::google::protobuf::int32 value) {
  set_has_skill1();
  skill1_ = value;
}

// required int32 battleid = 12;
inline bool OPUserDiscipleInfoRet_DiscipleInfo::has_battleid() const {
  return (_has_bits_[0] & 0x00000800u) != 0;
}
inline void OPUserDiscipleInfoRet_DiscipleInfo::set_has_battleid() {
  _has_bits_[0] |= 0x00000800u;
}
inline void OPUserDiscipleInfoRet_DiscipleInfo::clear_has_battleid() {
  _has_bits_[0] &= ~0x00000800u;
}
inline void OPUserDiscipleInfoRet_DiscipleInfo::clear_battleid() {
  battleid_ = 0;
  clear_has_battleid();
}
inline ::google::protobuf::int32 OPUserDiscipleInfoRet_DiscipleInfo::battleid() const {
  return battleid_;
}
inline void OPUserDiscipleInfoRet_DiscipleInfo::set_battleid(::google::protobuf::int32 value) {
  set_has_battleid();
  battleid_ = value;
}

// -------------------------------------------------------------------

// OPUserDiscipleInfoRet

// required int32 servertime = 1;
inline bool OPUserDiscipleInfoRet::has_servertime() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void OPUserDiscipleInfoRet::set_has_servertime() {
  _has_bits_[0] |= 0x00000001u;
}
inline void OPUserDiscipleInfoRet::clear_has_servertime() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void OPUserDiscipleInfoRet::clear_servertime() {
  servertime_ = 0;
  clear_has_servertime();
}
inline ::google::protobuf::int32 OPUserDiscipleInfoRet::servertime() const {
  return servertime_;
}
inline void OPUserDiscipleInfoRet::set_servertime(::google::protobuf::int32 value) {
  set_has_servertime();
  servertime_ = value;
}

// repeated .OPUserDiscipleInfoRet.DiscipleInfo disciple = 2;
inline int OPUserDiscipleInfoRet::disciple_size() const {
  return disciple_.size();
}
inline void OPUserDiscipleInfoRet::clear_disciple() {
  disciple_.Clear();
}
inline const ::OPUserDiscipleInfoRet_DiscipleInfo& OPUserDiscipleInfoRet::disciple(int index) const {
  return disciple_.Get(index);
}
inline ::OPUserDiscipleInfoRet_DiscipleInfo* OPUserDiscipleInfoRet::mutable_disciple(int index) {
  return disciple_.Mutable(index);
}
inline ::OPUserDiscipleInfoRet_DiscipleInfo* OPUserDiscipleInfoRet::add_disciple() {
  return disciple_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::OPUserDiscipleInfoRet_DiscipleInfo >&
OPUserDiscipleInfoRet::disciple() const {
  return disciple_;
}
inline ::google::protobuf::RepeatedPtrField< ::OPUserDiscipleInfoRet_DiscipleInfo >*
OPUserDiscipleInfoRet::mutable_disciple() {
  return &disciple_;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_UserDiscipleInfo_2eproto__INCLUDED
