// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BackStageFetchLucky.proto

package com.oldmountain.dzm.message;

public final class BackStageFetchLucky {
  private BackStageFetchLucky() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface OPBackStageFetchLuckyOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 version = 1 [default = 1];
    /**
     * <code>required int32 version = 1 [default = 1];</code>
     */
    boolean hasVersion();
    /**
     * <code>required int32 version = 1 [default = 1];</code>
     */
    int getVersion();

    // required string name = 2;
    /**
     * <code>required string name = 2;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code OPBackStageFetchLucky}
   */
  public static final class OPBackStageFetchLucky extends
      com.google.protobuf.GeneratedMessage
      implements OPBackStageFetchLuckyOrBuilder {
    // Use OPBackStageFetchLucky.newBuilder() to construct.
    private OPBackStageFetchLucky(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private OPBackStageFetchLucky(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final OPBackStageFetchLucky defaultInstance;
    public static OPBackStageFetchLucky getDefaultInstance() {
      return defaultInstance;
    }

    public OPBackStageFetchLucky getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private OPBackStageFetchLucky(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              version_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.oldmountain.dzm.message.BackStageFetchLucky.internal_static_OPBackStageFetchLucky_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.oldmountain.dzm.message.BackStageFetchLucky.internal_static_OPBackStageFetchLucky_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.oldmountain.dzm.message.BackStageFetchLucky.OPBackStageFetchLucky.class, com.oldmountain.dzm.message.BackStageFetchLucky.OPBackStageFetchLucky.Builder.class);
    }

    public static com.google.protobuf.Parser<OPBackStageFetchLucky> PARSER =
        new com.google.protobuf.AbstractParser<OPBackStageFetchLucky>() {
      public OPBackStageFetchLucky parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OPBackStageFetchLucky(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<OPBackStageFetchLucky> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 version = 1 [default = 1];
    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    /**
     * <code>required int32 version = 1 [default = 1];</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 version = 1 [default = 1];</code>
     */
    public int getVersion() {
      return version_;
    }

    // required string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    /**
     * <code>required string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      version_ = 1;
      name_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.oldmountain.dzm.message.BackStageFetchLucky.OPBackStageFetchLucky parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.oldmountain.dzm.message.BackStageFetchLucky.OPBackStageFetchLucky parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.oldmountain.dzm.message.BackStageFetchLucky.OPBackStageFetchLucky parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.oldmountain.dzm.message.BackStageFetchLucky.OPBackStageFetchLucky parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.oldmountain.dzm.message.BackStageFetchLucky.OPBackStageFetchLucky parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.oldmountain.dzm.message.BackStageFetchLucky.OPBackStageFetchLucky parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.oldmountain.dzm.message.BackStageFetchLucky.OPBackStageFetchLucky parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.oldmountain.dzm.message.BackStageFetchLucky.OPBackStageFetchLucky parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.oldmountain.dzm.message.BackStageFetchLucky.OPBackStageFetchLucky parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.oldmountain.dzm.message.BackStageFetchLucky.OPBackStageFetchLucky parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.oldmountain.dzm.message.BackStageFetchLucky.OPBackStageFetchLucky prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code OPBackStageFetchLucky}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.oldmountain.dzm.message.BackStageFetchLucky.OPBackStageFetchLuckyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.oldmountain.dzm.message.BackStageFetchLucky.internal_static_OPBackStageFetchLucky_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.oldmountain.dzm.message.BackStageFetchLucky.internal_static_OPBackStageFetchLucky_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.oldmountain.dzm.message.BackStageFetchLucky.OPBackStageFetchLucky.class, com.oldmountain.dzm.message.BackStageFetchLucky.OPBackStageFetchLucky.Builder.class);
      }

      // Construct using com.oldmountain.dzm.message.BackStageFetchLucky.OPBackStageFetchLucky.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        version_ = 1;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.oldmountain.dzm.message.BackStageFetchLucky.internal_static_OPBackStageFetchLucky_descriptor;
      }

      public com.oldmountain.dzm.message.BackStageFetchLucky.OPBackStageFetchLucky getDefaultInstanceForType() {
        return com.oldmountain.dzm.message.BackStageFetchLucky.OPBackStageFetchLucky.getDefaultInstance();
      }

      public com.oldmountain.dzm.message.BackStageFetchLucky.OPBackStageFetchLucky build() {
        com.oldmountain.dzm.message.BackStageFetchLucky.OPBackStageFetchLucky result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.oldmountain.dzm.message.BackStageFetchLucky.OPBackStageFetchLucky buildPartial() {
        com.oldmountain.dzm.message.BackStageFetchLucky.OPBackStageFetchLucky result = new com.oldmountain.dzm.message.BackStageFetchLucky.OPBackStageFetchLucky(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.oldmountain.dzm.message.BackStageFetchLucky.OPBackStageFetchLucky) {
          return mergeFrom((com.oldmountain.dzm.message.BackStageFetchLucky.OPBackStageFetchLucky)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.oldmountain.dzm.message.BackStageFetchLucky.OPBackStageFetchLucky other) {
        if (other == com.oldmountain.dzm.message.BackStageFetchLucky.OPBackStageFetchLucky.getDefaultInstance()) return this;
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasVersion()) {
          
          return false;
        }
        if (!hasName()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.oldmountain.dzm.message.BackStageFetchLucky.OPBackStageFetchLucky parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.oldmountain.dzm.message.BackStageFetchLucky.OPBackStageFetchLucky) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 version = 1 [default = 1];
      private int version_ = 1;
      /**
       * <code>required int32 version = 1 [default = 1];</code>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 version = 1 [default = 1];</code>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <code>required int32 version = 1 [default = 1];</code>
       */
      public Builder setVersion(int value) {
        bitField0_ |= 0x00000001;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 version = 1 [default = 1];</code>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = 1;
        onChanged();
        return this;
      }

      // required string name = 2;
      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:OPBackStageFetchLucky)
    }

    static {
      defaultInstance = new OPBackStageFetchLucky(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:OPBackStageFetchLucky)
  }

  public interface OPBackStageFetchLuckyRetOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 servertime = 1;
    /**
     * <code>required int32 servertime = 1;</code>
     */
    boolean hasServertime();
    /**
     * <code>required int32 servertime = 1;</code>
     */
    int getServertime();

    // required int32 userid = 2;
    /**
     * <code>required int32 userid = 2;</code>
     */
    boolean hasUserid();
    /**
     * <code>required int32 userid = 2;</code>
     */
    int getUserid();

    // required string name = 3;
    /**
     * <code>required string name = 3;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 3;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 3;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // required int32 registertime = 4;
    /**
     * <code>required int32 registertime = 4;</code>
     */
    boolean hasRegistertime();
    /**
     * <code>required int32 registertime = 4;</code>
     */
    int getRegistertime();

    // required int32 lastlogin = 5;
    /**
     * <code>required int32 lastlogin = 5;</code>
     */
    boolean hasLastlogin();
    /**
     * <code>required int32 lastlogin = 5;</code>
     */
    int getLastlogin();

    // required int32 level = 6;
    /**
     * <code>required int32 level = 6;</code>
     */
    boolean hasLevel();
    /**
     * <code>required int32 level = 6;</code>
     */
    int getLevel();

    // required int64 silvercoins = 7;
    /**
     * <code>required int64 silvercoins = 7;</code>
     */
    boolean hasSilvercoins();
    /**
     * <code>required int64 silvercoins = 7;</code>
     */
    long getSilvercoins();

    // required int32 goldcoins = 8;
    /**
     * <code>required int32 goldcoins = 8;</code>
     */
    boolean hasGoldcoins();
    /**
     * <code>required int32 goldcoins = 8;</code>
     */
    int getGoldcoins();

    // required int32 thisLuckPool = 9;
    /**
     * <code>required int32 thisLuckPool = 9;</code>
     */
    boolean hasThisLuckPool();
    /**
     * <code>required int32 thisLuckPool = 9;</code>
     */
    int getThisLuckPool();

    // required int32 nextLuckPool = 10;
    /**
     * <code>required int32 nextLuckPool = 10;</code>
     */
    boolean hasNextLuckPool();
    /**
     * <code>required int32 nextLuckPool = 10;</code>
     */
    int getNextLuckPool();

    // required int32 luckOne = 11;
    /**
     * <code>required int32 luckOne = 11;</code>
     */
    boolean hasLuckOne();
    /**
     * <code>required int32 luckOne = 11;</code>
     */
    int getLuckOne();

    // required int32 luckTwo = 12;
    /**
     * <code>required int32 luckTwo = 12;</code>
     */
    boolean hasLuckTwo();
    /**
     * <code>required int32 luckTwo = 12;</code>
     */
    int getLuckTwo();

    // required int32 treasureWorth = 13;
    /**
     * <code>required int32 treasureWorth = 13;</code>
     */
    boolean hasTreasureWorth();
    /**
     * <code>required int32 treasureWorth = 13;</code>
     */
    int getTreasureWorth();

    // required int32 thisDisciple = 14;
    /**
     * <code>required int32 thisDisciple = 14;</code>
     */
    boolean hasThisDisciple();
    /**
     * <code>required int32 thisDisciple = 14;</code>
     */
    int getThisDisciple();

    // required int32 nextDisciple = 15;
    /**
     * <code>required int32 nextDisciple = 15;</code>
     */
    boolean hasNextDisciple();
    /**
     * <code>required int32 nextDisciple = 15;</code>
     */
    int getNextDisciple();

    // required int32 discipleLucky = 16;
    /**
     * <code>required int32 discipleLucky = 16;</code>
     */
    boolean hasDiscipleLucky();
    /**
     * <code>required int32 discipleLucky = 16;</code>
     */
    int getDiscipleLucky();
  }
  /**
   * Protobuf type {@code OPBackStageFetchLuckyRet}
   */
  public static final class OPBackStageFetchLuckyRet extends
      com.google.protobuf.GeneratedMessage
      implements OPBackStageFetchLuckyRetOrBuilder {
    // Use OPBackStageFetchLuckyRet.newBuilder() to construct.
    private OPBackStageFetchLuckyRet(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private OPBackStageFetchLuckyRet(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final OPBackStageFetchLuckyRet defaultInstance;
    public static OPBackStageFetchLuckyRet getDefaultInstance() {
      return defaultInstance;
    }

    public OPBackStageFetchLuckyRet getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private OPBackStageFetchLuckyRet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              servertime_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              userid_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              name_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              registertime_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              lastlogin_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              level_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              silvercoins_ = input.readInt64();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              goldcoins_ = input.readInt32();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              thisLuckPool_ = input.readInt32();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000200;
              nextLuckPool_ = input.readInt32();
              break;
            }
            case 88: {
              bitField0_ |= 0x00000400;
              luckOne_ = input.readInt32();
              break;
            }
            case 96: {
              bitField0_ |= 0x00000800;
              luckTwo_ = input.readInt32();
              break;
            }
            case 104: {
              bitField0_ |= 0x00001000;
              treasureWorth_ = input.readInt32();
              break;
            }
            case 112: {
              bitField0_ |= 0x00002000;
              thisDisciple_ = input.readInt32();
              break;
            }
            case 120: {
              bitField0_ |= 0x00004000;
              nextDisciple_ = input.readInt32();
              break;
            }
            case 128: {
              bitField0_ |= 0x00008000;
              discipleLucky_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.oldmountain.dzm.message.BackStageFetchLucky.internal_static_OPBackStageFetchLuckyRet_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.oldmountain.dzm.message.BackStageFetchLucky.internal_static_OPBackStageFetchLuckyRet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.oldmountain.dzm.message.BackStageFetchLucky.OPBackStageFetchLuckyRet.class, com.oldmountain.dzm.message.BackStageFetchLucky.OPBackStageFetchLuckyRet.Builder.class);
    }

    public static com.google.protobuf.Parser<OPBackStageFetchLuckyRet> PARSER =
        new com.google.protobuf.AbstractParser<OPBackStageFetchLuckyRet>() {
      public OPBackStageFetchLuckyRet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OPBackStageFetchLuckyRet(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<OPBackStageFetchLuckyRet> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 servertime = 1;
    public static final int SERVERTIME_FIELD_NUMBER = 1;
    private int servertime_;
    /**
     * <code>required int32 servertime = 1;</code>
     */
    public boolean hasServertime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 servertime = 1;</code>
     */
    public int getServertime() {
      return servertime_;
    }

    // required int32 userid = 2;
    public static final int USERID_FIELD_NUMBER = 2;
    private int userid_;
    /**
     * <code>required int32 userid = 2;</code>
     */
    public boolean hasUserid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 userid = 2;</code>
     */
    public int getUserid() {
      return userid_;
    }

    // required string name = 3;
    public static final int NAME_FIELD_NUMBER = 3;
    private java.lang.Object name_;
    /**
     * <code>required string name = 3;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string name = 3;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 registertime = 4;
    public static final int REGISTERTIME_FIELD_NUMBER = 4;
    private int registertime_;
    /**
     * <code>required int32 registertime = 4;</code>
     */
    public boolean hasRegistertime() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 registertime = 4;</code>
     */
    public int getRegistertime() {
      return registertime_;
    }

    // required int32 lastlogin = 5;
    public static final int LASTLOGIN_FIELD_NUMBER = 5;
    private int lastlogin_;
    /**
     * <code>required int32 lastlogin = 5;</code>
     */
    public boolean hasLastlogin() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 lastlogin = 5;</code>
     */
    public int getLastlogin() {
      return lastlogin_;
    }

    // required int32 level = 6;
    public static final int LEVEL_FIELD_NUMBER = 6;
    private int level_;
    /**
     * <code>required int32 level = 6;</code>
     */
    public boolean hasLevel() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required int32 level = 6;</code>
     */
    public int getLevel() {
      return level_;
    }

    // required int64 silvercoins = 7;
    public static final int SILVERCOINS_FIELD_NUMBER = 7;
    private long silvercoins_;
    /**
     * <code>required int64 silvercoins = 7;</code>
     */
    public boolean hasSilvercoins() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required int64 silvercoins = 7;</code>
     */
    public long getSilvercoins() {
      return silvercoins_;
    }

    // required int32 goldcoins = 8;
    public static final int GOLDCOINS_FIELD_NUMBER = 8;
    private int goldcoins_;
    /**
     * <code>required int32 goldcoins = 8;</code>
     */
    public boolean hasGoldcoins() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>required int32 goldcoins = 8;</code>
     */
    public int getGoldcoins() {
      return goldcoins_;
    }

    // required int32 thisLuckPool = 9;
    public static final int THISLUCKPOOL_FIELD_NUMBER = 9;
    private int thisLuckPool_;
    /**
     * <code>required int32 thisLuckPool = 9;</code>
     */
    public boolean hasThisLuckPool() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>required int32 thisLuckPool = 9;</code>
     */
    public int getThisLuckPool() {
      return thisLuckPool_;
    }

    // required int32 nextLuckPool = 10;
    public static final int NEXTLUCKPOOL_FIELD_NUMBER = 10;
    private int nextLuckPool_;
    /**
     * <code>required int32 nextLuckPool = 10;</code>
     */
    public boolean hasNextLuckPool() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>required int32 nextLuckPool = 10;</code>
     */
    public int getNextLuckPool() {
      return nextLuckPool_;
    }

    // required int32 luckOne = 11;
    public static final int LUCKONE_FIELD_NUMBER = 11;
    private int luckOne_;
    /**
     * <code>required int32 luckOne = 11;</code>
     */
    public boolean hasLuckOne() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>required int32 luckOne = 11;</code>
     */
    public int getLuckOne() {
      return luckOne_;
    }

    // required int32 luckTwo = 12;
    public static final int LUCKTWO_FIELD_NUMBER = 12;
    private int luckTwo_;
    /**
     * <code>required int32 luckTwo = 12;</code>
     */
    public boolean hasLuckTwo() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>required int32 luckTwo = 12;</code>
     */
    public int getLuckTwo() {
      return luckTwo_;
    }

    // required int32 treasureWorth = 13;
    public static final int TREASUREWORTH_FIELD_NUMBER = 13;
    private int treasureWorth_;
    /**
     * <code>required int32 treasureWorth = 13;</code>
     */
    public boolean hasTreasureWorth() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>required int32 treasureWorth = 13;</code>
     */
    public int getTreasureWorth() {
      return treasureWorth_;
    }

    // required int32 thisDisciple = 14;
    public static final int THISDISCIPLE_FIELD_NUMBER = 14;
    private int thisDisciple_;
    /**
     * <code>required int32 thisDisciple = 14;</code>
     */
    public boolean hasThisDisciple() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    /**
     * <code>required int32 thisDisciple = 14;</code>
     */
    public int getThisDisciple() {
      return thisDisciple_;
    }

    // required int32 nextDisciple = 15;
    public static final int NEXTDISCIPLE_FIELD_NUMBER = 15;
    private int nextDisciple_;
    /**
     * <code>required int32 nextDisciple = 15;</code>
     */
    public boolean hasNextDisciple() {
      return ((bitField0_ & 0x00004000) == 0x00004000);
    }
    /**
     * <code>required int32 nextDisciple = 15;</code>
     */
    public int getNextDisciple() {
      return nextDisciple_;
    }

    // required int32 discipleLucky = 16;
    public static final int DISCIPLELUCKY_FIELD_NUMBER = 16;
    private int discipleLucky_;
    /**
     * <code>required int32 discipleLucky = 16;</code>
     */
    public boolean hasDiscipleLucky() {
      return ((bitField0_ & 0x00008000) == 0x00008000);
    }
    /**
     * <code>required int32 discipleLucky = 16;</code>
     */
    public int getDiscipleLucky() {
      return discipleLucky_;
    }

    private void initFields() {
      servertime_ = 0;
      userid_ = 0;
      name_ = "";
      registertime_ = 0;
      lastlogin_ = 0;
      level_ = 0;
      silvercoins_ = 0L;
      goldcoins_ = 0;
      thisLuckPool_ = 0;
      nextLuckPool_ = 0;
      luckOne_ = 0;
      luckTwo_ = 0;
      treasureWorth_ = 0;
      thisDisciple_ = 0;
      nextDisciple_ = 0;
      discipleLucky_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasServertime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUserid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRegistertime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLastlogin()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLevel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSilvercoins()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasGoldcoins()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasThisLuckPool()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNextLuckPool()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLuckOne()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLuckTwo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTreasureWorth()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasThisDisciple()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNextDisciple()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDiscipleLucky()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, servertime_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, userid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, registertime_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, lastlogin_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, level_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt64(7, silvercoins_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, goldcoins_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt32(9, thisLuckPool_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeInt32(10, nextLuckPool_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeInt32(11, luckOne_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeInt32(12, luckTwo_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeInt32(13, treasureWorth_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeInt32(14, thisDisciple_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        output.writeInt32(15, nextDisciple_);
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        output.writeInt32(16, discipleLucky_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, servertime_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, userid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, registertime_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, lastlogin_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, level_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, silvercoins_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, goldcoins_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, thisLuckPool_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, nextLuckPool_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(11, luckOne_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(12, luckTwo_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(13, treasureWorth_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(14, thisDisciple_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(15, nextDisciple_);
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(16, discipleLucky_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.oldmountain.dzm.message.BackStageFetchLucky.OPBackStageFetchLuckyRet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.oldmountain.dzm.message.BackStageFetchLucky.OPBackStageFetchLuckyRet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.oldmountain.dzm.message.BackStageFetchLucky.OPBackStageFetchLuckyRet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.oldmountain.dzm.message.BackStageFetchLucky.OPBackStageFetchLuckyRet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.oldmountain.dzm.message.BackStageFetchLucky.OPBackStageFetchLuckyRet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.oldmountain.dzm.message.BackStageFetchLucky.OPBackStageFetchLuckyRet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.oldmountain.dzm.message.BackStageFetchLucky.OPBackStageFetchLuckyRet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.oldmountain.dzm.message.BackStageFetchLucky.OPBackStageFetchLuckyRet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.oldmountain.dzm.message.BackStageFetchLucky.OPBackStageFetchLuckyRet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.oldmountain.dzm.message.BackStageFetchLucky.OPBackStageFetchLuckyRet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.oldmountain.dzm.message.BackStageFetchLucky.OPBackStageFetchLuckyRet prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code OPBackStageFetchLuckyRet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.oldmountain.dzm.message.BackStageFetchLucky.OPBackStageFetchLuckyRetOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.oldmountain.dzm.message.BackStageFetchLucky.internal_static_OPBackStageFetchLuckyRet_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.oldmountain.dzm.message.BackStageFetchLucky.internal_static_OPBackStageFetchLuckyRet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.oldmountain.dzm.message.BackStageFetchLucky.OPBackStageFetchLuckyRet.class, com.oldmountain.dzm.message.BackStageFetchLucky.OPBackStageFetchLuckyRet.Builder.class);
      }

      // Construct using com.oldmountain.dzm.message.BackStageFetchLucky.OPBackStageFetchLuckyRet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        servertime_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        userid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        registertime_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        lastlogin_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        level_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        silvercoins_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000040);
        goldcoins_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        thisLuckPool_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        nextLuckPool_ = 0;
        bitField0_ = (bitField0_ & ~0x00000200);
        luckOne_ = 0;
        bitField0_ = (bitField0_ & ~0x00000400);
        luckTwo_ = 0;
        bitField0_ = (bitField0_ & ~0x00000800);
        treasureWorth_ = 0;
        bitField0_ = (bitField0_ & ~0x00001000);
        thisDisciple_ = 0;
        bitField0_ = (bitField0_ & ~0x00002000);
        nextDisciple_ = 0;
        bitField0_ = (bitField0_ & ~0x00004000);
        discipleLucky_ = 0;
        bitField0_ = (bitField0_ & ~0x00008000);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.oldmountain.dzm.message.BackStageFetchLucky.internal_static_OPBackStageFetchLuckyRet_descriptor;
      }

      public com.oldmountain.dzm.message.BackStageFetchLucky.OPBackStageFetchLuckyRet getDefaultInstanceForType() {
        return com.oldmountain.dzm.message.BackStageFetchLucky.OPBackStageFetchLuckyRet.getDefaultInstance();
      }

      public com.oldmountain.dzm.message.BackStageFetchLucky.OPBackStageFetchLuckyRet build() {
        com.oldmountain.dzm.message.BackStageFetchLucky.OPBackStageFetchLuckyRet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.oldmountain.dzm.message.BackStageFetchLucky.OPBackStageFetchLuckyRet buildPartial() {
        com.oldmountain.dzm.message.BackStageFetchLucky.OPBackStageFetchLuckyRet result = new com.oldmountain.dzm.message.BackStageFetchLucky.OPBackStageFetchLuckyRet(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.servertime_ = servertime_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.userid_ = userid_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.registertime_ = registertime_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.lastlogin_ = lastlogin_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.level_ = level_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.silvercoins_ = silvercoins_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.goldcoins_ = goldcoins_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.thisLuckPool_ = thisLuckPool_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.nextLuckPool_ = nextLuckPool_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.luckOne_ = luckOne_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.luckTwo_ = luckTwo_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.treasureWorth_ = treasureWorth_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00002000;
        }
        result.thisDisciple_ = thisDisciple_;
        if (((from_bitField0_ & 0x00004000) == 0x00004000)) {
          to_bitField0_ |= 0x00004000;
        }
        result.nextDisciple_ = nextDisciple_;
        if (((from_bitField0_ & 0x00008000) == 0x00008000)) {
          to_bitField0_ |= 0x00008000;
        }
        result.discipleLucky_ = discipleLucky_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.oldmountain.dzm.message.BackStageFetchLucky.OPBackStageFetchLuckyRet) {
          return mergeFrom((com.oldmountain.dzm.message.BackStageFetchLucky.OPBackStageFetchLuckyRet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.oldmountain.dzm.message.BackStageFetchLucky.OPBackStageFetchLuckyRet other) {
        if (other == com.oldmountain.dzm.message.BackStageFetchLucky.OPBackStageFetchLuckyRet.getDefaultInstance()) return this;
        if (other.hasServertime()) {
          setServertime(other.getServertime());
        }
        if (other.hasUserid()) {
          setUserid(other.getUserid());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000004;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasRegistertime()) {
          setRegistertime(other.getRegistertime());
        }
        if (other.hasLastlogin()) {
          setLastlogin(other.getLastlogin());
        }
        if (other.hasLevel()) {
          setLevel(other.getLevel());
        }
        if (other.hasSilvercoins()) {
          setSilvercoins(other.getSilvercoins());
        }
        if (other.hasGoldcoins()) {
          setGoldcoins(other.getGoldcoins());
        }
        if (other.hasThisLuckPool()) {
          setThisLuckPool(other.getThisLuckPool());
        }
        if (other.hasNextLuckPool()) {
          setNextLuckPool(other.getNextLuckPool());
        }
        if (other.hasLuckOne()) {
          setLuckOne(other.getLuckOne());
        }
        if (other.hasLuckTwo()) {
          setLuckTwo(other.getLuckTwo());
        }
        if (other.hasTreasureWorth()) {
          setTreasureWorth(other.getTreasureWorth());
        }
        if (other.hasThisDisciple()) {
          setThisDisciple(other.getThisDisciple());
        }
        if (other.hasNextDisciple()) {
          setNextDisciple(other.getNextDisciple());
        }
        if (other.hasDiscipleLucky()) {
          setDiscipleLucky(other.getDiscipleLucky());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasServertime()) {
          
          return false;
        }
        if (!hasUserid()) {
          
          return false;
        }
        if (!hasName()) {
          
          return false;
        }
        if (!hasRegistertime()) {
          
          return false;
        }
        if (!hasLastlogin()) {
          
          return false;
        }
        if (!hasLevel()) {
          
          return false;
        }
        if (!hasSilvercoins()) {
          
          return false;
        }
        if (!hasGoldcoins()) {
          
          return false;
        }
        if (!hasThisLuckPool()) {
          
          return false;
        }
        if (!hasNextLuckPool()) {
          
          return false;
        }
        if (!hasLuckOne()) {
          
          return false;
        }
        if (!hasLuckTwo()) {
          
          return false;
        }
        if (!hasTreasureWorth()) {
          
          return false;
        }
        if (!hasThisDisciple()) {
          
          return false;
        }
        if (!hasNextDisciple()) {
          
          return false;
        }
        if (!hasDiscipleLucky()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.oldmountain.dzm.message.BackStageFetchLucky.OPBackStageFetchLuckyRet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.oldmountain.dzm.message.BackStageFetchLucky.OPBackStageFetchLuckyRet) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 servertime = 1;
      private int servertime_ ;
      /**
       * <code>required int32 servertime = 1;</code>
       */
      public boolean hasServertime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 servertime = 1;</code>
       */
      public int getServertime() {
        return servertime_;
      }
      /**
       * <code>required int32 servertime = 1;</code>
       */
      public Builder setServertime(int value) {
        bitField0_ |= 0x00000001;
        servertime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 servertime = 1;</code>
       */
      public Builder clearServertime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        servertime_ = 0;
        onChanged();
        return this;
      }

      // required int32 userid = 2;
      private int userid_ ;
      /**
       * <code>required int32 userid = 2;</code>
       */
      public boolean hasUserid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 userid = 2;</code>
       */
      public int getUserid() {
        return userid_;
      }
      /**
       * <code>required int32 userid = 2;</code>
       */
      public Builder setUserid(int value) {
        bitField0_ |= 0x00000002;
        userid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 userid = 2;</code>
       */
      public Builder clearUserid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        userid_ = 0;
        onChanged();
        return this;
      }

      // required string name = 3;
      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 3;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string name = 3;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 3;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 3;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 3;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        name_ = value;
        onChanged();
        return this;
      }

      // required int32 registertime = 4;
      private int registertime_ ;
      /**
       * <code>required int32 registertime = 4;</code>
       */
      public boolean hasRegistertime() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 registertime = 4;</code>
       */
      public int getRegistertime() {
        return registertime_;
      }
      /**
       * <code>required int32 registertime = 4;</code>
       */
      public Builder setRegistertime(int value) {
        bitField0_ |= 0x00000008;
        registertime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 registertime = 4;</code>
       */
      public Builder clearRegistertime() {
        bitField0_ = (bitField0_ & ~0x00000008);
        registertime_ = 0;
        onChanged();
        return this;
      }

      // required int32 lastlogin = 5;
      private int lastlogin_ ;
      /**
       * <code>required int32 lastlogin = 5;</code>
       */
      public boolean hasLastlogin() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int32 lastlogin = 5;</code>
       */
      public int getLastlogin() {
        return lastlogin_;
      }
      /**
       * <code>required int32 lastlogin = 5;</code>
       */
      public Builder setLastlogin(int value) {
        bitField0_ |= 0x00000010;
        lastlogin_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 lastlogin = 5;</code>
       */
      public Builder clearLastlogin() {
        bitField0_ = (bitField0_ & ~0x00000010);
        lastlogin_ = 0;
        onChanged();
        return this;
      }

      // required int32 level = 6;
      private int level_ ;
      /**
       * <code>required int32 level = 6;</code>
       */
      public boolean hasLevel() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required int32 level = 6;</code>
       */
      public int getLevel() {
        return level_;
      }
      /**
       * <code>required int32 level = 6;</code>
       */
      public Builder setLevel(int value) {
        bitField0_ |= 0x00000020;
        level_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 level = 6;</code>
       */
      public Builder clearLevel() {
        bitField0_ = (bitField0_ & ~0x00000020);
        level_ = 0;
        onChanged();
        return this;
      }

      // required int64 silvercoins = 7;
      private long silvercoins_ ;
      /**
       * <code>required int64 silvercoins = 7;</code>
       */
      public boolean hasSilvercoins() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required int64 silvercoins = 7;</code>
       */
      public long getSilvercoins() {
        return silvercoins_;
      }
      /**
       * <code>required int64 silvercoins = 7;</code>
       */
      public Builder setSilvercoins(long value) {
        bitField0_ |= 0x00000040;
        silvercoins_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 silvercoins = 7;</code>
       */
      public Builder clearSilvercoins() {
        bitField0_ = (bitField0_ & ~0x00000040);
        silvercoins_ = 0L;
        onChanged();
        return this;
      }

      // required int32 goldcoins = 8;
      private int goldcoins_ ;
      /**
       * <code>required int32 goldcoins = 8;</code>
       */
      public boolean hasGoldcoins() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>required int32 goldcoins = 8;</code>
       */
      public int getGoldcoins() {
        return goldcoins_;
      }
      /**
       * <code>required int32 goldcoins = 8;</code>
       */
      public Builder setGoldcoins(int value) {
        bitField0_ |= 0x00000080;
        goldcoins_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 goldcoins = 8;</code>
       */
      public Builder clearGoldcoins() {
        bitField0_ = (bitField0_ & ~0x00000080);
        goldcoins_ = 0;
        onChanged();
        return this;
      }

      // required int32 thisLuckPool = 9;
      private int thisLuckPool_ ;
      /**
       * <code>required int32 thisLuckPool = 9;</code>
       */
      public boolean hasThisLuckPool() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>required int32 thisLuckPool = 9;</code>
       */
      public int getThisLuckPool() {
        return thisLuckPool_;
      }
      /**
       * <code>required int32 thisLuckPool = 9;</code>
       */
      public Builder setThisLuckPool(int value) {
        bitField0_ |= 0x00000100;
        thisLuckPool_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 thisLuckPool = 9;</code>
       */
      public Builder clearThisLuckPool() {
        bitField0_ = (bitField0_ & ~0x00000100);
        thisLuckPool_ = 0;
        onChanged();
        return this;
      }

      // required int32 nextLuckPool = 10;
      private int nextLuckPool_ ;
      /**
       * <code>required int32 nextLuckPool = 10;</code>
       */
      public boolean hasNextLuckPool() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>required int32 nextLuckPool = 10;</code>
       */
      public int getNextLuckPool() {
        return nextLuckPool_;
      }
      /**
       * <code>required int32 nextLuckPool = 10;</code>
       */
      public Builder setNextLuckPool(int value) {
        bitField0_ |= 0x00000200;
        nextLuckPool_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 nextLuckPool = 10;</code>
       */
      public Builder clearNextLuckPool() {
        bitField0_ = (bitField0_ & ~0x00000200);
        nextLuckPool_ = 0;
        onChanged();
        return this;
      }

      // required int32 luckOne = 11;
      private int luckOne_ ;
      /**
       * <code>required int32 luckOne = 11;</code>
       */
      public boolean hasLuckOne() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>required int32 luckOne = 11;</code>
       */
      public int getLuckOne() {
        return luckOne_;
      }
      /**
       * <code>required int32 luckOne = 11;</code>
       */
      public Builder setLuckOne(int value) {
        bitField0_ |= 0x00000400;
        luckOne_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 luckOne = 11;</code>
       */
      public Builder clearLuckOne() {
        bitField0_ = (bitField0_ & ~0x00000400);
        luckOne_ = 0;
        onChanged();
        return this;
      }

      // required int32 luckTwo = 12;
      private int luckTwo_ ;
      /**
       * <code>required int32 luckTwo = 12;</code>
       */
      public boolean hasLuckTwo() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>required int32 luckTwo = 12;</code>
       */
      public int getLuckTwo() {
        return luckTwo_;
      }
      /**
       * <code>required int32 luckTwo = 12;</code>
       */
      public Builder setLuckTwo(int value) {
        bitField0_ |= 0x00000800;
        luckTwo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 luckTwo = 12;</code>
       */
      public Builder clearLuckTwo() {
        bitField0_ = (bitField0_ & ~0x00000800);
        luckTwo_ = 0;
        onChanged();
        return this;
      }

      // required int32 treasureWorth = 13;
      private int treasureWorth_ ;
      /**
       * <code>required int32 treasureWorth = 13;</code>
       */
      public boolean hasTreasureWorth() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <code>required int32 treasureWorth = 13;</code>
       */
      public int getTreasureWorth() {
        return treasureWorth_;
      }
      /**
       * <code>required int32 treasureWorth = 13;</code>
       */
      public Builder setTreasureWorth(int value) {
        bitField0_ |= 0x00001000;
        treasureWorth_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 treasureWorth = 13;</code>
       */
      public Builder clearTreasureWorth() {
        bitField0_ = (bitField0_ & ~0x00001000);
        treasureWorth_ = 0;
        onChanged();
        return this;
      }

      // required int32 thisDisciple = 14;
      private int thisDisciple_ ;
      /**
       * <code>required int32 thisDisciple = 14;</code>
       */
      public boolean hasThisDisciple() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      /**
       * <code>required int32 thisDisciple = 14;</code>
       */
      public int getThisDisciple() {
        return thisDisciple_;
      }
      /**
       * <code>required int32 thisDisciple = 14;</code>
       */
      public Builder setThisDisciple(int value) {
        bitField0_ |= 0x00002000;
        thisDisciple_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 thisDisciple = 14;</code>
       */
      public Builder clearThisDisciple() {
        bitField0_ = (bitField0_ & ~0x00002000);
        thisDisciple_ = 0;
        onChanged();
        return this;
      }

      // required int32 nextDisciple = 15;
      private int nextDisciple_ ;
      /**
       * <code>required int32 nextDisciple = 15;</code>
       */
      public boolean hasNextDisciple() {
        return ((bitField0_ & 0x00004000) == 0x00004000);
      }
      /**
       * <code>required int32 nextDisciple = 15;</code>
       */
      public int getNextDisciple() {
        return nextDisciple_;
      }
      /**
       * <code>required int32 nextDisciple = 15;</code>
       */
      public Builder setNextDisciple(int value) {
        bitField0_ |= 0x00004000;
        nextDisciple_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 nextDisciple = 15;</code>
       */
      public Builder clearNextDisciple() {
        bitField0_ = (bitField0_ & ~0x00004000);
        nextDisciple_ = 0;
        onChanged();
        return this;
      }

      // required int32 discipleLucky = 16;
      private int discipleLucky_ ;
      /**
       * <code>required int32 discipleLucky = 16;</code>
       */
      public boolean hasDiscipleLucky() {
        return ((bitField0_ & 0x00008000) == 0x00008000);
      }
      /**
       * <code>required int32 discipleLucky = 16;</code>
       */
      public int getDiscipleLucky() {
        return discipleLucky_;
      }
      /**
       * <code>required int32 discipleLucky = 16;</code>
       */
      public Builder setDiscipleLucky(int value) {
        bitField0_ |= 0x00008000;
        discipleLucky_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 discipleLucky = 16;</code>
       */
      public Builder clearDiscipleLucky() {
        bitField0_ = (bitField0_ & ~0x00008000);
        discipleLucky_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:OPBackStageFetchLuckyRet)
    }

    static {
      defaultInstance = new OPBackStageFetchLuckyRet(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:OPBackStageFetchLuckyRet)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_OPBackStageFetchLucky_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_OPBackStageFetchLucky_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_OPBackStageFetchLuckyRet_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_OPBackStageFetchLuckyRet_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031BackStageFetchLucky.proto\"9\n\025OPBackSta" +
      "geFetchLucky\022\022\n\007version\030\001 \002(\005:\0011\022\014\n\004name" +
      "\030\002 \002(\t\"\324\002\n\030OPBackStageFetchLuckyRet\022\022\n\ns" +
      "ervertime\030\001 \002(\005\022\016\n\006userid\030\002 \002(\005\022\014\n\004name\030" +
      "\003 \002(\t\022\024\n\014registertime\030\004 \002(\005\022\021\n\tlastlogin" +
      "\030\005 \002(\005\022\r\n\005level\030\006 \002(\005\022\023\n\013silvercoins\030\007 \002" +
      "(\003\022\021\n\tgoldcoins\030\010 \002(\005\022\024\n\014thisLuckPool\030\t " +
      "\002(\005\022\024\n\014nextLuckPool\030\n \002(\005\022\017\n\007luckOne\030\013 \002" +
      "(\005\022\017\n\007luckTwo\030\014 \002(\005\022\025\n\rtreasureWorth\030\r \002" +
      "(\005\022\024\n\014thisDisciple\030\016 \002(\005\022\024\n\014nextDisciple",
      "\030\017 \002(\005\022\025\n\rdiscipleLucky\030\020 \002(\005B\035\n\033com.old" +
      "mountain.dzm.message"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_OPBackStageFetchLucky_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_OPBackStageFetchLucky_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_OPBackStageFetchLucky_descriptor,
              new java.lang.String[] { "Version", "Name", });
          internal_static_OPBackStageFetchLuckyRet_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_OPBackStageFetchLuckyRet_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_OPBackStageFetchLuckyRet_descriptor,
              new java.lang.String[] { "Servertime", "Userid", "Name", "Registertime", "Lastlogin", "Level", "Silvercoins", "Goldcoins", "ThisLuckPool", "NextLuckPool", "LuckOne", "LuckTwo", "TreasureWorth", "ThisDisciple", "NextDisciple", "DiscipleLucky", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
