// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FightEndAddYestAttr.proto

package com.oldmountain.dzm.message;

public final class FightEndAddYestAttr {
  private FightEndAddYestAttr() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface OPFightEndAddYestAttrOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 version = 1 [default = 1];
    /**
     * <code>required int32 version = 1 [default = 1];</code>
     */
    boolean hasVersion();
    /**
     * <code>required int32 version = 1 [default = 1];</code>
     */
    int getVersion();

    // required int32 id = 2;
    /**
     * <code>required int32 id = 2;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 2;</code>
     */
    int getId();
  }
  /**
   * Protobuf type {@code OPFightEndAddYestAttr}
   */
  public static final class OPFightEndAddYestAttr extends
      com.google.protobuf.GeneratedMessage
      implements OPFightEndAddYestAttrOrBuilder {
    // Use OPFightEndAddYestAttr.newBuilder() to construct.
    private OPFightEndAddYestAttr(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private OPFightEndAddYestAttr(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final OPFightEndAddYestAttr defaultInstance;
    public static OPFightEndAddYestAttr getDefaultInstance() {
      return defaultInstance;
    }

    public OPFightEndAddYestAttr getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private OPFightEndAddYestAttr(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              version_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              id_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.oldmountain.dzm.message.FightEndAddYestAttr.internal_static_OPFightEndAddYestAttr_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.oldmountain.dzm.message.FightEndAddYestAttr.internal_static_OPFightEndAddYestAttr_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.oldmountain.dzm.message.FightEndAddYestAttr.OPFightEndAddYestAttr.class, com.oldmountain.dzm.message.FightEndAddYestAttr.OPFightEndAddYestAttr.Builder.class);
    }

    public static com.google.protobuf.Parser<OPFightEndAddYestAttr> PARSER =
        new com.google.protobuf.AbstractParser<OPFightEndAddYestAttr>() {
      public OPFightEndAddYestAttr parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OPFightEndAddYestAttr(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<OPFightEndAddYestAttr> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 version = 1 [default = 1];
    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    /**
     * <code>required int32 version = 1 [default = 1];</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 version = 1 [default = 1];</code>
     */
    public int getVersion() {
      return version_;
    }

    // required int32 id = 2;
    public static final int ID_FIELD_NUMBER = 2;
    private int id_;
    /**
     * <code>required int32 id = 2;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 id = 2;</code>
     */
    public int getId() {
      return id_;
    }

    private void initFields() {
      version_ = 1;
      id_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, id_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, id_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.oldmountain.dzm.message.FightEndAddYestAttr.OPFightEndAddYestAttr parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.oldmountain.dzm.message.FightEndAddYestAttr.OPFightEndAddYestAttr parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.oldmountain.dzm.message.FightEndAddYestAttr.OPFightEndAddYestAttr parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.oldmountain.dzm.message.FightEndAddYestAttr.OPFightEndAddYestAttr parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.oldmountain.dzm.message.FightEndAddYestAttr.OPFightEndAddYestAttr parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.oldmountain.dzm.message.FightEndAddYestAttr.OPFightEndAddYestAttr parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.oldmountain.dzm.message.FightEndAddYestAttr.OPFightEndAddYestAttr parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.oldmountain.dzm.message.FightEndAddYestAttr.OPFightEndAddYestAttr parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.oldmountain.dzm.message.FightEndAddYestAttr.OPFightEndAddYestAttr parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.oldmountain.dzm.message.FightEndAddYestAttr.OPFightEndAddYestAttr parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.oldmountain.dzm.message.FightEndAddYestAttr.OPFightEndAddYestAttr prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code OPFightEndAddYestAttr}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.oldmountain.dzm.message.FightEndAddYestAttr.OPFightEndAddYestAttrOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.oldmountain.dzm.message.FightEndAddYestAttr.internal_static_OPFightEndAddYestAttr_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.oldmountain.dzm.message.FightEndAddYestAttr.internal_static_OPFightEndAddYestAttr_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.oldmountain.dzm.message.FightEndAddYestAttr.OPFightEndAddYestAttr.class, com.oldmountain.dzm.message.FightEndAddYestAttr.OPFightEndAddYestAttr.Builder.class);
      }

      // Construct using com.oldmountain.dzm.message.FightEndAddYestAttr.OPFightEndAddYestAttr.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        version_ = 1;
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.oldmountain.dzm.message.FightEndAddYestAttr.internal_static_OPFightEndAddYestAttr_descriptor;
      }

      public com.oldmountain.dzm.message.FightEndAddYestAttr.OPFightEndAddYestAttr getDefaultInstanceForType() {
        return com.oldmountain.dzm.message.FightEndAddYestAttr.OPFightEndAddYestAttr.getDefaultInstance();
      }

      public com.oldmountain.dzm.message.FightEndAddYestAttr.OPFightEndAddYestAttr build() {
        com.oldmountain.dzm.message.FightEndAddYestAttr.OPFightEndAddYestAttr result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.oldmountain.dzm.message.FightEndAddYestAttr.OPFightEndAddYestAttr buildPartial() {
        com.oldmountain.dzm.message.FightEndAddYestAttr.OPFightEndAddYestAttr result = new com.oldmountain.dzm.message.FightEndAddYestAttr.OPFightEndAddYestAttr(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.id_ = id_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.oldmountain.dzm.message.FightEndAddYestAttr.OPFightEndAddYestAttr) {
          return mergeFrom((com.oldmountain.dzm.message.FightEndAddYestAttr.OPFightEndAddYestAttr)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.oldmountain.dzm.message.FightEndAddYestAttr.OPFightEndAddYestAttr other) {
        if (other == com.oldmountain.dzm.message.FightEndAddYestAttr.OPFightEndAddYestAttr.getDefaultInstance()) return this;
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasVersion()) {
          
          return false;
        }
        if (!hasId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.oldmountain.dzm.message.FightEndAddYestAttr.OPFightEndAddYestAttr parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.oldmountain.dzm.message.FightEndAddYestAttr.OPFightEndAddYestAttr) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 version = 1 [default = 1];
      private int version_ = 1;
      /**
       * <code>required int32 version = 1 [default = 1];</code>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 version = 1 [default = 1];</code>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <code>required int32 version = 1 [default = 1];</code>
       */
      public Builder setVersion(int value) {
        bitField0_ |= 0x00000001;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 version = 1 [default = 1];</code>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = 1;
        onChanged();
        return this;
      }

      // required int32 id = 2;
      private int id_ ;
      /**
       * <code>required int32 id = 2;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 id = 2;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 2;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 2;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:OPFightEndAddYestAttr)
    }

    static {
      defaultInstance = new OPFightEndAddYestAttr(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:OPFightEndAddYestAttr)
  }

  public interface OPFightEndAddYestAttrRetOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .OPFightEndInfoRet fightEndInfo = 1;
    /**
     * <code>required .OPFightEndInfoRet fightEndInfo = 1;</code>
     */
    boolean hasFightEndInfo();
    /**
     * <code>required .OPFightEndInfoRet fightEndInfo = 1;</code>
     */
    com.oldmountain.dzm.message.FightEndInfo.OPFightEndInfoRet getFightEndInfo();
    /**
     * <code>required .OPFightEndInfoRet fightEndInfo = 1;</code>
     */
    com.oldmountain.dzm.message.FightEndInfo.OPFightEndInfoRetOrBuilder getFightEndInfoOrBuilder();

    // required int32 servertime = 2;
    /**
     * <code>required int32 servertime = 2;</code>
     */
    boolean hasServertime();
    /**
     * <code>required int32 servertime = 2;</code>
     */
    int getServertime();

    // required int32 status = 3;
    /**
     * <code>required int32 status = 3;</code>
     */
    boolean hasStatus();
    /**
     * <code>required int32 status = 3;</code>
     */
    int getStatus();
  }
  /**
   * Protobuf type {@code OPFightEndAddYestAttrRet}
   */
  public static final class OPFightEndAddYestAttrRet extends
      com.google.protobuf.GeneratedMessage
      implements OPFightEndAddYestAttrRetOrBuilder {
    // Use OPFightEndAddYestAttrRet.newBuilder() to construct.
    private OPFightEndAddYestAttrRet(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private OPFightEndAddYestAttrRet(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final OPFightEndAddYestAttrRet defaultInstance;
    public static OPFightEndAddYestAttrRet getDefaultInstance() {
      return defaultInstance;
    }

    public OPFightEndAddYestAttrRet getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private OPFightEndAddYestAttrRet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.oldmountain.dzm.message.FightEndInfo.OPFightEndInfoRet.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = fightEndInfo_.toBuilder();
              }
              fightEndInfo_ = input.readMessage(com.oldmountain.dzm.message.FightEndInfo.OPFightEndInfoRet.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(fightEndInfo_);
                fightEndInfo_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              servertime_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              status_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.oldmountain.dzm.message.FightEndAddYestAttr.internal_static_OPFightEndAddYestAttrRet_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.oldmountain.dzm.message.FightEndAddYestAttr.internal_static_OPFightEndAddYestAttrRet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.oldmountain.dzm.message.FightEndAddYestAttr.OPFightEndAddYestAttrRet.class, com.oldmountain.dzm.message.FightEndAddYestAttr.OPFightEndAddYestAttrRet.Builder.class);
    }

    public static com.google.protobuf.Parser<OPFightEndAddYestAttrRet> PARSER =
        new com.google.protobuf.AbstractParser<OPFightEndAddYestAttrRet>() {
      public OPFightEndAddYestAttrRet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OPFightEndAddYestAttrRet(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<OPFightEndAddYestAttrRet> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .OPFightEndInfoRet fightEndInfo = 1;
    public static final int FIGHTENDINFO_FIELD_NUMBER = 1;
    private com.oldmountain.dzm.message.FightEndInfo.OPFightEndInfoRet fightEndInfo_;
    /**
     * <code>required .OPFightEndInfoRet fightEndInfo = 1;</code>
     */
    public boolean hasFightEndInfo() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .OPFightEndInfoRet fightEndInfo = 1;</code>
     */
    public com.oldmountain.dzm.message.FightEndInfo.OPFightEndInfoRet getFightEndInfo() {
      return fightEndInfo_;
    }
    /**
     * <code>required .OPFightEndInfoRet fightEndInfo = 1;</code>
     */
    public com.oldmountain.dzm.message.FightEndInfo.OPFightEndInfoRetOrBuilder getFightEndInfoOrBuilder() {
      return fightEndInfo_;
    }

    // required int32 servertime = 2;
    public static final int SERVERTIME_FIELD_NUMBER = 2;
    private int servertime_;
    /**
     * <code>required int32 servertime = 2;</code>
     */
    public boolean hasServertime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 servertime = 2;</code>
     */
    public int getServertime() {
      return servertime_;
    }

    // required int32 status = 3;
    public static final int STATUS_FIELD_NUMBER = 3;
    private int status_;
    /**
     * <code>required int32 status = 3;</code>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 status = 3;</code>
     */
    public int getStatus() {
      return status_;
    }

    private void initFields() {
      fightEndInfo_ = com.oldmountain.dzm.message.FightEndInfo.OPFightEndInfoRet.getDefaultInstance();
      servertime_ = 0;
      status_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasFightEndInfo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasServertime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getFightEndInfo().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, fightEndInfo_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, servertime_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, status_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, fightEndInfo_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, servertime_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, status_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.oldmountain.dzm.message.FightEndAddYestAttr.OPFightEndAddYestAttrRet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.oldmountain.dzm.message.FightEndAddYestAttr.OPFightEndAddYestAttrRet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.oldmountain.dzm.message.FightEndAddYestAttr.OPFightEndAddYestAttrRet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.oldmountain.dzm.message.FightEndAddYestAttr.OPFightEndAddYestAttrRet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.oldmountain.dzm.message.FightEndAddYestAttr.OPFightEndAddYestAttrRet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.oldmountain.dzm.message.FightEndAddYestAttr.OPFightEndAddYestAttrRet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.oldmountain.dzm.message.FightEndAddYestAttr.OPFightEndAddYestAttrRet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.oldmountain.dzm.message.FightEndAddYestAttr.OPFightEndAddYestAttrRet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.oldmountain.dzm.message.FightEndAddYestAttr.OPFightEndAddYestAttrRet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.oldmountain.dzm.message.FightEndAddYestAttr.OPFightEndAddYestAttrRet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.oldmountain.dzm.message.FightEndAddYestAttr.OPFightEndAddYestAttrRet prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code OPFightEndAddYestAttrRet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.oldmountain.dzm.message.FightEndAddYestAttr.OPFightEndAddYestAttrRetOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.oldmountain.dzm.message.FightEndAddYestAttr.internal_static_OPFightEndAddYestAttrRet_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.oldmountain.dzm.message.FightEndAddYestAttr.internal_static_OPFightEndAddYestAttrRet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.oldmountain.dzm.message.FightEndAddYestAttr.OPFightEndAddYestAttrRet.class, com.oldmountain.dzm.message.FightEndAddYestAttr.OPFightEndAddYestAttrRet.Builder.class);
      }

      // Construct using com.oldmountain.dzm.message.FightEndAddYestAttr.OPFightEndAddYestAttrRet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getFightEndInfoFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (fightEndInfoBuilder_ == null) {
          fightEndInfo_ = com.oldmountain.dzm.message.FightEndInfo.OPFightEndInfoRet.getDefaultInstance();
        } else {
          fightEndInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        servertime_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        status_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.oldmountain.dzm.message.FightEndAddYestAttr.internal_static_OPFightEndAddYestAttrRet_descriptor;
      }

      public com.oldmountain.dzm.message.FightEndAddYestAttr.OPFightEndAddYestAttrRet getDefaultInstanceForType() {
        return com.oldmountain.dzm.message.FightEndAddYestAttr.OPFightEndAddYestAttrRet.getDefaultInstance();
      }

      public com.oldmountain.dzm.message.FightEndAddYestAttr.OPFightEndAddYestAttrRet build() {
        com.oldmountain.dzm.message.FightEndAddYestAttr.OPFightEndAddYestAttrRet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.oldmountain.dzm.message.FightEndAddYestAttr.OPFightEndAddYestAttrRet buildPartial() {
        com.oldmountain.dzm.message.FightEndAddYestAttr.OPFightEndAddYestAttrRet result = new com.oldmountain.dzm.message.FightEndAddYestAttr.OPFightEndAddYestAttrRet(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (fightEndInfoBuilder_ == null) {
          result.fightEndInfo_ = fightEndInfo_;
        } else {
          result.fightEndInfo_ = fightEndInfoBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.servertime_ = servertime_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.status_ = status_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.oldmountain.dzm.message.FightEndAddYestAttr.OPFightEndAddYestAttrRet) {
          return mergeFrom((com.oldmountain.dzm.message.FightEndAddYestAttr.OPFightEndAddYestAttrRet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.oldmountain.dzm.message.FightEndAddYestAttr.OPFightEndAddYestAttrRet other) {
        if (other == com.oldmountain.dzm.message.FightEndAddYestAttr.OPFightEndAddYestAttrRet.getDefaultInstance()) return this;
        if (other.hasFightEndInfo()) {
          mergeFightEndInfo(other.getFightEndInfo());
        }
        if (other.hasServertime()) {
          setServertime(other.getServertime());
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasFightEndInfo()) {
          
          return false;
        }
        if (!hasServertime()) {
          
          return false;
        }
        if (!hasStatus()) {
          
          return false;
        }
        if (!getFightEndInfo().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.oldmountain.dzm.message.FightEndAddYestAttr.OPFightEndAddYestAttrRet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.oldmountain.dzm.message.FightEndAddYestAttr.OPFightEndAddYestAttrRet) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .OPFightEndInfoRet fightEndInfo = 1;
      private com.oldmountain.dzm.message.FightEndInfo.OPFightEndInfoRet fightEndInfo_ = com.oldmountain.dzm.message.FightEndInfo.OPFightEndInfoRet.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.oldmountain.dzm.message.FightEndInfo.OPFightEndInfoRet, com.oldmountain.dzm.message.FightEndInfo.OPFightEndInfoRet.Builder, com.oldmountain.dzm.message.FightEndInfo.OPFightEndInfoRetOrBuilder> fightEndInfoBuilder_;
      /**
       * <code>required .OPFightEndInfoRet fightEndInfo = 1;</code>
       */
      public boolean hasFightEndInfo() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .OPFightEndInfoRet fightEndInfo = 1;</code>
       */
      public com.oldmountain.dzm.message.FightEndInfo.OPFightEndInfoRet getFightEndInfo() {
        if (fightEndInfoBuilder_ == null) {
          return fightEndInfo_;
        } else {
          return fightEndInfoBuilder_.getMessage();
        }
      }
      /**
       * <code>required .OPFightEndInfoRet fightEndInfo = 1;</code>
       */
      public Builder setFightEndInfo(com.oldmountain.dzm.message.FightEndInfo.OPFightEndInfoRet value) {
        if (fightEndInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          fightEndInfo_ = value;
          onChanged();
        } else {
          fightEndInfoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .OPFightEndInfoRet fightEndInfo = 1;</code>
       */
      public Builder setFightEndInfo(
          com.oldmountain.dzm.message.FightEndInfo.OPFightEndInfoRet.Builder builderForValue) {
        if (fightEndInfoBuilder_ == null) {
          fightEndInfo_ = builderForValue.build();
          onChanged();
        } else {
          fightEndInfoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .OPFightEndInfoRet fightEndInfo = 1;</code>
       */
      public Builder mergeFightEndInfo(com.oldmountain.dzm.message.FightEndInfo.OPFightEndInfoRet value) {
        if (fightEndInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              fightEndInfo_ != com.oldmountain.dzm.message.FightEndInfo.OPFightEndInfoRet.getDefaultInstance()) {
            fightEndInfo_ =
              com.oldmountain.dzm.message.FightEndInfo.OPFightEndInfoRet.newBuilder(fightEndInfo_).mergeFrom(value).buildPartial();
          } else {
            fightEndInfo_ = value;
          }
          onChanged();
        } else {
          fightEndInfoBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .OPFightEndInfoRet fightEndInfo = 1;</code>
       */
      public Builder clearFightEndInfo() {
        if (fightEndInfoBuilder_ == null) {
          fightEndInfo_ = com.oldmountain.dzm.message.FightEndInfo.OPFightEndInfoRet.getDefaultInstance();
          onChanged();
        } else {
          fightEndInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .OPFightEndInfoRet fightEndInfo = 1;</code>
       */
      public com.oldmountain.dzm.message.FightEndInfo.OPFightEndInfoRet.Builder getFightEndInfoBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getFightEndInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>required .OPFightEndInfoRet fightEndInfo = 1;</code>
       */
      public com.oldmountain.dzm.message.FightEndInfo.OPFightEndInfoRetOrBuilder getFightEndInfoOrBuilder() {
        if (fightEndInfoBuilder_ != null) {
          return fightEndInfoBuilder_.getMessageOrBuilder();
        } else {
          return fightEndInfo_;
        }
      }
      /**
       * <code>required .OPFightEndInfoRet fightEndInfo = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.oldmountain.dzm.message.FightEndInfo.OPFightEndInfoRet, com.oldmountain.dzm.message.FightEndInfo.OPFightEndInfoRet.Builder, com.oldmountain.dzm.message.FightEndInfo.OPFightEndInfoRetOrBuilder> 
          getFightEndInfoFieldBuilder() {
        if (fightEndInfoBuilder_ == null) {
          fightEndInfoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.oldmountain.dzm.message.FightEndInfo.OPFightEndInfoRet, com.oldmountain.dzm.message.FightEndInfo.OPFightEndInfoRet.Builder, com.oldmountain.dzm.message.FightEndInfo.OPFightEndInfoRetOrBuilder>(
                  fightEndInfo_,
                  getParentForChildren(),
                  isClean());
          fightEndInfo_ = null;
        }
        return fightEndInfoBuilder_;
      }

      // required int32 servertime = 2;
      private int servertime_ ;
      /**
       * <code>required int32 servertime = 2;</code>
       */
      public boolean hasServertime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 servertime = 2;</code>
       */
      public int getServertime() {
        return servertime_;
      }
      /**
       * <code>required int32 servertime = 2;</code>
       */
      public Builder setServertime(int value) {
        bitField0_ |= 0x00000002;
        servertime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 servertime = 2;</code>
       */
      public Builder clearServertime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        servertime_ = 0;
        onChanged();
        return this;
      }

      // required int32 status = 3;
      private int status_ ;
      /**
       * <code>required int32 status = 3;</code>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 status = 3;</code>
       */
      public int getStatus() {
        return status_;
      }
      /**
       * <code>required int32 status = 3;</code>
       */
      public Builder setStatus(int value) {
        bitField0_ |= 0x00000004;
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 status = 3;</code>
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000004);
        status_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:OPFightEndAddYestAttrRet)
    }

    static {
      defaultInstance = new OPFightEndAddYestAttrRet(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:OPFightEndAddYestAttrRet)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_OPFightEndAddYestAttr_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_OPFightEndAddYestAttr_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_OPFightEndAddYestAttrRet_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_OPFightEndAddYestAttrRet_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031FightEndAddYestAttr.proto\032\022FightEndInf" +
      "o.proto\"7\n\025OPFightEndAddYestAttr\022\022\n\007vers" +
      "ion\030\001 \002(\005:\0011\022\n\n\002id\030\002 \002(\005\"h\n\030OPFightEndAd" +
      "dYestAttrRet\022(\n\014fightEndInfo\030\001 \002(\0132\022.OPF" +
      "ightEndInfoRet\022\022\n\nservertime\030\002 \002(\005\022\016\n\006st" +
      "atus\030\003 \002(\005B\035\n\033com.oldmountain.dzm.messag" +
      "e"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_OPFightEndAddYestAttr_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_OPFightEndAddYestAttr_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_OPFightEndAddYestAttr_descriptor,
              new java.lang.String[] { "Version", "Id", });
          internal_static_OPFightEndAddYestAttrRet_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_OPFightEndAddYestAttrRet_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_OPFightEndAddYestAttrRet_descriptor,
              new java.lang.String[] { "FightEndInfo", "Servertime", "Status", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.oldmountain.dzm.message.FightEndInfo.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
