// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recharge.proto

package com.oldmountain.dzm.message;

public final class Recharge {
  private Recharge() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface OPRechargeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string ConsumeStreamId = 1;
    /**
     * <code>required string ConsumeStreamId = 1;</code>
     */
    boolean hasConsumeStreamId();
    /**
     * <code>required string ConsumeStreamId = 1;</code>
     */
    java.lang.String getConsumeStreamId();
    /**
     * <code>required string ConsumeStreamId = 1;</code>
     */
    com.google.protobuf.ByteString
        getConsumeStreamIdBytes();

    // required string CooOrderSerial = 2;
    /**
     * <code>required string CooOrderSerial = 2;</code>
     */
    boolean hasCooOrderSerial();
    /**
     * <code>required string CooOrderSerial = 2;</code>
     */
    java.lang.String getCooOrderSerial();
    /**
     * <code>required string CooOrderSerial = 2;</code>
     */
    com.google.protobuf.ByteString
        getCooOrderSerialBytes();

    // required string Uin = 3;
    /**
     * <code>required string Uin = 3;</code>
     */
    boolean hasUin();
    /**
     * <code>required string Uin = 3;</code>
     */
    java.lang.String getUin();
    /**
     * <code>required string Uin = 3;</code>
     */
    com.google.protobuf.ByteString
        getUinBytes();

    // required string GoodsId = 4;
    /**
     * <code>required string GoodsId = 4;</code>
     */
    boolean hasGoodsId();
    /**
     * <code>required string GoodsId = 4;</code>
     */
    java.lang.String getGoodsId();
    /**
     * <code>required string GoodsId = 4;</code>
     */
    com.google.protobuf.ByteString
        getGoodsIdBytes();

    // required int32 GoodsCount = 5;
    /**
     * <code>required int32 GoodsCount = 5;</code>
     */
    boolean hasGoodsCount();
    /**
     * <code>required int32 GoodsCount = 5;</code>
     */
    int getGoodsCount();

    // required string CreateTime = 6;
    /**
     * <code>required string CreateTime = 6;</code>
     */
    boolean hasCreateTime();
    /**
     * <code>required string CreateTime = 6;</code>
     */
    java.lang.String getCreateTime();
    /**
     * <code>required string CreateTime = 6;</code>
     */
    com.google.protobuf.ByteString
        getCreateTimeBytes();

    // optional string Platform = 7;
    /**
     * <code>optional string Platform = 7;</code>
     */
    boolean hasPlatform();
    /**
     * <code>optional string Platform = 7;</code>
     */
    java.lang.String getPlatform();
    /**
     * <code>optional string Platform = 7;</code>
     */
    com.google.protobuf.ByteString
        getPlatformBytes();
  }
  /**
   * Protobuf type {@code OPRecharge}
   */
  public static final class OPRecharge extends
      com.google.protobuf.GeneratedMessage
      implements OPRechargeOrBuilder {
    // Use OPRecharge.newBuilder() to construct.
    private OPRecharge(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private OPRecharge(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final OPRecharge defaultInstance;
    public static OPRecharge getDefaultInstance() {
      return defaultInstance;
    }

    public OPRecharge getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private OPRecharge(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              consumeStreamId_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              cooOrderSerial_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              uin_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              goodsId_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              goodsCount_ = input.readInt32();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              createTime_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              platform_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.oldmountain.dzm.message.Recharge.internal_static_OPRecharge_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.oldmountain.dzm.message.Recharge.internal_static_OPRecharge_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.oldmountain.dzm.message.Recharge.OPRecharge.class, com.oldmountain.dzm.message.Recharge.OPRecharge.Builder.class);
    }

    public static com.google.protobuf.Parser<OPRecharge> PARSER =
        new com.google.protobuf.AbstractParser<OPRecharge>() {
      public OPRecharge parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OPRecharge(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<OPRecharge> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string ConsumeStreamId = 1;
    public static final int CONSUMESTREAMID_FIELD_NUMBER = 1;
    private java.lang.Object consumeStreamId_;
    /**
     * <code>required string ConsumeStreamId = 1;</code>
     */
    public boolean hasConsumeStreamId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string ConsumeStreamId = 1;</code>
     */
    public java.lang.String getConsumeStreamId() {
      java.lang.Object ref = consumeStreamId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          consumeStreamId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string ConsumeStreamId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getConsumeStreamIdBytes() {
      java.lang.Object ref = consumeStreamId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        consumeStreamId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string CooOrderSerial = 2;
    public static final int COOORDERSERIAL_FIELD_NUMBER = 2;
    private java.lang.Object cooOrderSerial_;
    /**
     * <code>required string CooOrderSerial = 2;</code>
     */
    public boolean hasCooOrderSerial() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string CooOrderSerial = 2;</code>
     */
    public java.lang.String getCooOrderSerial() {
      java.lang.Object ref = cooOrderSerial_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          cooOrderSerial_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string CooOrderSerial = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCooOrderSerialBytes() {
      java.lang.Object ref = cooOrderSerial_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cooOrderSerial_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string Uin = 3;
    public static final int UIN_FIELD_NUMBER = 3;
    private java.lang.Object uin_;
    /**
     * <code>required string Uin = 3;</code>
     */
    public boolean hasUin() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string Uin = 3;</code>
     */
    public java.lang.String getUin() {
      java.lang.Object ref = uin_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          uin_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string Uin = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUinBytes() {
      java.lang.Object ref = uin_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uin_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string GoodsId = 4;
    public static final int GOODSID_FIELD_NUMBER = 4;
    private java.lang.Object goodsId_;
    /**
     * <code>required string GoodsId = 4;</code>
     */
    public boolean hasGoodsId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string GoodsId = 4;</code>
     */
    public java.lang.String getGoodsId() {
      java.lang.Object ref = goodsId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          goodsId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string GoodsId = 4;</code>
     */
    public com.google.protobuf.ByteString
        getGoodsIdBytes() {
      java.lang.Object ref = goodsId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        goodsId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 GoodsCount = 5;
    public static final int GOODSCOUNT_FIELD_NUMBER = 5;
    private int goodsCount_;
    /**
     * <code>required int32 GoodsCount = 5;</code>
     */
    public boolean hasGoodsCount() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 GoodsCount = 5;</code>
     */
    public int getGoodsCount() {
      return goodsCount_;
    }

    // required string CreateTime = 6;
    public static final int CREATETIME_FIELD_NUMBER = 6;
    private java.lang.Object createTime_;
    /**
     * <code>required string CreateTime = 6;</code>
     */
    public boolean hasCreateTime() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required string CreateTime = 6;</code>
     */
    public java.lang.String getCreateTime() {
      java.lang.Object ref = createTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          createTime_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string CreateTime = 6;</code>
     */
    public com.google.protobuf.ByteString
        getCreateTimeBytes() {
      java.lang.Object ref = createTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        createTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string Platform = 7;
    public static final int PLATFORM_FIELD_NUMBER = 7;
    private java.lang.Object platform_;
    /**
     * <code>optional string Platform = 7;</code>
     */
    public boolean hasPlatform() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string Platform = 7;</code>
     */
    public java.lang.String getPlatform() {
      java.lang.Object ref = platform_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          platform_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string Platform = 7;</code>
     */
    public com.google.protobuf.ByteString
        getPlatformBytes() {
      java.lang.Object ref = platform_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        platform_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      consumeStreamId_ = "";
      cooOrderSerial_ = "";
      uin_ = "";
      goodsId_ = "";
      goodsCount_ = 0;
      createTime_ = "";
      platform_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasConsumeStreamId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCooOrderSerial()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUin()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasGoodsId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasGoodsCount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCreateTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getConsumeStreamIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getCooOrderSerialBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getUinBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getGoodsIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, goodsCount_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getCreateTimeBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getPlatformBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getConsumeStreamIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getCooOrderSerialBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getUinBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getGoodsIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, goodsCount_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getCreateTimeBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getPlatformBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.oldmountain.dzm.message.Recharge.OPRecharge parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.oldmountain.dzm.message.Recharge.OPRecharge parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.oldmountain.dzm.message.Recharge.OPRecharge parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.oldmountain.dzm.message.Recharge.OPRecharge parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.oldmountain.dzm.message.Recharge.OPRecharge parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.oldmountain.dzm.message.Recharge.OPRecharge parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.oldmountain.dzm.message.Recharge.OPRecharge parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.oldmountain.dzm.message.Recharge.OPRecharge parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.oldmountain.dzm.message.Recharge.OPRecharge parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.oldmountain.dzm.message.Recharge.OPRecharge parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.oldmountain.dzm.message.Recharge.OPRecharge prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code OPRecharge}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.oldmountain.dzm.message.Recharge.OPRechargeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.oldmountain.dzm.message.Recharge.internal_static_OPRecharge_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.oldmountain.dzm.message.Recharge.internal_static_OPRecharge_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.oldmountain.dzm.message.Recharge.OPRecharge.class, com.oldmountain.dzm.message.Recharge.OPRecharge.Builder.class);
      }

      // Construct using com.oldmountain.dzm.message.Recharge.OPRecharge.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        consumeStreamId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        cooOrderSerial_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        uin_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        goodsId_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        goodsCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        createTime_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        platform_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.oldmountain.dzm.message.Recharge.internal_static_OPRecharge_descriptor;
      }

      public com.oldmountain.dzm.message.Recharge.OPRecharge getDefaultInstanceForType() {
        return com.oldmountain.dzm.message.Recharge.OPRecharge.getDefaultInstance();
      }

      public com.oldmountain.dzm.message.Recharge.OPRecharge build() {
        com.oldmountain.dzm.message.Recharge.OPRecharge result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.oldmountain.dzm.message.Recharge.OPRecharge buildPartial() {
        com.oldmountain.dzm.message.Recharge.OPRecharge result = new com.oldmountain.dzm.message.Recharge.OPRecharge(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.consumeStreamId_ = consumeStreamId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.cooOrderSerial_ = cooOrderSerial_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.uin_ = uin_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.goodsId_ = goodsId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.goodsCount_ = goodsCount_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.createTime_ = createTime_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.platform_ = platform_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.oldmountain.dzm.message.Recharge.OPRecharge) {
          return mergeFrom((com.oldmountain.dzm.message.Recharge.OPRecharge)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.oldmountain.dzm.message.Recharge.OPRecharge other) {
        if (other == com.oldmountain.dzm.message.Recharge.OPRecharge.getDefaultInstance()) return this;
        if (other.hasConsumeStreamId()) {
          bitField0_ |= 0x00000001;
          consumeStreamId_ = other.consumeStreamId_;
          onChanged();
        }
        if (other.hasCooOrderSerial()) {
          bitField0_ |= 0x00000002;
          cooOrderSerial_ = other.cooOrderSerial_;
          onChanged();
        }
        if (other.hasUin()) {
          bitField0_ |= 0x00000004;
          uin_ = other.uin_;
          onChanged();
        }
        if (other.hasGoodsId()) {
          bitField0_ |= 0x00000008;
          goodsId_ = other.goodsId_;
          onChanged();
        }
        if (other.hasGoodsCount()) {
          setGoodsCount(other.getGoodsCount());
        }
        if (other.hasCreateTime()) {
          bitField0_ |= 0x00000020;
          createTime_ = other.createTime_;
          onChanged();
        }
        if (other.hasPlatform()) {
          bitField0_ |= 0x00000040;
          platform_ = other.platform_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasConsumeStreamId()) {
          
          return false;
        }
        if (!hasCooOrderSerial()) {
          
          return false;
        }
        if (!hasUin()) {
          
          return false;
        }
        if (!hasGoodsId()) {
          
          return false;
        }
        if (!hasGoodsCount()) {
          
          return false;
        }
        if (!hasCreateTime()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.oldmountain.dzm.message.Recharge.OPRecharge parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.oldmountain.dzm.message.Recharge.OPRecharge) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string ConsumeStreamId = 1;
      private java.lang.Object consumeStreamId_ = "";
      /**
       * <code>required string ConsumeStreamId = 1;</code>
       */
      public boolean hasConsumeStreamId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string ConsumeStreamId = 1;</code>
       */
      public java.lang.String getConsumeStreamId() {
        java.lang.Object ref = consumeStreamId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          consumeStreamId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string ConsumeStreamId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getConsumeStreamIdBytes() {
        java.lang.Object ref = consumeStreamId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          consumeStreamId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string ConsumeStreamId = 1;</code>
       */
      public Builder setConsumeStreamId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        consumeStreamId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string ConsumeStreamId = 1;</code>
       */
      public Builder clearConsumeStreamId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        consumeStreamId_ = getDefaultInstance().getConsumeStreamId();
        onChanged();
        return this;
      }
      /**
       * <code>required string ConsumeStreamId = 1;</code>
       */
      public Builder setConsumeStreamIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        consumeStreamId_ = value;
        onChanged();
        return this;
      }

      // required string CooOrderSerial = 2;
      private java.lang.Object cooOrderSerial_ = "";
      /**
       * <code>required string CooOrderSerial = 2;</code>
       */
      public boolean hasCooOrderSerial() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string CooOrderSerial = 2;</code>
       */
      public java.lang.String getCooOrderSerial() {
        java.lang.Object ref = cooOrderSerial_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          cooOrderSerial_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string CooOrderSerial = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCooOrderSerialBytes() {
        java.lang.Object ref = cooOrderSerial_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cooOrderSerial_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string CooOrderSerial = 2;</code>
       */
      public Builder setCooOrderSerial(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        cooOrderSerial_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string CooOrderSerial = 2;</code>
       */
      public Builder clearCooOrderSerial() {
        bitField0_ = (bitField0_ & ~0x00000002);
        cooOrderSerial_ = getDefaultInstance().getCooOrderSerial();
        onChanged();
        return this;
      }
      /**
       * <code>required string CooOrderSerial = 2;</code>
       */
      public Builder setCooOrderSerialBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        cooOrderSerial_ = value;
        onChanged();
        return this;
      }

      // required string Uin = 3;
      private java.lang.Object uin_ = "";
      /**
       * <code>required string Uin = 3;</code>
       */
      public boolean hasUin() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string Uin = 3;</code>
       */
      public java.lang.String getUin() {
        java.lang.Object ref = uin_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          uin_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string Uin = 3;</code>
       */
      public com.google.protobuf.ByteString
          getUinBytes() {
        java.lang.Object ref = uin_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uin_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string Uin = 3;</code>
       */
      public Builder setUin(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        uin_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string Uin = 3;</code>
       */
      public Builder clearUin() {
        bitField0_ = (bitField0_ & ~0x00000004);
        uin_ = getDefaultInstance().getUin();
        onChanged();
        return this;
      }
      /**
       * <code>required string Uin = 3;</code>
       */
      public Builder setUinBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        uin_ = value;
        onChanged();
        return this;
      }

      // required string GoodsId = 4;
      private java.lang.Object goodsId_ = "";
      /**
       * <code>required string GoodsId = 4;</code>
       */
      public boolean hasGoodsId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string GoodsId = 4;</code>
       */
      public java.lang.String getGoodsId() {
        java.lang.Object ref = goodsId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          goodsId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string GoodsId = 4;</code>
       */
      public com.google.protobuf.ByteString
          getGoodsIdBytes() {
        java.lang.Object ref = goodsId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          goodsId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string GoodsId = 4;</code>
       */
      public Builder setGoodsId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        goodsId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string GoodsId = 4;</code>
       */
      public Builder clearGoodsId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        goodsId_ = getDefaultInstance().getGoodsId();
        onChanged();
        return this;
      }
      /**
       * <code>required string GoodsId = 4;</code>
       */
      public Builder setGoodsIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        goodsId_ = value;
        onChanged();
        return this;
      }

      // required int32 GoodsCount = 5;
      private int goodsCount_ ;
      /**
       * <code>required int32 GoodsCount = 5;</code>
       */
      public boolean hasGoodsCount() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int32 GoodsCount = 5;</code>
       */
      public int getGoodsCount() {
        return goodsCount_;
      }
      /**
       * <code>required int32 GoodsCount = 5;</code>
       */
      public Builder setGoodsCount(int value) {
        bitField0_ |= 0x00000010;
        goodsCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 GoodsCount = 5;</code>
       */
      public Builder clearGoodsCount() {
        bitField0_ = (bitField0_ & ~0x00000010);
        goodsCount_ = 0;
        onChanged();
        return this;
      }

      // required string CreateTime = 6;
      private java.lang.Object createTime_ = "";
      /**
       * <code>required string CreateTime = 6;</code>
       */
      public boolean hasCreateTime() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required string CreateTime = 6;</code>
       */
      public java.lang.String getCreateTime() {
        java.lang.Object ref = createTime_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          createTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string CreateTime = 6;</code>
       */
      public com.google.protobuf.ByteString
          getCreateTimeBytes() {
        java.lang.Object ref = createTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          createTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string CreateTime = 6;</code>
       */
      public Builder setCreateTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        createTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string CreateTime = 6;</code>
       */
      public Builder clearCreateTime() {
        bitField0_ = (bitField0_ & ~0x00000020);
        createTime_ = getDefaultInstance().getCreateTime();
        onChanged();
        return this;
      }
      /**
       * <code>required string CreateTime = 6;</code>
       */
      public Builder setCreateTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        createTime_ = value;
        onChanged();
        return this;
      }

      // optional string Platform = 7;
      private java.lang.Object platform_ = "";
      /**
       * <code>optional string Platform = 7;</code>
       */
      public boolean hasPlatform() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string Platform = 7;</code>
       */
      public java.lang.String getPlatform() {
        java.lang.Object ref = platform_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          platform_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string Platform = 7;</code>
       */
      public com.google.protobuf.ByteString
          getPlatformBytes() {
        java.lang.Object ref = platform_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          platform_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string Platform = 7;</code>
       */
      public Builder setPlatform(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        platform_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string Platform = 7;</code>
       */
      public Builder clearPlatform() {
        bitField0_ = (bitField0_ & ~0x00000040);
        platform_ = getDefaultInstance().getPlatform();
        onChanged();
        return this;
      }
      /**
       * <code>optional string Platform = 7;</code>
       */
      public Builder setPlatformBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        platform_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:OPRecharge)
    }

    static {
      defaultInstance = new OPRecharge(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:OPRecharge)
  }

  public interface OPRechargeRetOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 status = 1;
    /**
     * <code>required int32 status = 1;</code>
     */
    boolean hasStatus();
    /**
     * <code>required int32 status = 1;</code>
     */
    int getStatus();
  }
  /**
   * Protobuf type {@code OPRechargeRet}
   */
  public static final class OPRechargeRet extends
      com.google.protobuf.GeneratedMessage
      implements OPRechargeRetOrBuilder {
    // Use OPRechargeRet.newBuilder() to construct.
    private OPRechargeRet(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private OPRechargeRet(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final OPRechargeRet defaultInstance;
    public static OPRechargeRet getDefaultInstance() {
      return defaultInstance;
    }

    public OPRechargeRet getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private OPRechargeRet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              status_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.oldmountain.dzm.message.Recharge.internal_static_OPRechargeRet_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.oldmountain.dzm.message.Recharge.internal_static_OPRechargeRet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.oldmountain.dzm.message.Recharge.OPRechargeRet.class, com.oldmountain.dzm.message.Recharge.OPRechargeRet.Builder.class);
    }

    public static com.google.protobuf.Parser<OPRechargeRet> PARSER =
        new com.google.protobuf.AbstractParser<OPRechargeRet>() {
      public OPRechargeRet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OPRechargeRet(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<OPRechargeRet> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 status = 1;
    public static final int STATUS_FIELD_NUMBER = 1;
    private int status_;
    /**
     * <code>required int32 status = 1;</code>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 status = 1;</code>
     */
    public int getStatus() {
      return status_;
    }

    private void initFields() {
      status_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, status_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, status_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.oldmountain.dzm.message.Recharge.OPRechargeRet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.oldmountain.dzm.message.Recharge.OPRechargeRet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.oldmountain.dzm.message.Recharge.OPRechargeRet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.oldmountain.dzm.message.Recharge.OPRechargeRet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.oldmountain.dzm.message.Recharge.OPRechargeRet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.oldmountain.dzm.message.Recharge.OPRechargeRet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.oldmountain.dzm.message.Recharge.OPRechargeRet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.oldmountain.dzm.message.Recharge.OPRechargeRet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.oldmountain.dzm.message.Recharge.OPRechargeRet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.oldmountain.dzm.message.Recharge.OPRechargeRet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.oldmountain.dzm.message.Recharge.OPRechargeRet prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code OPRechargeRet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.oldmountain.dzm.message.Recharge.OPRechargeRetOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.oldmountain.dzm.message.Recharge.internal_static_OPRechargeRet_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.oldmountain.dzm.message.Recharge.internal_static_OPRechargeRet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.oldmountain.dzm.message.Recharge.OPRechargeRet.class, com.oldmountain.dzm.message.Recharge.OPRechargeRet.Builder.class);
      }

      // Construct using com.oldmountain.dzm.message.Recharge.OPRechargeRet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        status_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.oldmountain.dzm.message.Recharge.internal_static_OPRechargeRet_descriptor;
      }

      public com.oldmountain.dzm.message.Recharge.OPRechargeRet getDefaultInstanceForType() {
        return com.oldmountain.dzm.message.Recharge.OPRechargeRet.getDefaultInstance();
      }

      public com.oldmountain.dzm.message.Recharge.OPRechargeRet build() {
        com.oldmountain.dzm.message.Recharge.OPRechargeRet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.oldmountain.dzm.message.Recharge.OPRechargeRet buildPartial() {
        com.oldmountain.dzm.message.Recharge.OPRechargeRet result = new com.oldmountain.dzm.message.Recharge.OPRechargeRet(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.status_ = status_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.oldmountain.dzm.message.Recharge.OPRechargeRet) {
          return mergeFrom((com.oldmountain.dzm.message.Recharge.OPRechargeRet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.oldmountain.dzm.message.Recharge.OPRechargeRet other) {
        if (other == com.oldmountain.dzm.message.Recharge.OPRechargeRet.getDefaultInstance()) return this;
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasStatus()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.oldmountain.dzm.message.Recharge.OPRechargeRet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.oldmountain.dzm.message.Recharge.OPRechargeRet) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 status = 1;
      private int status_ ;
      /**
       * <code>required int32 status = 1;</code>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 status = 1;</code>
       */
      public int getStatus() {
        return status_;
      }
      /**
       * <code>required int32 status = 1;</code>
       */
      public Builder setStatus(int value) {
        bitField0_ |= 0x00000001;
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 status = 1;</code>
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:OPRechargeRet)
    }

    static {
      defaultInstance = new OPRechargeRet(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:OPRechargeRet)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_OPRecharge_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_OPRecharge_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_OPRechargeRet_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_OPRechargeRet_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016recharge.proto\"\225\001\n\nOPRecharge\022\027\n\017Consu" +
      "meStreamId\030\001 \002(\t\022\026\n\016CooOrderSerial\030\002 \002(\t" +
      "\022\013\n\003Uin\030\003 \002(\t\022\017\n\007GoodsId\030\004 \002(\t\022\022\n\nGoodsC" +
      "ount\030\005 \002(\005\022\022\n\nCreateTime\030\006 \002(\t\022\020\n\010Platfo" +
      "rm\030\007 \001(\t\"\037\n\rOPRechargeRet\022\016\n\006status\030\001 \002(" +
      "\005B\035\n\033com.oldmountain.dzm.message"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_OPRecharge_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_OPRecharge_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_OPRecharge_descriptor,
              new java.lang.String[] { "ConsumeStreamId", "CooOrderSerial", "Uin", "GoodsId", "GoodsCount", "CreateTime", "Platform", });
          internal_static_OPRechargeRet_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_OPRechargeRet_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_OPRechargeRet_descriptor,
              new java.lang.String[] { "Status", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
