// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SellEquip.proto

package com.oldmountain.dzm.message;

public final class SellEquip {
  private SellEquip() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface OPSellEquipOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated int32 id = 1;
    /**
     * <code>repeated int32 id = 1;</code>
     */
    java.util.List<java.lang.Integer> getIdList();
    /**
     * <code>repeated int32 id = 1;</code>
     */
    int getIdCount();
    /**
     * <code>repeated int32 id = 1;</code>
     */
    int getId(int index);
  }
  /**
   * Protobuf type {@code OPSellEquip}
   */
  public static final class OPSellEquip extends
      com.google.protobuf.GeneratedMessage
      implements OPSellEquipOrBuilder {
    // Use OPSellEquip.newBuilder() to construct.
    private OPSellEquip(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private OPSellEquip(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final OPSellEquip defaultInstance;
    public static OPSellEquip getDefaultInstance() {
      return defaultInstance;
    }

    public OPSellEquip getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private OPSellEquip(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                id_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              id_.add(input.readInt32());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                id_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                id_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          id_ = java.util.Collections.unmodifiableList(id_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.oldmountain.dzm.message.SellEquip.internal_static_OPSellEquip_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.oldmountain.dzm.message.SellEquip.internal_static_OPSellEquip_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.oldmountain.dzm.message.SellEquip.OPSellEquip.class, com.oldmountain.dzm.message.SellEquip.OPSellEquip.Builder.class);
    }

    public static com.google.protobuf.Parser<OPSellEquip> PARSER =
        new com.google.protobuf.AbstractParser<OPSellEquip>() {
      public OPSellEquip parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OPSellEquip(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<OPSellEquip> getParserForType() {
      return PARSER;
    }

    // repeated int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Integer> id_;
    /**
     * <code>repeated int32 id = 1;</code>
     */
    public java.util.List<java.lang.Integer>
        getIdList() {
      return id_;
    }
    /**
     * <code>repeated int32 id = 1;</code>
     */
    public int getIdCount() {
      return id_.size();
    }
    /**
     * <code>repeated int32 id = 1;</code>
     */
    public int getId(int index) {
      return id_.get(index);
    }

    private void initFields() {
      id_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < id_.size(); i++) {
        output.writeInt32(1, id_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < id_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(id_.get(i));
        }
        size += dataSize;
        size += 1 * getIdList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.oldmountain.dzm.message.SellEquip.OPSellEquip parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.oldmountain.dzm.message.SellEquip.OPSellEquip parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.oldmountain.dzm.message.SellEquip.OPSellEquip parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.oldmountain.dzm.message.SellEquip.OPSellEquip parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.oldmountain.dzm.message.SellEquip.OPSellEquip parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.oldmountain.dzm.message.SellEquip.OPSellEquip parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.oldmountain.dzm.message.SellEquip.OPSellEquip parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.oldmountain.dzm.message.SellEquip.OPSellEquip parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.oldmountain.dzm.message.SellEquip.OPSellEquip parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.oldmountain.dzm.message.SellEquip.OPSellEquip parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.oldmountain.dzm.message.SellEquip.OPSellEquip prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code OPSellEquip}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.oldmountain.dzm.message.SellEquip.OPSellEquipOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.oldmountain.dzm.message.SellEquip.internal_static_OPSellEquip_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.oldmountain.dzm.message.SellEquip.internal_static_OPSellEquip_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.oldmountain.dzm.message.SellEquip.OPSellEquip.class, com.oldmountain.dzm.message.SellEquip.OPSellEquip.Builder.class);
      }

      // Construct using com.oldmountain.dzm.message.SellEquip.OPSellEquip.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.oldmountain.dzm.message.SellEquip.internal_static_OPSellEquip_descriptor;
      }

      public com.oldmountain.dzm.message.SellEquip.OPSellEquip getDefaultInstanceForType() {
        return com.oldmountain.dzm.message.SellEquip.OPSellEquip.getDefaultInstance();
      }

      public com.oldmountain.dzm.message.SellEquip.OPSellEquip build() {
        com.oldmountain.dzm.message.SellEquip.OPSellEquip result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.oldmountain.dzm.message.SellEquip.OPSellEquip buildPartial() {
        com.oldmountain.dzm.message.SellEquip.OPSellEquip result = new com.oldmountain.dzm.message.SellEquip.OPSellEquip(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          id_ = java.util.Collections.unmodifiableList(id_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.id_ = id_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.oldmountain.dzm.message.SellEquip.OPSellEquip) {
          return mergeFrom((com.oldmountain.dzm.message.SellEquip.OPSellEquip)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.oldmountain.dzm.message.SellEquip.OPSellEquip other) {
        if (other == com.oldmountain.dzm.message.SellEquip.OPSellEquip.getDefaultInstance()) return this;
        if (!other.id_.isEmpty()) {
          if (id_.isEmpty()) {
            id_ = other.id_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureIdIsMutable();
            id_.addAll(other.id_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.oldmountain.dzm.message.SellEquip.OPSellEquip parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.oldmountain.dzm.message.SellEquip.OPSellEquip) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated int32 id = 1;
      private java.util.List<java.lang.Integer> id_ = java.util.Collections.emptyList();
      private void ensureIdIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          id_ = new java.util.ArrayList<java.lang.Integer>(id_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int32 id = 1;</code>
       */
      public java.util.List<java.lang.Integer>
          getIdList() {
        return java.util.Collections.unmodifiableList(id_);
      }
      /**
       * <code>repeated int32 id = 1;</code>
       */
      public int getIdCount() {
        return id_.size();
      }
      /**
       * <code>repeated int32 id = 1;</code>
       */
      public int getId(int index) {
        return id_.get(index);
      }
      /**
       * <code>repeated int32 id = 1;</code>
       */
      public Builder setId(
          int index, int value) {
        ensureIdIsMutable();
        id_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 id = 1;</code>
       */
      public Builder addId(int value) {
        ensureIdIsMutable();
        id_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 id = 1;</code>
       */
      public Builder addAllId(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureIdIsMutable();
        super.addAll(values, id_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 id = 1;</code>
       */
      public Builder clearId() {
        id_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:OPSellEquip)
    }

    static {
      defaultInstance = new OPSellEquip(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:OPSellEquip)
  }

  public interface OPSellEquipRetOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 silvercoins = 1;
    /**
     * <code>required int64 silvercoins = 1;</code>
     */
    boolean hasSilvercoins();
    /**
     * <code>required int64 silvercoins = 1;</code>
     */
    long getSilvercoins();

    // required int32 servertime = 2;
    /**
     * <code>required int32 servertime = 2;</code>
     */
    boolean hasServertime();
    /**
     * <code>required int32 servertime = 2;</code>
     */
    int getServertime();

    // repeated int32 ids = 3;
    /**
     * <code>repeated int32 ids = 3;</code>
     */
    java.util.List<java.lang.Integer> getIdsList();
    /**
     * <code>repeated int32 ids = 3;</code>
     */
    int getIdsCount();
    /**
     * <code>repeated int32 ids = 3;</code>
     */
    int getIds(int index);
  }
  /**
   * Protobuf type {@code OPSellEquipRet}
   */
  public static final class OPSellEquipRet extends
      com.google.protobuf.GeneratedMessage
      implements OPSellEquipRetOrBuilder {
    // Use OPSellEquipRet.newBuilder() to construct.
    private OPSellEquipRet(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private OPSellEquipRet(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final OPSellEquipRet defaultInstance;
    public static OPSellEquipRet getDefaultInstance() {
      return defaultInstance;
    }

    public OPSellEquipRet getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private OPSellEquipRet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              silvercoins_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              servertime_ = input.readInt32();
              break;
            }
            case 24: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                ids_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000004;
              }
              ids_.add(input.readInt32());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
                ids_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000004;
              }
              while (input.getBytesUntilLimit() > 0) {
                ids_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          ids_ = java.util.Collections.unmodifiableList(ids_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.oldmountain.dzm.message.SellEquip.internal_static_OPSellEquipRet_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.oldmountain.dzm.message.SellEquip.internal_static_OPSellEquipRet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.oldmountain.dzm.message.SellEquip.OPSellEquipRet.class, com.oldmountain.dzm.message.SellEquip.OPSellEquipRet.Builder.class);
    }

    public static com.google.protobuf.Parser<OPSellEquipRet> PARSER =
        new com.google.protobuf.AbstractParser<OPSellEquipRet>() {
      public OPSellEquipRet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OPSellEquipRet(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<OPSellEquipRet> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 silvercoins = 1;
    public static final int SILVERCOINS_FIELD_NUMBER = 1;
    private long silvercoins_;
    /**
     * <code>required int64 silvercoins = 1;</code>
     */
    public boolean hasSilvercoins() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 silvercoins = 1;</code>
     */
    public long getSilvercoins() {
      return silvercoins_;
    }

    // required int32 servertime = 2;
    public static final int SERVERTIME_FIELD_NUMBER = 2;
    private int servertime_;
    /**
     * <code>required int32 servertime = 2;</code>
     */
    public boolean hasServertime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 servertime = 2;</code>
     */
    public int getServertime() {
      return servertime_;
    }

    // repeated int32 ids = 3;
    public static final int IDS_FIELD_NUMBER = 3;
    private java.util.List<java.lang.Integer> ids_;
    /**
     * <code>repeated int32 ids = 3;</code>
     */
    public java.util.List<java.lang.Integer>
        getIdsList() {
      return ids_;
    }
    /**
     * <code>repeated int32 ids = 3;</code>
     */
    public int getIdsCount() {
      return ids_.size();
    }
    /**
     * <code>repeated int32 ids = 3;</code>
     */
    public int getIds(int index) {
      return ids_.get(index);
    }

    private void initFields() {
      silvercoins_ = 0L;
      servertime_ = 0;
      ids_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasSilvercoins()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasServertime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, silvercoins_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, servertime_);
      }
      for (int i = 0; i < ids_.size(); i++) {
        output.writeInt32(3, ids_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, silvercoins_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, servertime_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < ids_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(ids_.get(i));
        }
        size += dataSize;
        size += 1 * getIdsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.oldmountain.dzm.message.SellEquip.OPSellEquipRet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.oldmountain.dzm.message.SellEquip.OPSellEquipRet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.oldmountain.dzm.message.SellEquip.OPSellEquipRet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.oldmountain.dzm.message.SellEquip.OPSellEquipRet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.oldmountain.dzm.message.SellEquip.OPSellEquipRet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.oldmountain.dzm.message.SellEquip.OPSellEquipRet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.oldmountain.dzm.message.SellEquip.OPSellEquipRet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.oldmountain.dzm.message.SellEquip.OPSellEquipRet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.oldmountain.dzm.message.SellEquip.OPSellEquipRet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.oldmountain.dzm.message.SellEquip.OPSellEquipRet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.oldmountain.dzm.message.SellEquip.OPSellEquipRet prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code OPSellEquipRet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.oldmountain.dzm.message.SellEquip.OPSellEquipRetOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.oldmountain.dzm.message.SellEquip.internal_static_OPSellEquipRet_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.oldmountain.dzm.message.SellEquip.internal_static_OPSellEquipRet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.oldmountain.dzm.message.SellEquip.OPSellEquipRet.class, com.oldmountain.dzm.message.SellEquip.OPSellEquipRet.Builder.class);
      }

      // Construct using com.oldmountain.dzm.message.SellEquip.OPSellEquipRet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        silvercoins_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        servertime_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        ids_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.oldmountain.dzm.message.SellEquip.internal_static_OPSellEquipRet_descriptor;
      }

      public com.oldmountain.dzm.message.SellEquip.OPSellEquipRet getDefaultInstanceForType() {
        return com.oldmountain.dzm.message.SellEquip.OPSellEquipRet.getDefaultInstance();
      }

      public com.oldmountain.dzm.message.SellEquip.OPSellEquipRet build() {
        com.oldmountain.dzm.message.SellEquip.OPSellEquipRet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.oldmountain.dzm.message.SellEquip.OPSellEquipRet buildPartial() {
        com.oldmountain.dzm.message.SellEquip.OPSellEquipRet result = new com.oldmountain.dzm.message.SellEquip.OPSellEquipRet(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.silvercoins_ = silvercoins_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.servertime_ = servertime_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          ids_ = java.util.Collections.unmodifiableList(ids_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.ids_ = ids_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.oldmountain.dzm.message.SellEquip.OPSellEquipRet) {
          return mergeFrom((com.oldmountain.dzm.message.SellEquip.OPSellEquipRet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.oldmountain.dzm.message.SellEquip.OPSellEquipRet other) {
        if (other == com.oldmountain.dzm.message.SellEquip.OPSellEquipRet.getDefaultInstance()) return this;
        if (other.hasSilvercoins()) {
          setSilvercoins(other.getSilvercoins());
        }
        if (other.hasServertime()) {
          setServertime(other.getServertime());
        }
        if (!other.ids_.isEmpty()) {
          if (ids_.isEmpty()) {
            ids_ = other.ids_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureIdsIsMutable();
            ids_.addAll(other.ids_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSilvercoins()) {
          
          return false;
        }
        if (!hasServertime()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.oldmountain.dzm.message.SellEquip.OPSellEquipRet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.oldmountain.dzm.message.SellEquip.OPSellEquipRet) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 silvercoins = 1;
      private long silvercoins_ ;
      /**
       * <code>required int64 silvercoins = 1;</code>
       */
      public boolean hasSilvercoins() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 silvercoins = 1;</code>
       */
      public long getSilvercoins() {
        return silvercoins_;
      }
      /**
       * <code>required int64 silvercoins = 1;</code>
       */
      public Builder setSilvercoins(long value) {
        bitField0_ |= 0x00000001;
        silvercoins_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 silvercoins = 1;</code>
       */
      public Builder clearSilvercoins() {
        bitField0_ = (bitField0_ & ~0x00000001);
        silvercoins_ = 0L;
        onChanged();
        return this;
      }

      // required int32 servertime = 2;
      private int servertime_ ;
      /**
       * <code>required int32 servertime = 2;</code>
       */
      public boolean hasServertime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 servertime = 2;</code>
       */
      public int getServertime() {
        return servertime_;
      }
      /**
       * <code>required int32 servertime = 2;</code>
       */
      public Builder setServertime(int value) {
        bitField0_ |= 0x00000002;
        servertime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 servertime = 2;</code>
       */
      public Builder clearServertime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        servertime_ = 0;
        onChanged();
        return this;
      }

      // repeated int32 ids = 3;
      private java.util.List<java.lang.Integer> ids_ = java.util.Collections.emptyList();
      private void ensureIdsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          ids_ = new java.util.ArrayList<java.lang.Integer>(ids_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated int32 ids = 3;</code>
       */
      public java.util.List<java.lang.Integer>
          getIdsList() {
        return java.util.Collections.unmodifiableList(ids_);
      }
      /**
       * <code>repeated int32 ids = 3;</code>
       */
      public int getIdsCount() {
        return ids_.size();
      }
      /**
       * <code>repeated int32 ids = 3;</code>
       */
      public int getIds(int index) {
        return ids_.get(index);
      }
      /**
       * <code>repeated int32 ids = 3;</code>
       */
      public Builder setIds(
          int index, int value) {
        ensureIdsIsMutable();
        ids_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 ids = 3;</code>
       */
      public Builder addIds(int value) {
        ensureIdsIsMutable();
        ids_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 ids = 3;</code>
       */
      public Builder addAllIds(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureIdsIsMutable();
        super.addAll(values, ids_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 ids = 3;</code>
       */
      public Builder clearIds() {
        ids_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:OPSellEquipRet)
    }

    static {
      defaultInstance = new OPSellEquipRet(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:OPSellEquipRet)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_OPSellEquip_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_OPSellEquip_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_OPSellEquipRet_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_OPSellEquipRet_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017SellEquip.proto\"\031\n\013OPSellEquip\022\n\n\002id\030\001" +
      " \003(\005\"F\n\016OPSellEquipRet\022\023\n\013silvercoins\030\001 " +
      "\002(\003\022\022\n\nservertime\030\002 \002(\005\022\013\n\003ids\030\003 \003(\005B\035\n\033" +
      "com.oldmountain.dzm.message"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_OPSellEquip_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_OPSellEquip_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_OPSellEquip_descriptor,
              new java.lang.String[] { "Id", });
          internal_static_OPSellEquipRet_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_OPSellEquipRet_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_OPSellEquipRet_descriptor,
              new java.lang.String[] { "Silvercoins", "Servertime", "Ids", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
