// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SnatchFragment.proto

package com.oldmountain.dzm.message;

public final class SnatchFragment {
  private SnatchFragment() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface OPSnatchFragmentOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 playerid = 1;
    /**
     * <code>required int32 playerid = 1;</code>
     */
    boolean hasPlayerid();
    /**
     * <code>required int32 playerid = 1;</code>
     */
    int getPlayerid();

    // required int32 fragmentid = 2;
    /**
     * <code>required int32 fragmentid = 2;</code>
     */
    boolean hasFragmentid();
    /**
     * <code>required int32 fragmentid = 2;</code>
     */
    int getFragmentid();
  }
  /**
   * Protobuf type {@code OPSnatchFragment}
   */
  public static final class OPSnatchFragment extends
      com.google.protobuf.GeneratedMessage
      implements OPSnatchFragmentOrBuilder {
    // Use OPSnatchFragment.newBuilder() to construct.
    private OPSnatchFragment(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private OPSnatchFragment(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final OPSnatchFragment defaultInstance;
    public static OPSnatchFragment getDefaultInstance() {
      return defaultInstance;
    }

    public OPSnatchFragment getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private OPSnatchFragment(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              playerid_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              fragmentid_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.oldmountain.dzm.message.SnatchFragment.internal_static_OPSnatchFragment_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.oldmountain.dzm.message.SnatchFragment.internal_static_OPSnatchFragment_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.oldmountain.dzm.message.SnatchFragment.OPSnatchFragment.class, com.oldmountain.dzm.message.SnatchFragment.OPSnatchFragment.Builder.class);
    }

    public static com.google.protobuf.Parser<OPSnatchFragment> PARSER =
        new com.google.protobuf.AbstractParser<OPSnatchFragment>() {
      public OPSnatchFragment parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OPSnatchFragment(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<OPSnatchFragment> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 playerid = 1;
    public static final int PLAYERID_FIELD_NUMBER = 1;
    private int playerid_;
    /**
     * <code>required int32 playerid = 1;</code>
     */
    public boolean hasPlayerid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 playerid = 1;</code>
     */
    public int getPlayerid() {
      return playerid_;
    }

    // required int32 fragmentid = 2;
    public static final int FRAGMENTID_FIELD_NUMBER = 2;
    private int fragmentid_;
    /**
     * <code>required int32 fragmentid = 2;</code>
     */
    public boolean hasFragmentid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 fragmentid = 2;</code>
     */
    public int getFragmentid() {
      return fragmentid_;
    }

    private void initFields() {
      playerid_ = 0;
      fragmentid_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasPlayerid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFragmentid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, playerid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, fragmentid_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, playerid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, fragmentid_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.oldmountain.dzm.message.SnatchFragment.OPSnatchFragment parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.oldmountain.dzm.message.SnatchFragment.OPSnatchFragment parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.oldmountain.dzm.message.SnatchFragment.OPSnatchFragment parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.oldmountain.dzm.message.SnatchFragment.OPSnatchFragment parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.oldmountain.dzm.message.SnatchFragment.OPSnatchFragment parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.oldmountain.dzm.message.SnatchFragment.OPSnatchFragment parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.oldmountain.dzm.message.SnatchFragment.OPSnatchFragment parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.oldmountain.dzm.message.SnatchFragment.OPSnatchFragment parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.oldmountain.dzm.message.SnatchFragment.OPSnatchFragment parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.oldmountain.dzm.message.SnatchFragment.OPSnatchFragment parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.oldmountain.dzm.message.SnatchFragment.OPSnatchFragment prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code OPSnatchFragment}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.oldmountain.dzm.message.SnatchFragment.OPSnatchFragmentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.oldmountain.dzm.message.SnatchFragment.internal_static_OPSnatchFragment_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.oldmountain.dzm.message.SnatchFragment.internal_static_OPSnatchFragment_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.oldmountain.dzm.message.SnatchFragment.OPSnatchFragment.class, com.oldmountain.dzm.message.SnatchFragment.OPSnatchFragment.Builder.class);
      }

      // Construct using com.oldmountain.dzm.message.SnatchFragment.OPSnatchFragment.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        playerid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        fragmentid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.oldmountain.dzm.message.SnatchFragment.internal_static_OPSnatchFragment_descriptor;
      }

      public com.oldmountain.dzm.message.SnatchFragment.OPSnatchFragment getDefaultInstanceForType() {
        return com.oldmountain.dzm.message.SnatchFragment.OPSnatchFragment.getDefaultInstance();
      }

      public com.oldmountain.dzm.message.SnatchFragment.OPSnatchFragment build() {
        com.oldmountain.dzm.message.SnatchFragment.OPSnatchFragment result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.oldmountain.dzm.message.SnatchFragment.OPSnatchFragment buildPartial() {
        com.oldmountain.dzm.message.SnatchFragment.OPSnatchFragment result = new com.oldmountain.dzm.message.SnatchFragment.OPSnatchFragment(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.playerid_ = playerid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.fragmentid_ = fragmentid_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.oldmountain.dzm.message.SnatchFragment.OPSnatchFragment) {
          return mergeFrom((com.oldmountain.dzm.message.SnatchFragment.OPSnatchFragment)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.oldmountain.dzm.message.SnatchFragment.OPSnatchFragment other) {
        if (other == com.oldmountain.dzm.message.SnatchFragment.OPSnatchFragment.getDefaultInstance()) return this;
        if (other.hasPlayerid()) {
          setPlayerid(other.getPlayerid());
        }
        if (other.hasFragmentid()) {
          setFragmentid(other.getFragmentid());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPlayerid()) {
          
          return false;
        }
        if (!hasFragmentid()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.oldmountain.dzm.message.SnatchFragment.OPSnatchFragment parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.oldmountain.dzm.message.SnatchFragment.OPSnatchFragment) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 playerid = 1;
      private int playerid_ ;
      /**
       * <code>required int32 playerid = 1;</code>
       */
      public boolean hasPlayerid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 playerid = 1;</code>
       */
      public int getPlayerid() {
        return playerid_;
      }
      /**
       * <code>required int32 playerid = 1;</code>
       */
      public Builder setPlayerid(int value) {
        bitField0_ |= 0x00000001;
        playerid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 playerid = 1;</code>
       */
      public Builder clearPlayerid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        playerid_ = 0;
        onChanged();
        return this;
      }

      // required int32 fragmentid = 2;
      private int fragmentid_ ;
      /**
       * <code>required int32 fragmentid = 2;</code>
       */
      public boolean hasFragmentid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 fragmentid = 2;</code>
       */
      public int getFragmentid() {
        return fragmentid_;
      }
      /**
       * <code>required int32 fragmentid = 2;</code>
       */
      public Builder setFragmentid(int value) {
        bitField0_ |= 0x00000002;
        fragmentid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 fragmentid = 2;</code>
       */
      public Builder clearFragmentid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        fragmentid_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:OPSnatchFragment)
    }

    static {
      defaultInstance = new OPSnatchFragment(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:OPSnatchFragment)
  }

  public interface OPSnatchFragmentRetOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 servertime = 1;
    /**
     * <code>required int32 servertime = 1;</code>
     */
    boolean hasServertime();
    /**
     * <code>required int32 servertime = 1;</code>
     */
    int getServertime();

    // required int32 status = 2;
    /**
     * <code>required int32 status = 2;</code>
     */
    boolean hasStatus();
    /**
     * <code>required int32 status = 2;</code>
     */
    int getStatus();
  }
  /**
   * Protobuf type {@code OPSnatchFragmentRet}
   */
  public static final class OPSnatchFragmentRet extends
      com.google.protobuf.GeneratedMessage
      implements OPSnatchFragmentRetOrBuilder {
    // Use OPSnatchFragmentRet.newBuilder() to construct.
    private OPSnatchFragmentRet(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private OPSnatchFragmentRet(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final OPSnatchFragmentRet defaultInstance;
    public static OPSnatchFragmentRet getDefaultInstance() {
      return defaultInstance;
    }

    public OPSnatchFragmentRet getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private OPSnatchFragmentRet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              servertime_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              status_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.oldmountain.dzm.message.SnatchFragment.internal_static_OPSnatchFragmentRet_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.oldmountain.dzm.message.SnatchFragment.internal_static_OPSnatchFragmentRet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.oldmountain.dzm.message.SnatchFragment.OPSnatchFragmentRet.class, com.oldmountain.dzm.message.SnatchFragment.OPSnatchFragmentRet.Builder.class);
    }

    public static com.google.protobuf.Parser<OPSnatchFragmentRet> PARSER =
        new com.google.protobuf.AbstractParser<OPSnatchFragmentRet>() {
      public OPSnatchFragmentRet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OPSnatchFragmentRet(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<OPSnatchFragmentRet> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 servertime = 1;
    public static final int SERVERTIME_FIELD_NUMBER = 1;
    private int servertime_;
    /**
     * <code>required int32 servertime = 1;</code>
     */
    public boolean hasServertime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 servertime = 1;</code>
     */
    public int getServertime() {
      return servertime_;
    }

    // required int32 status = 2;
    public static final int STATUS_FIELD_NUMBER = 2;
    private int status_;
    /**
     * <code>required int32 status = 2;</code>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 status = 2;</code>
     */
    public int getStatus() {
      return status_;
    }

    private void initFields() {
      servertime_ = 0;
      status_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasServertime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, servertime_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, status_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, servertime_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, status_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.oldmountain.dzm.message.SnatchFragment.OPSnatchFragmentRet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.oldmountain.dzm.message.SnatchFragment.OPSnatchFragmentRet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.oldmountain.dzm.message.SnatchFragment.OPSnatchFragmentRet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.oldmountain.dzm.message.SnatchFragment.OPSnatchFragmentRet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.oldmountain.dzm.message.SnatchFragment.OPSnatchFragmentRet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.oldmountain.dzm.message.SnatchFragment.OPSnatchFragmentRet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.oldmountain.dzm.message.SnatchFragment.OPSnatchFragmentRet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.oldmountain.dzm.message.SnatchFragment.OPSnatchFragmentRet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.oldmountain.dzm.message.SnatchFragment.OPSnatchFragmentRet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.oldmountain.dzm.message.SnatchFragment.OPSnatchFragmentRet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.oldmountain.dzm.message.SnatchFragment.OPSnatchFragmentRet prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code OPSnatchFragmentRet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.oldmountain.dzm.message.SnatchFragment.OPSnatchFragmentRetOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.oldmountain.dzm.message.SnatchFragment.internal_static_OPSnatchFragmentRet_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.oldmountain.dzm.message.SnatchFragment.internal_static_OPSnatchFragmentRet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.oldmountain.dzm.message.SnatchFragment.OPSnatchFragmentRet.class, com.oldmountain.dzm.message.SnatchFragment.OPSnatchFragmentRet.Builder.class);
      }

      // Construct using com.oldmountain.dzm.message.SnatchFragment.OPSnatchFragmentRet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        servertime_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.oldmountain.dzm.message.SnatchFragment.internal_static_OPSnatchFragmentRet_descriptor;
      }

      public com.oldmountain.dzm.message.SnatchFragment.OPSnatchFragmentRet getDefaultInstanceForType() {
        return com.oldmountain.dzm.message.SnatchFragment.OPSnatchFragmentRet.getDefaultInstance();
      }

      public com.oldmountain.dzm.message.SnatchFragment.OPSnatchFragmentRet build() {
        com.oldmountain.dzm.message.SnatchFragment.OPSnatchFragmentRet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.oldmountain.dzm.message.SnatchFragment.OPSnatchFragmentRet buildPartial() {
        com.oldmountain.dzm.message.SnatchFragment.OPSnatchFragmentRet result = new com.oldmountain.dzm.message.SnatchFragment.OPSnatchFragmentRet(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.servertime_ = servertime_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.status_ = status_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.oldmountain.dzm.message.SnatchFragment.OPSnatchFragmentRet) {
          return mergeFrom((com.oldmountain.dzm.message.SnatchFragment.OPSnatchFragmentRet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.oldmountain.dzm.message.SnatchFragment.OPSnatchFragmentRet other) {
        if (other == com.oldmountain.dzm.message.SnatchFragment.OPSnatchFragmentRet.getDefaultInstance()) return this;
        if (other.hasServertime()) {
          setServertime(other.getServertime());
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasServertime()) {
          
          return false;
        }
        if (!hasStatus()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.oldmountain.dzm.message.SnatchFragment.OPSnatchFragmentRet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.oldmountain.dzm.message.SnatchFragment.OPSnatchFragmentRet) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 servertime = 1;
      private int servertime_ ;
      /**
       * <code>required int32 servertime = 1;</code>
       */
      public boolean hasServertime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 servertime = 1;</code>
       */
      public int getServertime() {
        return servertime_;
      }
      /**
       * <code>required int32 servertime = 1;</code>
       */
      public Builder setServertime(int value) {
        bitField0_ |= 0x00000001;
        servertime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 servertime = 1;</code>
       */
      public Builder clearServertime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        servertime_ = 0;
        onChanged();
        return this;
      }

      // required int32 status = 2;
      private int status_ ;
      /**
       * <code>required int32 status = 2;</code>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 status = 2;</code>
       */
      public int getStatus() {
        return status_;
      }
      /**
       * <code>required int32 status = 2;</code>
       */
      public Builder setStatus(int value) {
        bitField0_ |= 0x00000002;
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 status = 2;</code>
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000002);
        status_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:OPSnatchFragmentRet)
    }

    static {
      defaultInstance = new OPSnatchFragmentRet(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:OPSnatchFragmentRet)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_OPSnatchFragment_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_OPSnatchFragment_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_OPSnatchFragmentRet_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_OPSnatchFragmentRet_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024SnatchFragment.proto\"8\n\020OPSnatchFragme" +
      "nt\022\020\n\010playerid\030\001 \002(\005\022\022\n\nfragmentid\030\002 \002(\005" +
      "\"9\n\023OPSnatchFragmentRet\022\022\n\nservertime\030\001 " +
      "\002(\005\022\016\n\006status\030\002 \002(\005B\035\n\033com.oldmountain.d" +
      "zm.message"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_OPSnatchFragment_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_OPSnatchFragment_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_OPSnatchFragment_descriptor,
              new java.lang.String[] { "Playerid", "Fragmentid", });
          internal_static_OPSnatchFragmentRet_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_OPSnatchFragmentRet_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_OPSnatchFragmentRet_descriptor,
              new java.lang.String[] { "Servertime", "Status", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
