
# Turn on or off logging.
config.logging=true
#

application.package=com.youai.dreamonepiece.platform.nd91

#
# Set the keystore properties for signing the application.
#
key.store=DreamOnePiece_91.keystore
key.alias=mobile.keystore

key.store.password=120213
key.alias.password=120213


#
#java.encoding=UTF-8
#java.target=1.6
#java.source=1.6
java.compilerargs=-nowarn
#
adb.device.arg=-d
verbose=false

#debug-obfuscation-check=false
#release-obfuscation-check=true


