
# Turn on or off logging.
config.logging=true
#

application.package=com.youai.dreamonepiece.platform.yingyonghui

#
# Set the keystore properties for signing the application.
#
key.store=DreamOnePiece_YingYongHui.keystore
key.alias=DreamOnePiece_YingYongHui.keystore

key.store.password=youaihzw
key.alias.password=youaihzw


#
#java.encoding=UTF-8
#java.target=1.6
#java.source=1.6
java.compilerargs=-nowarn
#
adb.device.arg=-d
verbose=false

#debug-obfuscation-check=false
#release-obfuscation-check=true


