log4j.rootLogger=INFO,console,file

#\u8BBE\u7F6E\u6BCF\u4E2A\u65E5\u5FD7\u6587\u4EF6\u7684\u6700\u5927\u5BB9\u91CF
#log4j.appender.MaxFileSize=200MB

#\u4E1A\u52A1\u63A5\u53E3\u591A\u65E5\u5FD7log\u793A\u4F8B\uFF0C\u7528\u4E8E\u63A5\u53E3\u6027\u80FD\u8C03\u4F18\u548C\u9891\u6B21\u7EDF\u8BA1\u4F7F\u7528\u4EE5\u53CA\u64CD\u4F5C\u4FE1\u606F\u7EDF\u8BA1
#eg.start  \u540E\u7EED\u589E\u52A0\u5F00\u5173\u63A7\u5236\u8BE5log\u662F\u5426\u5F00\u542F
log4j.logger.FightEndBattle=debug,FightEndBattle
log4j.logger.FightEndInfo=debug,FightEndInfo
log4j.logger.EquipInfo=debug,EquipInfo
log4j.logger.UserBasicInfo=debug,UserBasicInfo
log4j.logger.DiscipleInfo=debug,DiscipleInfo
log4j.logger.SkillInfo=debug,SkillInfo
log4j.logger.BattleArrayInfo=debug,BattleArrayInfo
log4j.logger.ToolInfo=debug,ToolInfo
log4j.logger.MarketInfo=debug,MarketInfo
log4j.logger.FriendInfo=debug,FriendInfo
log4j.logger.ShopInfo=debug,ShopInfo
log4j.logger.SkillBookInfo=debug,SkillBookInfo
log4j.logger.AdventureInfo=debug,AdventureInfo
log4j.logger.SysMsgInfo=debug,SysMsgInfo
log4j.logger.ChatInfo=debug,ChatInfo
log4j.logger.TitleInfo=debug,TitleInfo
log4j.logger.TeamBuffInfo=debug,TeamBuffInfo
log4j.logger.UserInfo=debug,UserInfo
log4j.logger.PlayerLoginInfo=debug,PlayerLoginInfo
log4j.logger.BoxRewardInfo=debug,BoxRewardInfo
log4j.logger.RecruitDiscipleInfo=debug,RecruitDiscipleInfo
log4j.logger.GoldCost=debug,GoldCost
log4j.logger.LandDataError=debug,LandDataError
log4j.logger.CdkeyReward=debug,CdkeyReward
log4j.logger.RechargeInfo=debug,RechargeInfo
log4j.logger.PlayerLogoutInfo=debug,PlayerLogoutInfo
log4j.logger.OnlineCount=debug,OnlineCount
log4j.logger.EquipDiamond=debug,EquipDiamond
log4j.logger.ChallengeActivate=debug,ChallengeActivate
log4j.logger.RewardDropActivate=debug,RewardDropActivate



#eg.end
#Succession

log4j.appender.console=org.apache.log4j.ConsoleAppender
log4j.appender.console.layout=org.apache.log4j.PatternLayout
log4j.appender.console.layout.ConversionPattern=%-5p %d [%F,%L] - %m%n

log4j.appender.file=org.apache.log4j.DailyRollingFileAppender
log4j.appender.file.layout=org.apache.log4j.PatternLayout
log4j.appender.file.datePattern='.'yyyyMMdd
log4j.appender.file.append=true
log4j.appender.file.layout.ConversionPattern=%-5p %d [%F,%L] - %m%n
log4j.appender.file.File=../logs/Server.log

#log4j.appender.file.File=D:/rolling.log=======
#to fightEndBattle
log4j.appender.FightEndBattle=org.apache.log4j.DailyRollingFileAppender
log4j.appender.FightEndBattle.File=../logs/FightEndBattle.log
log4j.appender.FightEndBattle.datePattern='.'yyyyMMdd
log4j.appender.FightEndBattle.append=true
log4j.appender.FightEndBattle.layout=org.apache.log4j.PatternLayout
log4j.appender.FightEndBattle.layout.ConversionPattern=%-5p %d [%F,%L] - %m%n
#to fightEndInfo
log4j.appender.FightEndInfo=org.apache.log4j.DailyRollingFileAppender
log4j.appender.FightEndInfo.File=../logs/FightEndInfo.log
log4j.appender.FightEndInfo.datePattern='.'yyyyMMdd
log4j.appender.FightEndInfo.append=true
log4j.appender.FightEndInfo.layout=org.apache.log4j.PatternLayout
log4j.appender.FightEndInfo.layout.ConversionPattern=%-5p %d [%F,%L] - %m%n
#to EquipInfo
log4j.appender.EquipInfo=org.apache.log4j.DailyRollingFileAppender
log4j.appender.EquipInfo.File=../logs/EquipInfo.log
log4j.appender.EquipInfo.datePattern='.'yyyyMMdd
log4j.appender.EquipInfo.append=true
log4j.appender.EquipInfo.layout=org.apache.log4j.PatternLayout
log4j.appender.EquipInfo.layout.ConversionPattern=%-5p %d [%F,%L] - %m%n

#to UserBasicInfo
log4j.appender.UserBasicInfo=org.apache.log4j.DailyRollingFileAppender
log4j.appender.UserBasicInfo.File=../logs/UserBasicInfo.log
log4j.appender.UserBasicInfo.datePattern='.'yyyyMMdd
log4j.appender.UserBasicInfo.append=true
log4j.appender.UserBasicInfo.layout=org.apache.log4j.PatternLayout
log4j.appender.UserBasicInfo.layout.ConversionPattern=%-5p %d [%F,%L] - %m%n

#to DiscipleInfo
log4j.appender.DiscipleInfo=org.apache.log4j.DailyRollingFileAppender
log4j.appender.DiscipleInfo.File=../logs/DiscipleInfo.log
log4j.appender.DiscipleInfo.datePattern='.'yyyyMMdd
log4j.appender.DiscipleInfo.append=true
log4j.appender.DiscipleInfo.layout=org.apache.log4j.PatternLayout
log4j.appender.DiscipleInfo.layout.ConversionPattern=%-5p %d [%F,%L] - %m%n

#to SkillInfo
log4j.appender.SkillInfo=org.apache.log4j.DailyRollingFileAppender
log4j.appender.SkillInfo.File=../logs/SkillInfo.log
log4j.appender.SkillInfo.datePattern='.'yyyyMMdd
log4j.appender.SkillInfo.append=true
log4j.appender.SkillInfo.layout=org.apache.log4j.PatternLayout
log4j.appender.SkillInfo.layout.ConversionPattern=%-5p %d [%F,%L] - %m%n

#to BattleArrayInfo
log4j.appender.BattleArrayInfo=org.apache.log4j.DailyRollingFileAppender
log4j.appender.BattleArrayInfo.File=../logs/BattleArrayInfo.log
log4j.appender.BattleArrayInfo.datePattern='.'yyyyMMdd
log4j.appender.BattleArrayInfo.append=true
log4j.appender.BattleArrayInfo.layout=org.apache.log4j.PatternLayout
log4j.appender.BattleArrayInfo.layout.ConversionPattern=%-5p %d [%F,%L] - %m%n

#to ToolInfo
log4j.appender.ToolInfo=org.apache.log4j.DailyRollingFileAppender
log4j.appender.ToolInfo.File=../logs/ToolInfo.log
log4j.appender.ToolInfo.datePattern='.'yyyyMMdd
log4j.appender.ToolInfo.append=true
log4j.appender.ToolInfo.layout=org.apache.log4j.PatternLayout
log4j.appender.ToolInfo.layout.ConversionPattern=%-5p %d [%F,%L] - %m%n

#to MarketInfo
log4j.appender.MarketInfo=org.apache.log4j.DailyRollingFileAppender
log4j.appender.MarketInfo.File=../logs/MarketInfo.log
log4j.appender.MarketInfo.datePattern='.'yyyyMMdd
log4j.appender.MarketInfo.append=true
log4j.appender.MarketInfo.layout=org.apache.log4j.PatternLayout
log4j.appender.MarketInfo.layout.ConversionPattern=%-5p %d [%F,%L] - %m%n

#to FriendInfo
log4j.appender.FriendInfo=org.apache.log4j.DailyRollingFileAppender
log4j.appender.FriendInfo.File=../logs/FriendInfo.log
log4j.appender.FriendInfo.datePattern='.'yyyyMMdd
log4j.appender.FriendInfo.append=true
log4j.appender.FriendInfo.layout=org.apache.log4j.PatternLayout
log4j.appender.FriendInfo.layout.ConversionPattern=%-5p %d [%F,%L] - %m%n

#to ShopInfo
log4j.appender.ShopInfo=org.apache.log4j.DailyRollingFileAppender
log4j.appender.ShopInfo.File=../logs/ShopInfo.log
log4j.appender.ShopInfo.datePattern='.'yyyyMMdd
log4j.appender.ShopInfo.append=true
log4j.appender.ShopInfo.layout=org.apache.log4j.PatternLayout
log4j.appender.ShopInfo.layout.ConversionPattern=%-5p %d [%F,%L] - %m%n

#to SkillBookInfo
log4j.appender.SkillBookInfo=org.apache.log4j.DailyRollingFileAppender
log4j.appender.SkillBookInfo.File=../logs/SkillBookInfo.log
log4j.appender.SkillBookInfo.datePattern='.'yyyyMMdd
log4j.appender.SkillBookInfo.append=true
log4j.appender.SkillBookInfo.layout=org.apache.log4j.PatternLayout
log4j.appender.SkillBookInfo.layout.ConversionPattern=%-5p %d [%F,%L] - %m%n

#to AdventureInfo
log4j.appender.AdventureInfo=org.apache.log4j.DailyRollingFileAppender
log4j.appender.AdventureInfo.File=../logs/AdventureInfo.log
log4j.appender.AdventureInfo.datePattern='.'yyyyMMdd
log4j.appender.AdventureInfo.append=true
log4j.appender.AdventureInfo.layout=org.apache.log4j.PatternLayout
log4j.appender.AdventureInfo.layout.ConversionPattern=%-5p %d [%F,%L] - %m%n

#to SysMsgInfo
log4j.appender.SysMsgInfo=org.apache.log4j.DailyRollingFileAppender
log4j.appender.SysMsgInfo.File=../logs/SysMsgInfo.log
log4j.appender.SysMsgInfo.datePattern='.'yyyyMMdd
log4j.appender.SysMsgInfo.append=true
log4j.appender.SysMsgInfo.layout=org.apache.log4j.PatternLayout
log4j.appender.SysMsgInfo.layout.ConversionPattern=%-5p %d [%F,%L] - %m%n

#to ChatInfo
log4j.appender.ChatInfo=org.apache.log4j.DailyRollingFileAppender
log4j.appender.ChatInfo.File=../logs/ChatInfo.log
log4j.appender.ChatInfo.datePattern='.'yyyyMMdd
log4j.appender.ChatInfo.append=true
log4j.appender.ChatInfo.layout=org.apache.log4j.PatternLayout
log4j.appender.ChatInfo.layout.ConversionPattern=%-5p %d [%F,%L] - %m%n

#to TitleInfo
log4j.appender.TitleInfo=org.apache.log4j.DailyRollingFileAppender
log4j.appender.TitleInfo.File=../logs/TitleInfo.log
log4j.appender.TitleInfo.datePattern='.'yyyyMMdd
log4j.appender.TitleInfo.append=true
log4j.appender.TitleInfo.layout=org.apache.log4j.PatternLayout
log4j.appender.TitleInfo.layout.ConversionPattern=%-5p %d [%F,%L] - %m%n

#to TeamBuffInfo
log4j.appender.TeamBuffInfo=org.apache.log4j.DailyRollingFileAppender
log4j.appender.TeamBuffInfo.File=../logs/TeamBuffInfo.log
log4j.appender.TeamBuffInfo.datePattern='.'yyyyMMdd
log4j.appender.TeamBuffInfo.append=true
log4j.appender.TeamBuffInfo.layout=org.apache.log4j.PatternLayout
log4j.appender.TeamBuffInfo.layout.ConversionPattern=%-5p %d [%F,%L] - %m%n

#to UserInfo
log4j.appender.UserInfo=org.apache.log4j.DailyRollingFileAppender
log4j.appender.UserInfo.File=../logs/UserInfo.log
log4j.appender.UserInfo.datePattern='.'yyyyMMdd
log4j.appender.UserInfo.append=true
log4j.appender.UserInfo.layout=org.apache.log4j.PatternLayout
log4j.appender.UserInfo.layout.ConversionPattern=%-5p %d [%F,%L] - %m%n

#to PlayerLoginInfo
log4j.appender.PlayerLoginInfo=org.apache.log4j.DailyRollingFileAppender
log4j.appender.PlayerLoginInfo.File=../logs/PlayerLoginInfo.log
log4j.appender.PlayerLoginInfo.datePattern='.'yyyyMMdd
log4j.appender.PlayerLoginInfo.append=true
log4j.appender.PlayerLoginInfo.layout=org.apache.log4j.PatternLayout
log4j.appender.PlayerLoginInfo.layout.ConversionPattern=%-5p %d [%F,%L] - %m%n

#to BoxRewardInfo
log4j.appender.BoxRewardInfo=org.apache.log4j.DailyRollingFileAppender
log4j.appender.BoxRewardInfo.File=../logs/BoxRewardInfo.log
log4j.appender.BoxRewardInfo.datePattern='.'yyyyMMdd
log4j.appender.BoxRewardInfo.append=true
log4j.appender.BoxRewardInfo.layout=org.apache.log4j.PatternLayout
log4j.appender.BoxRewardInfo.layout.ConversionPattern=%-5p %d [%F,%L] - %m%n

#to RecruitDiscipleInfo
log4j.appender.RecruitDiscipleInfo=org.apache.log4j.DailyRollingFileAppender
log4j.appender.RecruitDiscipleInfo.File=../logs/RecruitDiscipleInfo.log
log4j.appender.RecruitDiscipleInfo.datePattern='.'yyyyMMdd
log4j.appender.RecruitDiscipleInfo.append=true
log4j.appender.RecruitDiscipleInfo.layout=org.apache.log4j.PatternLayout
log4j.appender.RecruitDiscipleInfo.layout.ConversionPattern=%-5p %d [%F,%L] - %m%n

#to GoldCost
log4j.appender.GoldCost=org.apache.log4j.DailyRollingFileAppender
log4j.appender.GoldCost.File=../logs/GoldCost.log
log4j.appender.GoldCost.datePattern='.'yyyyMMdd
log4j.appender.GoldCost.append=true
log4j.appender.GoldCost.layout=org.apache.log4j.PatternLayout
log4j.appender.GoldCost.layout.ConversionPattern=%-5p %d [%F,%L] - %m%n

#to landdata
log4j.appender.LandDataError=org.apache.log4j.DailyRollingFileAppender
log4j.appender.LandDataError.File=../logs/DataLandError.log
log4j.appender.LandDataError.datePattern='.'yyyyMMdd
log4j.appender.LandDataError.append=true
log4j.appender.LandDataError.layout=org.apache.log4j.PatternLayout
log4j.appender.LandDataError.layout.ConversionPattern=%-5p %d [%F,%L] - %m%n

#to CdkeyReward
log4j.appender.CdkeyReward=org.apache.log4j.DailyRollingFileAppender
log4j.appender.CdkeyReward.File=../logs/CdkeyReward.log
log4j.appender.CdkeyReward.datePattern='.'yyyyMMdd
log4j.appender.CdkeyReward.append=true
log4j.appender.CdkeyReward.layout=org.apache.log4j.PatternLayout
log4j.appender.CdkeyReward.layout.ConversionPattern=%-5p %d [%F,%L] - %m%n

#to RechargeInfo
log4j.appender.RechargeInfo=org.apache.log4j.DailyRollingFileAppender
log4j.appender.RechargeInfo.File=../logs/RechargeInfo.log
log4j.appender.RechargeInfo.datePattern='.'yyyyMMdd
log4j.appender.RechargeInfo.append=true
log4j.appender.RechargeInfo.layout=org.apache.log4j.PatternLayout
log4j.appender.RechargeInfo.layout.ConversionPattern=%-5p %d [%F,%L] - %m%n

#to PlayerLogoutInfo
log4j.appender.PlayerLogoutInfo=org.apache.log4j.DailyRollingFileAppender
log4j.appender.PlayerLogoutInfo.File=../logs/PlayerLogoutInfo.log
log4j.appender.PlayerLogoutInfo.datePattern='.'yyyyMMdd
log4j.appender.PlayerLogoutInfo.append=true
log4j.appender.PlayerLogoutInfo.layout=org.apache.log4j.PatternLayout
log4j.appender.PlayerLogoutInfo.layout.ConversionPattern=%-5p %d [%F,%L] - %m%n

#to onlineUserCount
log4j.appender.OnlineCount=org.apache.log4j.DailyRollingFileAppender
log4j.appender.OnlineCount.File=../logs/OnlineCount.log
log4j.appender.OnlineCount.datePattern='.'yyyyMMdd
log4j.appender.OnlineCount.append=true
log4j.appender.OnlineCount.layout=org.apache.log4j.PatternLayout
log4j.appender.OnlineCount.layout.ConversionPattern=%-5p %d [%F,%L] - %m%n

#to EquipDiamond
log4j.appender.EquipDiamond=org.apache.log4j.DailyRollingFileAppender
log4j.appender.EquipDiamond.File=../logs/EquipDiamond.log
log4j.appender.EquipDiamond.datePattern='.'yyyyMMdd
log4j.appender.EquipDiamond.append=true
log4j.appender.EquipDiamond.layout=org.apache.log4j.PatternLayout
log4j.appender.EquipDiamond.layout.ConversionPattern=%-5p %d [%F,%L] - %m%n

#to ChallengeActivate
log4j.appender.ChallengeActivate=org.apache.log4j.DailyRollingFileAppender
log4j.appender.ChallengeActivate.File=../logs/ChallengeActivate.log
log4j.appender.ChallengeActivate.datePattern='.'yyyyMMdd
log4j.appender.ChallengeActivate.append=true
log4j.appender.ChallengeActivate.layout=org.apache.log4j.PatternLayout
log4j.appender.ChallengeActivate.layout.ConversionPattern=%-5p %d [%F,%L] - %m%n

#to RewardDropActivate
log4j.appender.RewardDropActivate=org.apache.log4j.DailyRollingFileAppender
log4j.appender.RewardDropActivate.File=../logs/RewardDropActivate.log
log4j.appender.RewardDropActivate.datePattern='.'yyyyMMdd
log4j.appender.RewardDropActivate.append=true
log4j.appender.RewardDropActivate.layout=org.apache.log4j.PatternLayout
log4j.appender.RewardDropActivate.layout.ConversionPattern=%-5p %d [%F,%L] - %m%n
